### ISSUE TITLE
Suggestion: option to exclude remarks, engine time and flight time in the logbook printing module

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#1053]

**Comment by ericberman** [comment]
Flight/engine time is already controlled by the option "Display the following in tables of your flights:: Hobbs time, flight times, and engine times for flights" under Profile->Preferences->Flight Entry and display.

For remarks, you can use "///" to exclude everything that follows on a flight-by-flight basis, or use the "Condensed" layout (which has no remarks).  Otherwise, I'm not quite sure what problem such an option would be solving?  Note too that a remarks column is mandated for some layouts (such as EASA)

**Comment by zartom** [comment]
Well I do want them to be displayed anywhere except on PDFs I might send to potential future employers...

**Comment by ericberman** [comment]
"them" = times or "them" = remarks?  If remarks, I don't understand why you'd want to suppress all remarks.  E.g., if you have a flight where you had an engine failure, surely you'd want to include that fact even in the PDF, right?  It's the flight where you waxed poetic about the scenery where you might want to suppress all of that.  If you do a bulk edit to your logbook and put "///", you can include the bits you want while excluding the bits you don't want, no?

**Comment by zartom** [comment]
Regarding Engine and Flight Time, I never want to display them in any PDF

As for remarks, let's say I'm sending a trimmed copy of my logbook with only the last 6, 12, 24 months of flights in it as per someone's request, every remark there will be just me mentioning the time of day when I was starting my shift as PF, PM or relief pilot on a long haul flight because this is what I use it for nowadays. The "///" method will of course work, it is just more work to bulk edit it with Excel than just exclude it for a one-time print view

**Comment by ericberman** [comment]
Flight/engine time is already controlled by the option "Display the following in tables of your flights:: Hobbs time, flight times, and engine times for flights" under Profile->Preferences->Flight Entry and display.

For remarks, you can use "///" to exclude everything that follows on a flight-by-flight basis, or use the "Condensed" layout (which has no remarks).  Otherwise, I'm not quite sure what problem such an option would be solving?  Note too that a remarks column is mandated for some layouts (such as EASA)

**Comment by ericberman** [comment]
My point about flight/engine time was that the option already exists, it's just not in the print options.  So there's no additional feature required there.  

Why not just use the condensed layout (which has no comments) for the scenario you describe?
