### ISSUE TITLE
Countries visited counter in achievements is incorrect 

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#1077]
![Screenshot_20230404_101446_Chrome](https://user-images.githubusercontent.com/1769078/229731241-39ec5e5d-3d59-49b5-b5e0-912526c0ced6.jpg)
![Screenshot_20230404_101509_Chrome](https://user-images.githubusercontent.com/1769078/229731254-1a1f9d39-8130-4cf1-b4f8-5eb66573e042.jpg)

**Comment by ericberman** [comment]
Hi, Tom.  I can't track this down without knowing whose data that is - your account has a lot more flights and a lot more airports than that.   Email me the account email address so I can look?  I did a test account with a single flight between CNF4 and CYTZ and it doesn't show 2 countries (doesn't show that achievement at all).

**Comment by zartom** [comment]
My friend's
***@***.***

בתאריך יום ג׳, 4 באפר׳ 2023, 17:50, מאת Eric Berman ‏<
***@***.***>:

**Comment by ericberman** [comment]
Not a bug.  Your friend has a flight on March 21 2018 at the airport LLSD, which is in Israel.  This is getting excluded from visited airports because it has no landings recorded (or other time, for that matter), but for the "Countries Visited" I don't do that level of filtering.   See https://myflightbookblog.blogspot.com/2017/11/how-are-visited-airports-computed.html for visited airports specifically; the achievements, though, is just about where you recorded some flying.
![image](https://user-images.githubusercontent.com/16455286/229855296-bdb37785-c4c5-4439-a450-21f072451bfd.png)

**Comment by zartom** [comment]
Got it! thanks
