### ISSUE TITLE
Saved search delete button launches the search

### ISSUE THREAD

**Issue by pballer2oo7** [ericberman/MyFlightbookWeb#1089]
![image](https://github.com/ericberman/MyFlightbookWeb/assets/7807540/b76bab28-2fc1-40eb-8464-6a6670cae33d)

1. Click the "red X" next to a saved search
2. The search launches

Browsing back to the saved searches list shows that the search was indeed deleted but it loading the search initially is perhaps unexpected.

**Comment by ericberman** [comment]
I'm not able to reproduce this?

Here's what I do:
 * Fill out a search query for trailing 12 months.
 * Name the query as "trailing 12" and click "Save and Search" => Shows results for previous 12 months, makes sense
 * Reset to show all my flights, or just click on the Logbook tab
 * Click to expand the search form
 * Click on "Saved Searches"
 * Click the "x" next to "trailing 12"
 * ==> Search is deleted, but I'm still seeing all of my flights.

I wonder if what happened for you was that you still had the search active.  E.g., if you omitted the "reset to show all my flights" step above (so your search results still contained the trailing 12-month flights), then deleting the saved search does not reset the active search.  That's by design.  The active search is your current context; deleting a saved query is simply affecting which search templates are in the database.

**Comment by pballer2oo7** [comment]
> I wonder if what happened for you was that you still had the search active.... The active search is your current context; deleting a saved query is simply affecting which search templates are in the database.

Ya thats definitely it. Makes sense to me now.
