### ISSUE TITLE
Entering the same time for “Last Landing” and “Block In Time” causes “Flight end time is after block in time” warning

### ISSUE THREAD

**Issue by mpfusion** [ericberman/MyFlightbookWeb#1099]
Description
----------------
Entering the same time for “Last Landing” and “Block In Time” causes in “Flight end time is after block in time” when checking flights using Logbook → Check Flights.

To reproduce
--------------------
- Create a new flight: New Flight
- In the Cockpit
  Click on (Tap for Now) and enter e.g.

     Block Out Time: 2023-07-09 19:20 (UTC)
     First Takoff:   2023-07-09 19:21 (UTC)
     Last Landing:   2023-07-09 19:22 (UTC)
     Block In Time:  2023-07-09 19:22 (UTC)

Then enter:
    PIC: 0:02
    Total: 0:02

Then add the flight. Go to the web app to Logbook → Check Flights → (Select All) → Check Flights

Result
---------

    Flight end time is after block in time

Expected Result
-----------------------
This should not cause a warning because the flight end time does in fact *not* end after the block in time.

Notes
--------
Creating the flight in the web app (in contrast to the iOS app) doesn't cause the warning and works as expected, although the times entered are the same. Actually editing the flight using the web app and deleting the 19:22 in “Last Landing” and “Block In Time” and writing 19:22 (notice: no change!) and updating the flight also causes the warning to disappear. Editing the value on the iOS app and “replacing” the 19:22 with 19:22 causes the warning to reappear.

Version
----------
version: myflightbook 2023.06.22.1

**Comment by ericberman** [comment]
This is really a won't fix.  It's due to block times having seconds truncated and takeoff/landing time not truncated.  So you're really comparing something like 2023-07-09 19:22:25 as the last landing time to 2023-07-09 19:22:00 as the block-in time.  Both display as 19:22, but indeed the block time in this scenario is actually slightly some number of seconds behind the landing time.  Very corner case for actual times (seriously - who actually lands and comes to final rest within the same minute?  You'd have to stay on the end of the runway!).  Editing the value causes the issue to disappear because the seconds all get truncated.

I transferred this to the website issues because it looked like it was a check flights issues, but it's not: it's a data issue.  I will consider truncation of the seconds on flight/engine time on the iOS app...

**Comment by mpfusion** [comment]
On Thu, 06 Jul 2023 16:48:29 -0700
Eric Berman ***@***.***> wrote:

> This is really a won't fix.

No problem.

> It's due to block times having seconds truncated and
> takeoff/landing time not truncated.

Maybe truncate takeoff/landing time as well? But there are probably
good reasons it's done the way it is.

> Very corner case for actual times (seriously - who actually lands
> and comes to final rest within the same minute?

I totally agree. Not many users will run into this.

> I will consider truncation of the seconds on flight/engine time on
> the iOS app...

That would make the behaviour consistent with the web app.
