### ISSUE TITLE
Feature suggestion: "Chapter" grouping within logbook

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#236]
Could do it by date ranges (e.g., military service, or ATP training), or explicitly tag items.  Could then show each chapter in a different color, or with breaks of some sort.  This was from a user, but I'm not quite sure what "success" looks like for such a feature.

**Comment by fkrauthan** [comment]
I think beeing able to add simple tags (preferable multiple once) on a per flight base could be really cool. And then you use them for filtering etc. E.g. I could tag all my PPL training flights with a `PPL` tag. And in addition my Solo flights with `Solo` and then can get reports how many flights where part of my PPL training. And to easily and quickly find all my Solo flights etc.

**Comment by ericberman** [comment]
You can certainly already do that - no new feature required.  Just make up any tag like "#PPL#" and put it into the comments.  (Nothing magic about the hashtag prefix/suffix, it just avoids false-positives/false-negatives when searching).  

BTW, Solo time is already a property, and you can search for the presence of given properties, so no need for a tag for that.

**Comment by fkrauthan** [comment]
Oh cool I didn't realize that. I did know about Solo time was just trying to illustrate an example *haha* so what is then the idea behind this ticket? Just to have the ability of color code things? because in this case maybe add a simple feature where you can specify colors for a tag and then in the big list just apply that tag color as background color (maybe use the first tag's color or something like that).

**Comment by ericberman** [comment]
Ooh, now **that's** an interesting idea - color coding by the tag you find.

**Comment by ericberman** [comment]
Should add it to printing, though it's a bit harder to do so there.

**Comment by ericberman** [comment]
Should add it to printing, though it's a bit harder to do so there.
