### ISSUE TITLE
Pre-defined queries

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#324]
Some useful queries may not be easy or possible to specify with the current search facility.  A useful enhancement would be for the SEARCH screen to offer certain pre-defined queries, or queries a user might define and save for himself (like the way templates work).

Some of the interesting queries include

- "simulated OR actual IMC time"
- Experience of a certain sort (“Time as SIC in turbine aircraft”)
- Flights satisfying certain Checkride criteria
- Insurance queries (“Hours in complex aircraft in the last 12 months”)
- Flights that contribute to instrument currency (IMC OR simulated OR holding OR approaches).

**Comment by ericberman** [comment]
I already have the notion of named queries that you can save, and a lot of these you can get by simply clicking on an item in totals (e.g., turbine time - click on that to see just flights in turbine aircraft, then click on SIC to see your SIC turbine time.)

And flights satisfying certain checkride criteria is often unanswerable - see [here](https://myflightbookblog.blogspot.com/2018/12/ratings-progress-why-cant-i-click.html) for why.

The key new thing here, I think, is the instrument currency query (holding OR approaches; note that IMC or simulated IMC is actually not a requirement for instrument currency!)

**Comment by KayRJay** [comment]
User-defined named queries could work like templates ... any arbitrary query a user might enter could be saved (from the Search screen, probably), named, and shared with others.   More open ended than just clicking on one or a few properties that are ANDed together.

**Comment by ericberman** [comment]
Already can save the query from the search screen - click the down arrow by the "Find Matching Flights" button.  Sharing is interesting, but I don't think it's nearly as rich as with templates and it is decidedly more fragile and complex.  E.g., taking a quick look at queries that people have saved, a lot of them are for searches in a list of models or a list of aircraft - that's almost by definition not shareable.

**Comment by KayRJay** [comment]
I agree that there’s probably little value in sharing user-defined searches.  However, it would be helpful if you defined and named some pre-built search criteria for things that are hard or impossible to do now (e.g, the OR of sim and actual IFR).   These search criteria would be “shared” in the sense of being available to all users.  You could also allow a user to change the specs of such a search and save it for their own use.
 
I didn’t see the down arrow at first.   Might be better to have a button “Save this search” next to the “Find Matching Flights” button.   

Also, it seems most natural to name and save the query after looking at the result, not before (e.g., before pressing “Find matching flights”).   Until you get the result you want, the user may not know he wants to save the search.   And, this approach would allow a user to refine the search, replacing or changing the criteria used in a saved search.

It would also be more natural and consistent to specify use of an existing search up where other criteria are specified ...

“Find flights matching a saved search ... [?]” would pop up a list of saved searches.

Summarizing ...

- Use named searches in the same general way as other parameterized searches
- Name, save, refine and delete saved searches after seeing the result, not before
- In place of the obscure down arrow, use a button (unless displaying a menu)

This whole topic is of minor importance, but over all, the present UI is a bit obscure.   If you were starting from scratch, you might restructure this whole thing.  It may not be worth it now, of course.  Do you know how many people use saved searches?   Do you think more people would do so if the UI were more obvious?

Ken

P.S. Hello from HKG, where we are in a 6 hour layover on our way to Bali ...

**Comment by ericberman** [comment]
Now that I have fixed #323 and you can search for Approaches OR holds, I think all of the key scenarios driving this feature are addressed:
 * You can search for instrument currency experience (approaches OR holds)
 * You can already create your own queries.  Yes, the UI is unobtrusive - that is deliberate.  By design, you should be able to get most common searches automatically (see below); I don't want to overly clutter the UI making super obvious a feature that you don't know that you want (and probably don't in fact need).  Saving searches is the "fall back" for when none of the other scenarios (below) do it for you, so if I'm doing those correctly (and I think I am), saved searches become a cool little power feature, not a core feature.
 * Totals are already clickable, which makes LOTS of system-defined (as opposed to user-defined) canned queries unnecessary.  E.g., click on your turbine total to see your turbine time, or click on your AMEL total to see totals in AMEL aircraft and view your total PIC time there.  I.e., anything that can be totaled is already a click away for searching.  This model also ensures no empty click-to-search functionality.  E.g., if you have no turbine time, you can't click to see your (non-existant) turbine time.
 * Ratings progress can't be done with database queries much less with "saved" queries.  That's why I have a separate page for them.  I don't do this in MySQL under the covers either.  Too many substitutions, exclusions, either/or stuff, measuring distance between airports, etc.  They're also non-deterministic (which is why in general they're not clickable), in the sense that there are often multiple answers to the question of "which flights contributed to my progress against this rating requirement"
 * Probably the most common scenario for doing a saved query doesn't require a saved query.  Namely insurance or FBO rules.  E.g., my club has a rule that to be insured in the Mooney, we need to have 3 hours of PIC time in the Mooney every 180 days.  Sure, a query for that is nice, but you know what's nicer?   A custom currency rule (which is exactly what I do).  And yes, since it translates directly to a query, it's also clickable in currency.  So it's a far better solution than creating/saving a query.

I get naming the query after looking at the result, but note that the search context is saved, so you can go name it after you get what you want without having to redo the search.

For those reasons, I think this issue has largely been rendered moot, and I'm won't-fixing it.
