### ISSUE TITLE
Range searches

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#326]
For many numeric parameters, it would be helpful to be able to do range searches.   Sample queries might be flights over a certain duration, or greater than 10 miles and less than 100.

A possible UI might be similar to this:

**Flight is described with these limits (click to show) [?]**   … or use the word “parameters” if you don’t like “limits”.  With [?] for guidance.

Distance flown      >= ____ and  <= _____         Flight Duration >= ____ and  <=  _______
Maximum altitude >= ____ and  <= _____         Fuel Burn/hour  >= ____ and  <=  _______
Takeoff temperature >= __ and  <=  _____        Landing temperature  >= ____ and  <=  _______

where the ____ is an enterable field).   If both limits were entered, it’s a between search, else bounded on only one side.  

The only numeric parameters that would appear in this section would be the ones the user has used or are in the applicable template(s).

**Comment by ericberman** [comment]
I am leaning towards won't fix on this.  It's a ton of work: the database query is the (relatively) easy part, but there's a bunch of UI for this on the website, and then I have to replicate that UI on the mobile apps as well (since the Query object gets serialized and displayed/edited/shared there).  All doable, but a lot.

I'll keep this open if I can get some realistic use cases.  By which I mean "here's a real problem people have which range searches solve", as opposed to a hypothetical "I could imagine if the functionality were there someone might poke around and use it for its own sake."  For the latter, I'm happy to say "go have fun with Excel pivot tables which excel (pardon the pun) at such analysis."  

The key real scenarios that I know of (so far) for people use searching for today are generally:
 * Insurance questions
 * Identify flights that contribute towards currency or towards a rating
 * Finding a specific flight (cool pictures, experience of a new aircraft, landing at a cool airport) that they want to reminisce about or share or remember some detail about; for these queries, inevitably a search on date/aircraft/model/comments/etc. is much more reliable than a range.
 * Compute combination totals (e.g., how much solo multi-engine night flight do I have?)

The most realistic range scenario I can think of is literally "range": i.e., distance.  This is because ratings require cross-country time logged using a given distance threshold, or require a flight that meets that distance.  The cross-country thing is generally done by explicitly logging cross-country flights using a particular threshold (see my [blog post](https://myflightbookblog.blogspot.com/2018/08/logging-cross-country-time.html) about that), so just searching for "has cross-country time" (optionally also looking for the presence of <25nm, <50nm, or >50nm, which are properties you can search on) solves that.  

The ratings progress is vastly more tricky because it inevitably has further requirements; the ratings progress functionality does all of that measurement precisely because search fundamentally can't do it.  Examples that preclude search from working for this:
 * Distance is rarely logged (and isn't reliable even if it is), but it can generally be computed.  To do this efficiently (since, for reasons I've explained in email), you can't do it as a join; you have to do a couple of separate queries and then walk through the flights.
 * The rules impose additional requirements, like one airport having to be 250nm away from the airport of departure - unless you're in Hawaii, in which case it's 150nm
 * Even if you find the flights that meet the distance, additional criteria are required (operating control towers, etc.)

But beyond distance I'm trying to think of the scenario where you need to be able to find flights that had, for example, "between 2 and 3 hours of PIC time" or "less than 4 hours of solo", and I'm coming up short, which means that this issue is very low priority and likely to stay that way indefinitely (in which case I should "won't fix" it, since "indefinitely" essentially means "never").

Actual problems that people have that range searches solve?
