### ISSUE TITLE
Use "Public" and "Shared" to indicate different things

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#329]
Currently, users can proactively share a flight using Facebook, Twitter or email.   That's distinct from "publishing" a flight by making certain information available to anyone with the link to the flight.   It is somewhat confusing that both of these are called "sharing" in MyFlightbook now.

The suggestion is to change the property "Is shared" to "Is public" and replace this text

**Sharing
    Share Flight Details  Share details such as route, comments, and pictures with others[?]**

with

Fight Privacy [?]
☐ Make this flight public

If the box is not checked, the flight is not visible even to users with the URL, else basic flight info would be available by URL.

**Comment by KayRJay** [comment]
**Fight Privacy [?]
☐ Make basic details of this flight public**

**Comment by ericberman** [comment]
I'm not sure I want to do this.  
I respect the distinction between the adjective "public" and the verb "Share".  I actually deliberately moved away from "Public" or "Private" to "shared" (adjective) because:
 * "shared" is an adjective, not just a past-tense verb
 * I still need to explain what the difference is, and "shared" seemed to flow better into that description
 * Marking a flight as public actually *does* perform the action of sharing (it gets pulled into the list of sample "recent flights" on the publicly available home page).  So no further action is required for some level of sharing to occur.

**Comment by KayRJay** [comment]
This is up to you, of course.   To me, it’s a question of clarification, and removing confusion.  Your arguments below are somewhat academic.  My view is that users don’t think in these terms.  It’s just a matter of meting clear (and consistent with other online services that have similar functionality).

Specifically, what difference does it make if it is an adjective or verb?  Not to most users.   I don’t get your point 2, as it seems easier to have different words for different things.  And point three is also a bit obscure, but I get your point.

Again, your call of course!  I just thought it important to put it in GitHub so you can record your decision (and thought process) there.

Ken

**Comment by ericberman** [comment]
Right, that's why I didn't close the issue, just added my concerns about doing so.
Point 2 was simply saying that you have to explain what "public" implies.  Current language can answer that in-line.

**Comment by ericberman** [comment]
I still am not comfortable with "public" in this context (though I am in other contexts - e.g., aircraft notes, where I did switch from "shared" to "public").  Of course, under the covers, that's the word I use.  But the flight isn't public, it's just...exposed.  

So I went with a much less abstract terminology: "[x] Allow others to view details of this flight[?]".

**Comment by KayRJay** [comment]
That works!  Thanks.
