### ISSUE TITLE
Videos: displaying in list, viewing parameters, deleting, max size?

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#358]
A few thoughts about video attachments ...

Re: "Show flight images in-line" (pull down option) ... Having a thumbnail display for attached video(s) takes up a lot of space in the list.   It would be sufficient to have the (file) name(s) of the video(s) listed, one per line, with a "play" button to the right.   The pull-down menu option could be changed to "View videos in list" and "View video file names in list" if you want to keep the current functionality.  You could also have two options -- "Show flight images in-line" and "Show videos in-line".

It would be helpful on the Edit and Details pages to see some of the information about the videos: file name, size, creation date, length (mm:ss).  Even though a user could add this information manually, it would be handy if it were saved automatically.

The pencil icon to add a tag and the X to delete a video should be placed to the left of the thumbnail.  If there are several videos on a flight, these icons appear between thumbnails, and it is visually ambiguous which flight they apply to (above or below).

I just temporarily added a 1.6 GB file.   While storage is cheap, you might like to impose a maximum size, especially since there is a way to add links to videos on YouTube, etc.

If a supplied link is not valid, the error is "Video source is not surpported".   Typo.

**Comment by ericberman** [comment]
Comments in reverse order:
 * Typo - thanks, excellent catch, fixed (not yet on live site)
 * Large: videos are currently a gratuity feature for people who donate, so the size is fine.  (That's why I reserve this for donors - videos can indeed grow rapidly in size!)  I think I have a maximum file size set up for the website as a whole for file uploads, so I'm OK with decently long videos.
 * Pencil and "x" - I have these above/below for three reasons: (a) consistency with images, (b) allows the pencil to be next to the comment that it edits, and (c) minimizes the hit to horizontal real-estate, which is generally a scarcer resource than vertical real-estate.  But the visual ambiguity is a good point, especially considering that videos (moreso than images) often have some whitespace at the top.
 * Meta data - I actually don't have any of this!  I can hit Amazon S3 to get file size, but S3 is a dumb bucket and doesn't know a video file from a spreadsheet. I'd have to open the file and parse it out, which means I'd have to understand the video file format (which I really don't want to have to do).  Besides, the video player does show things like that.  E.g., see attached screenshot, which does show length.  I can get modification date (and for images, a few more things)
![screenshot](https://user-images.githubusercontent.com/16455286/63555862-75925000-c4f7-11e9-834f-5e3b293bb409.png).  Not sure name matters as much as the comment.  Name is an arbitrary URL assigned by S3 anyhow...  (BTW, note the gap between the "x" and the video in this image - that whitespace is actually in the video frame itself, not between the x and the video; this happens or not based on resolution of the uploaded video)
 * I think it's weird to show these independently, given the world of facebook/instagram/twitter/etc., where images and videos are interspersed in-line, with always at least a thumbnail of the video.  (Autoplay is a whole separate monstrosity, but I'm not doing autoplay).  Is the issue that video thumbnails tend to be larger?

**Comment by KayRJay** [comment]
Thanks for the quick response.   Comments below ...

> On Aug 22, 2019, at 5:17 PM, Eric Berman <notifications@github.com> wrote:
> 
> Comments in reverse order:
> 
> Typo - thanks, excellent catch, fixed (not yet on live site)

You bet.
> Large: videos are currently a gratuity feature for people who donate, so the size is fine. (That's why I reserve this for donors - videos can indeed grow rapidly in size!) I think I have a maximum file size set up for the website as a whole for file uploads, so I'm OK with decently long videos.
Nice.  Do you allow people who don’t donate to store videos at all?  Do you publicize the size limit on free videos?  Or, with your philosophy, do you simply not show the option to upload a video?
> Pencil and "x" - I have these above/below for three reasons: (a) consistency with images, (b) allows the pencil to be next to the comment that it edits, and (c) minimizes the hit to horizontal real-estate, which is generally a scarcer resource than vertical real-estate. But the visual ambiguity is a good point, especially considering that videos (moreso than images) often have some whitespace at the top.
Good reasons, but still, the ambiguity is an issue.  You could solve the consistency issue by putting the pencil and X adjacent to the image.  Since you don’t actually use the horizontal space to the right of the video, I don’t see the real estate as an issue.   As to having the pencil next to the tag, well, you could simply have a little box, with no pencil, making it more like other optional enterable parameters:

                                   

So, a, b, and c may not really be issues.
> Meta data - I actually don't have any of this! I can hit Amazon S3 to get file size, but S3 is a dumb bucket and doesn't know a video file from a spreadsheet. I'd have to open the file and parse it out, which means I'd have to understand the video file format (which I really don't want to have to do). Besides, the video player does show things like that. E.g., see attached screenshot, which does show length. I can get modification date (and for images, a few more things)

That all makes sense once the file is in S3.  However, for videos that are uploaded within MFB, all that meta data info is (readily?) available from the OS as you’re doing the upload.   You could capture that info for uploaded videos and add it to S3 along with the blob.   Too bad about already uploaded flights.

For videos added with links, I didn’t see any way to display the URL, the comment (“say something”), whether using compact view or not, whether including images in the list or not, or on the details page.   Maybe I’m not looking in the right place or doing something wrong.

Also, is there a way to search for flights that have images or videos (or, in the future, .PDFs)?

Question: when a link to a video is presented, do you go get it and store it in MFB, or just store the link?   What happens down the road if the link is no longer good?
>  <https://user-images.githubusercontent.com/16455286/63555862-75925000-c4f7-11e9-834f-5e3b293bb409.png>.

> Not sure name matters as much as the comment. Name is an arbitrary URL assigned by S3 anyhow... (BTW, note the gap between the "x" and the video in this image - that whitespace is actually in the video frame itself, not between the x and the video; this happens or not based on resolution of the uploaded video)

Right … a good reason to not put the X above the video.  Wastes vertical space while you have plenty of horizontal space to use.
> I think it's weird to show these independently, given the world of facebook/instagram/twitter/etc., where images and videos are interspersed in-line, with always at least a thumbnail of the video. (Autoplay is a whole separate monstrosity, but I'm not doing autoplay). Is the issue that video thumbnails tend to be larger?

I don’t see the comparison with facebook/instagram/twitter.   Showing a video or an image is a very minor part of MFB’s primary function, the log book.  And none of those have nearly the breadth and depth of functionality as MFB does.   I don’t think users would be confused by a different UI in this case.  Even if the comparison was more direct, I don’t see it justifies doing something sub-optimally in the context of MFB.

**Comment by ericberman** [comment]
Replied in email, since above are more questions than issues per se.

**Comment by ericberman** [comment]
Another thought about how to do this that may be more elegant: hover menu.  There are actually currently up to 4 items that can show for an image/video (depending on scenario):
 * Pencil (to edit the comment)
 * "x" (to delete)
 * GPS pin marker (to zoom an associated map on the geotag of the image)
 * "Favorite" star (to pick which image you prefer for an aircraft by default when multiple are available.)

Perhaps the cleanest and most elegant way to do this would be to expose these on mouse hover?

**Comment by KayRJay** [comment]
That sounds nice ... and introduces a paradigm you could use elsewhere (like SAVE and ...).

😃👍

**Comment by ericberman** [comment]
Played with this using the hover menu, wasn't liking it - the hover menu just looked odd by itself.  I did stick the 4 action icons, though, vertically oriented, to the right of the image/video.  I think it looks OK, and clarifies to which image/video they belong.

As for metadata: did a bit of investigating.  It's really a no-go.  I get the uploaded filename and uploaded size and that's about it, and neither is really relevant: many (most?) images/videos come from phones/tablets, where you (the user) never even see the original filename or size.  And besides the filename and size you upload and the filename and size of the processed file typically bear no resemblance whatsoever to each other, so I see no value in preserving/displaying those.  Any interesting metadata (resolution, length, date taken, etc.) must therefore come from inside the image/video.  For images, I already use EXIF for that, which is the standard.  For videos, there is no equivalent standard, and I do NOT want to get into the business of opening up and understanding all the multitude of video file formats.  So I'm going to "won't fix" the meta data.

**Comment by ericberman** [comment]
BTW, thanks for suggesting I play with the layout here.  I like the look much better now.  I also adjusted the width so that the comments won't be wider than the image/video above it and will wrap.  Makes this:
![bad wrap](https://user-images.githubusercontent.com/16455286/63609126-5e9d3d80-c58b-11e9-8f18-9cae30180796.png)
Look like this:
![goodwrap](https://user-images.githubusercontent.com/16455286/63609182-75dc2b00-c58b-11e9-893c-d52743141f11.png)

**Comment by ericberman** [comment]
I'm going to leave images+videos as all/nothing.  Given how many other services all provide intermixed videos and images, I think it's an arbitrary distinction.  The primary reason to turn them all on/off is really for printed layouts/PDFs (i.e., for job interviews - Delta Airlines doesn't care about your images/videos, those are more about leisure flying) or to get a more compact view (in which case images and videos are equal offenders against "compact")

**Comment by KayRJay** [comment]
Much nicer!   Thanks for taking the time to do this ...
