### ISSUE TITLE
When editing/adding a flight, can we preserve query, sort order, and page position on return?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#359]
Makes it easier to preserve context/state if you're adding/editing multiple flights at once.

Note that flight query could be tricky, since you could edit a flight that doesn't match the query...

**Comment by KayRJay** [comment]
It may be appropriate to preserve search context under some scenarios, but probably not in others.  However, preserving the sort order and page position would always be useful after finishing an edit.

Permitting navigating to the "next" or "previous" flight after making edits is a case where not preserving context is the most natural and useful thing to do.  "Next" and "previous" will most likely be thought of as “next flight in time/date”, not “next in the search result set".   This common scenario occurs where there is a need to edit a few, recently entered flights where data entry was garbled.

Typically, if a user enters several flights over recent days, it may occur that a few (2-3?) flights need to be edited due to data entry errors.    In this case, the user would most likely have opened a flight for editing with a single click on a flight from the logbook list, rather than by searching.    With a clear UI on the Edit page, the user would not be confused about which flight he was about to edit.

In a different scenario, where perhaps multiple flights need to be edited, the user might find those flights with a search, review them and conclude that a bulk edit would be the preferable thing to do.    In that case, where the user has a late realization about a set of flights, preserving context might be useful, perhaps to refine the search.   However, most likely some sort of bulk update (perhaps via export, edit in Excel, import) is the most efficient way to do the editing.

**Comment by ericberman** [comment]
All of those comments are why issue #322 is open; (almost) completely separate issue.

**Comment by ericberman** [comment]
All of those comments are why issue #322 is open; (almost) completely separate issue.
