### ISSUE TITLE
Bug: Can add flights in the future

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#379]
Today is Sept 26.   I can add (empty) flights for Sept 27 and 28 with no errors. An attempt to add a flight for Sept 29 results in an error at the time ADD Flight is pressed: "9/29/2019 is in the future. You should fly the flight before recording it."   An attempt to enter Sept 30 in the date field results in a different error: "Date of flight should be today or in the past."

Seems there should be only one error, and it should be issued when the date field is filled in.

**Comment by ericberman** [comment]
Inconsistent check - the UI was allowing up to 3 days in the future, but the back-end was allowing only 2, so if you did 3 days then you'd get the back-end error and if you did 4 days you'd get the front-end error.

Made the UI allow up to 2 days in the future.

Note that allowing *a little* into the future is allowed, if only due to timezone differences (it can be at least a day ahead where you are from where the server or whoever defines "now" is); I allow up to one more day than that, just to avoid any issues.
