### ISSUE TITLE
Plus sign under flight date displays comment in compact view, but not for all flights

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#398]
My 10/31 and 11/2 flights both have comments, but only the 10/31 flight has a plus sign below the date.  It displays the comment for that flight.   This is true if I toggle compact view off and back on.

**Comment by ericberman** [comment]
No bug here.  All flights show comments even in compact view; the plus sign only shows after the comment if there's more information to display (properties, engine times, signature, etc.)

The difference between your 10/31 and 11/2 flight is that the 10/31 flight has a newline at the end of it, so the plus sign is showing after that.  So the behavior is correct as far as the plus sign goes, but I suppose it's reasonable to trim comments so that there's no trailing whitespace.

**Comment by KayRJay** [comment]
aha.   Thanks.
