### ISSUE TITLE
Move pop-up menu to left side of flight list

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#400]
This is really minor, but would improve ease of use ...

Please consider relocating the down arrow with the pop-up menu that's now on the right side of a flight in the log book to the left.  So instead of this:
<img width="900" alt="Screen Shot 2019-11-05 at 12 06 07 PM" src="https://user-images.githubusercontent.com/16978320/68237821-2a9bbb00-ffc5-11e9-9f4f-10de76401247.png">
you'd have this:
<img width="899" alt="Screen Shot 2019-11-05 at 12 08 57 PM" src="https://user-images.githubusercontent.com/16978320/68237788-1952ae80-ffc5-11e9-80e6-db5df244a316.png">

The advantage is that the user's eye doesn't have to scan all the way across the page to hover over the correct down arrow.   Even though there are alternating grey bars to assist the user, it's just a tiny bit of extra eye movement and brain power to select the right flight.   Since clicking on the date (on the left) shows details, it would be more be consistent to operate on a flight (e.g., to edit or delete it) also on the left of the page.

As an alternative, you could consider having the pop-up menu appear when hovering over the date.   You could continue to have the down arrow if you like.  (The advantage of the down arrow is that it makes obvious that there are other things you can do, and this usage is consistent throughout MFB.).  You could still keep clicking on the date (vs. hovering) if you wanted to do so. Further, you could integrate the two operations by making "Show details" one of the options in the pop-up menu. 

In my mind, the best option would be to have the down arrow on the left, with "Show details" as one of the options.   I'd keep the "click on date" option for legacy consistency, but not make it hoverable.

For me, "Show details" is not very often what I want.  I'm usually editing an existing flight, and would rather be able to do so without scanning over to the right side (or, as often happens, inadvertently clicking on the date, seeing the details, then have to scan to the right to edit a flight).

Again, it's a small idea, but would save me microseconds each time I go to edit a flight.

By the way, I will shortly file another issue about the Show Details page ...

**Comment by ericberman** [comment]
I'm super reluctant to move the drop menu to the left; it's on the right all over the place, and the convention on the web and on apps (I can send numerous examples) seems to be that the context menu/(hamburger menu)[https://www.computerhope.com/jargon/h/hamburger-menu.htm] is on the right (in left-to-right languages like English).  E.g., look at where Chrome or Firefox stuck the menu, lots of other examples.  And when I do issue #382, the checkboxes will likely go on the left (following other "is selected" examples like our very own github. 

Integrating with the date is an interesting idea, but it would double the page weight from the menus (since it needs to be twice on each line), and removing the drop-arrow indicator is, I think, not an option, since it's your visual clue that "hey, you can do more."
