### ISSUE TITLE
Details page minor suggestions 

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#401]
The  Show Details page could be cleaner and easier to use.  Here's a proposed new format:
<img width="741" alt="Screen Shot 2019-11-05 at 1 22 17 PM" src="https://user-images.githubusercontent.com/16978320/68243272-5e7bde00-ffcf-11e9-80e2-ebc836521b14.png">

The data displayed in the first line of the details is the same as the data in the gray bar.  That's redundant and a waste of space.   Just display the same info you do in the Logbook, with navigation (next/previous) buttons to the left (reducing eye scan), and a hover-over down arrow for operating on the flight.

Currently, the buttons FLIGHT (perhaps better labeled "DETAILS") and AIRCRAFT button make the flight or aircraft information appear or disappear (and the option selected turns gray).     But there is no button to control display of a map with the airport(s) visited or, if present, the flight path.  Seems there should be a MAP / TELEMETRY button to control display of either the map or telemetry.  As a nice tip, the third button could change from MAP to TELEMETRY depending on what's present for the flight.

I'm not sure why selecting one option turns off the display of the other.  Seems it is reasonable to want to display all three types of info.

**Comment by KayRJay** [comment]
After further exploration ... 

I see that for some flights, I get different buttons:

<img width="606" alt="Screen Shot 2019-11-05 at 1 41 01 PM" src="https://user-images.githubusercontent.com/16978320/68244427-0c888780-ffd2-11e9-9aef-77ff64fc093f.png">

So, you are already changing the button text when telemetry is present.  Doh!

So, there could be a button MAP in addition to DETAILS and AIRCRAFT when telemetry is NOT present.

**Comment by ericberman** [comment]
Good suggestion about the redundant info, but the reason that the map is omnipresent is that it interacts with both the chart and raw data.  You can click a data point in either the chart or the raw data to see it on the map.  If the map were a mutually exclusive button, you couldn't do that.  I also wanted the map to be on the main details page since it seems like a kinda important piece of detail to see at a glance where you actually flew; I just separated it out of the main top section so that it could interact with the chart and the raw data.

**Comment by ericberman** [comment]
BTW, the redundant info (date/aircraft/route/comments) would need to stay in the upper bar, rather than in the "flight" section.  Otherwise, if you have only one flight, that whole upper bar would be empty, which is rather odd.  Plus, it provides context: e.g., if you switch to chart or raw data or such you can still tell which flight you're looking at.

**Comment by KayRJay** [comment]
Ok, fair enough.   Do you have comments on the general formatting comments?

**Comment by ericberman** [comment]
gotta play with it a bit and see what issues, if any, I bump into.  But it seems that the main ones are:
 * Eliminate the redundancy, which might (or might not) mean a slight layout adjustment in the content area; need to see how it looks.
 * put the next/previous buttons next to each other instead of at left/right of header bar
 * consider changing "Flight" to "Details"
 * I'm a little leery about putting the menu at the left since it's at the right everywhere else in the system (I know you suggested moving it left in the logbook list itself, but I'm not comfortable with that).  But moving it into the header area may make sense.

Am I missing anything?

**Comment by ericberman** [comment]
I'm going to leave "Flight" as just "Flight."  "Details" is (ironically?) too vague (details of what?) and "Flight Details" is too long (it actually causes the button to wrap, and aesthetically I don't think varying width buttons work, and wider buttons don't fit.)  Plus, it's accurate: that tab shows the information about the flight.

First two bullets above are coded up (not yet checked in).  And moving the drop-down to the right of the expand/collapse buttons seems to work (rather than in the header), so I think I'm going to go with that.

**Comment by ericberman** [comment]
I may also consider putting the times above the route block.  (Note that the route block disappears if there is no route).
