### ISSUE TITLE
Flight Time or Hours?

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#402]
In my Cirrus, I have a HOBBS meter and a FLIGHT meter.   MyFlightBook allows me to enter the Hobbs start and end as well as the date/time of Engine start and stop.  

<img width="561" alt="Screen Shot 2019-11-05 at 2 28 43 PM" src="https://user-images.githubusercontent.com/16978320/68247691-95a2bd00-ffd8-11e9-9a7d-6a0543344035.png">

However, MyFlightBook permits only flight start and end times (UTC) to be entered, not the flight METER:
<img width="712" alt="Screen Shot 2019-11-05 at 2 07 51 PM" src="https://user-images.githubusercontent.com/16978320/68247738-ae12d780-ffd8-11e9-80ba-837cf7086377.png">

Since Hobbs and Flight hours are different, it might be useful (to some pilots) to record both Flight hours and meters.

**Comment by ericberman** [comment]
I've just added two new properties: "Flight Meter Start" and "Flight Meter End".  These are excluded from totals.  I didn't do the work to show elapsed values when both are present for a flight (as I do with hobbs, for example), because it's redundant with the time-based computation done for the intrinsic flight start/end fields.
