### ISSUE TITLE
Show last login date (and time?) when signing in

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#439]
Currently, the date of last sign-in on the website is shown under Password user the Account info under the Profile.  This is inconvenient (navigation: hover, click, click).  It's also inappropriate, as the date of the last login is not associated with changing the password.   

More logically, the date (and time!) of the last login should be shown when the user signs in, without having to navigate to it.  It could be placed immediately under the Welcome message (and the suggestion to support MyFlightBook could be moved somewhere else, like below the MyFlightBook logo?).

Welcome, ken | Sign Out
Last sign-in: 12/31/2019 10:09 am

If you like, after the first page-redraw or other navigation, that Last sign-in information could be replaced with the time the user signed in for the current session:

Welcome, ken | Sign Out
Signed-in since: 1/3/2020 12:09 pm

**Comment by ericberman** [comment]
funny, the only reason I show even this data is because the other day someone asked me how long they had had their account, and I realized that I have some of this data and didn't show it anywhere.

The sign-in information is vaguely interesting and not super accurate (e.g., if you sign in via the mobile apps, that bypasses this), but it generally does cover web site usage at least.

I put it in account information because, well, I figured that's where you'd go if you wanted that sort of arcana.  

So my two questions would be:
a) Is this important enough information to be above the fold on every page on the site?
a) where would this go?  Your suggestion above would mean pushing everything down a bit:
![image](https://user-images.githubusercontent.com/16455286/71770475-ae98f300-2ee1-11ea-95bd-074b4d315208.png)
Could put it to the left/right, but I think that gets really cluttered.

**Comment by KayRJay** [comment]
Well, this is a great example of you adding features based on user input.  

To answer the questions you asked …

1. Not super important.  Just after signing in seems a logical time to display the info.   

2. Reasonable concern re clutter.  The info could disappear after the first page refresh or navigation.

3. Other websites (like some banks) do display this info on signing in.  Reminds the user of his activity and might alert him to a bogus or unexpected login.

**Comment by ericberman** [comment]
Often for non-critical information like this I'll put it behind a hover tooltip.  So there, but not distracting or cluttering...

**Comment by KayRJay** [comment]
Another good alternative.

**Comment by KayRJay** [comment]
Don't know where the pop-up is.   My own name (Welcome, Ken) would be a great place.   No additional pixels required.   Can include time of last (i.e., previous) sign-in and could change to time of current sign-in on first navigation or page refresh.   

Is this also going to be on the mobile app?

You said "put sign-**out**" under a pop-up.  Where?  Why?

Also, another idea ... under my profile, display the number of logins I've had.  Or, add this to Achievements.

**Comment by ericberman** [comment]
I haven't taken it out to the live site yet.  Maybe later today, maybe tomorrow.  working on some other issues as well, I'd rather take out one big update than piecemeal.
I don't count logons, so I can't display that.  Kinda of a meaningless number anyhow.
The whole "Welcome, Ken" becomes the pop-up.  You see this model in lot of websites, with "Sign Out" moved into the pop-up.  (E.g., see Amazon)  Actually cleans up the page nicely.
This won't be on the mobile app; the mobile app doesn't have the same notion of a constant header.

**Comment by KayRJay** [comment]
Sounds great, though you might leave Sign-out separate, as some folks may not think to hover over their name. 

Thanks.

**Comment by KayRJay** [comment]
I just signed in twice (sign-out, then back in) and the text says my last sign-in was yesterday.

Also, do you have ability to put the time there?  If I sign in and out multiple times/day, it would be additionally helpful.

Curious: why does a mobile sign-in not get reflected in the date (and time) of last sign-in?

**Comment by ericberman** [comment]
Your account is still cached for about 30 minutes; signing in or out doesn't affect the cache on the server.  So when you sign out and sign right back in, I don't hit the database to reload all of your stuff.

Time gets into time zone issues.  I could do UTC, some people have a default time zone, but it also makes the display a lot longer to grock.  But time (or heck, even the date of the last sign-in) is helpful...at solving what problem exactly?  I threw this on to the site last week because I had it and thought it was a vaguely interesting curiousity, but I can't think of a single scenario where you really need it.  I have used it as a support person only a few times in the last 14 years, and then only to check to see if someone who had needed help with a password reset had ultimately been able to get in.

I don't do this on the mobile apps because (a) they don't have access to the information (at least not from the server; they could, I suppose, record it locally, (b) they stay signed in, and (c) again, it's absolutely never ever come up as something important.  Literally nobody has ever asked for it!  Even this whole thread only came up *after* I had already thrown it up in the account section of the website.

**Comment by KayRJay** [comment]
Inline ...

> On Jan 5, 2020, at 11:09 AM, Eric Berman <notifications@github.com> wrote:
> 
> Your account is still cached for about 30 minutes; signing in or out doesn't affect the cache on the server. So when you sign out and sign right back in, I don't hit the database to reload all of your stuff.
> 
Ok.  Makes sense.  Seemed odd, and will be a little odder if I login after 30 minutes.   No biggie.
> Time gets into time zone issues. I could do UTC, some people have a default time zone, but it also makes the display a lot longer to grock.
> 
OK.
> But time (or heck, even the date of the last sign-in) is helpful...at solving what problem exactly? I threw this on to the site last week because I had it and thought it was a vaguely interesting curiousity, but I can't think of a single scenario where you really need it.
> 
As I mentioned, some sites do this as a security enhancement, to notify the user that someone else may have been tampering with their account.  Of course I realize this isn’t a big issue for MyflightBook.
> I have used it as a support person only a few times in the last 14 years, and then only to check to see if someone who had needed help with a password reset had ultimately been able to get in.
> 
Reasonable.
> I don't do this on the mobile apps because (a) they don't have access to the information (at least not from the server; they could, I suppose, record it locally, (b) they stay signed in, and (c) again, it's absolutely never ever come up as something important.
> 
Never said it was important.  Just curious.
> Literally nobody has ever asked for it! Even this whole thread only came up after I had already thrown it up in the account section of the website.
> 
Right, and thank you for putting it where it “belongs”.  Sorry if that raised a bunch of issues you’d rather not have come up!

**Comment by ericberman** [comment]
No worries! :)
