### ISSUE TITLE
Improve password changing

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#440]
Currently you can only change your password if you know your current password.  Consider these improvements, which are common on many websites:

- Record a password hint, display the hint on request
- Button (eye?) to display current password if signed-in (useful if browser remembers password)
- Password recovery options if user enters account email address and both first and last names
   - send a link (expiring in 30 minutes) to a page that does not require the current password; or
   - send the existing password; or
   - send a code/token that must be entered in lieu of the current password
- Support (3?) user-entered security questions and answers to recover the password

Implement password strength requirements (with a tip to display the requirements):

- Minimum length (8 characters?)
- Different from the email address
- At least three of these: upper case, lower case, numbers, symbols
- Prohibit any "illegal" characters such as "<"
- Different from current (or recent past few) password(s)
- Not common words like "password" or "12345678"
- Not repeated numbers or letters ("aaaaaaaaa" or "11111111")

**Comment by ericberman** [comment]
You can change your password without knowing your current password by doing a reset; that displays the hint in the process.  And you can, of course, always see your hint while signed in.

The eye button to display password is reasonable.

Email+first+last name is not secure - can easily be guessed (e.g., I bet your CFI could guess that).  And sending passwords via email is inherently insecure (though I do have that as a last resort when people  contact me and can't remember their secret question).  

But the current password reset process actually essentially already mirrors your suggestion here: I send a link to your email, thus proving that you are able to receive email at that address.  The link is also like your proposed code/token, except that you can just click it instead of typing it in.  When you click that, you must answer the security question, thus also proving your identity.  

Sending a code/token via a 2nd factor (e.g., text message, as many websites do) would be awesome, and I'd like to do it, but there are two barriers to doing so: (a) I don't have a phone number for anybody currently (and I'm leery about requiring entry of it), but more importantly (b) I'm not aware of any cheap/free services that do this.

I've seen some sites that require 3 questions/answers.  I personally hate that (especially when they constrain the questions/answers - heck *I* often can't answer them reliably!), but mostly I don't know what that solves over one q&a - do you have to answer all 3 correctly to reset your password?  If not, then it doesn't really add any security, and if you do then you've just greatly increased the odds of a failure to correctly answer, making a password reset *more* difficult.  

Note that matching on an answer requires a perfect case-and-space sensitive match, and I can't relax that requirement (also for security): I don't store the answer to your question in clear text; that way, if (heaven forbid) the database were to be compromised, your secret answers are safe.  They're not encrypted, they're salted and hashed - i.e., it's by definition a one-way process that can't be reversed.  When you type your answer, I perform the salt/hash operation on what you type and compare it to what's in the database.

For password strength - I do have a minimum length (6 or 8, I would have to check), and it does (at least on the web) display an indication of strength.  Beyond that, I'm pretty reluctant to overconstrain what you can and can't use for passwords (other than I need to prohibit characters like "<"; see issue #307).

**Comment by KayRJay** [comment]
> On Jan 3, 2020, at 2:17 PM, Eric Berman <notifications@github.com> wrote:
> 
> You can change your password without knowing your current password by doing a reset; that displays the hint in the process. And you can, of course, always see your hint while signed in.
> 

How do you do a “reset”?  How is the hint specified?  Didn’t see that anywhere.  Probably should be under the Password portion of the Profile.
> The eye button to display password is reasonable.
> 
> Email+first+last name is not secure - can easily be guessed (e.g., I bet your CFI could guess that). And sending passwords via email is inherently insecure (though I do have that as a last resort when people contact me and can't remember their secret question).
> 
> 
Of course agreed, but by proving I can login under the email, that’s not a problem.
> But the current password reset process actually essentially already mirrors your suggestion here: I send a link to your email, thus proving that you are able to receive email at that address. The link is also like your proposed code/token, except that you can just click it instead of typing it in. When you click that, you must answer the security question, thus also proving your identity.
> 
I didn’t see how to start the process without entering the current password.
> Sending a code/token via a 2nd factor (e.g., text message, as many websites do) would be awesome, and I'd like to do it, but there are two barriers to doing so: (a) I don't have a phone number for anybody currently (and I'm leery about requiring entry of it), but more importantly (b) I'm not aware of any cheap/free services that do this.
> 
> 
Sending via email works.
> I've seen some sites that require 3 questions/answers. I personally hate that (especially when they constrain the questions/answers - heck I often can't answer them reliably!), but mostly I don't know what that solves over one q&a - do you have to answer all 3 correctly to reset your password? If not, then it doesn't really add any security, and if you do then you've just greatly increased the odds of a failure to correctly answer, making a password reset more difficult.
> 
> 
Agree the questions and answers should be user-specified.    Usually answering all the questions is required, and reduces the possibility of guessing.   

Different people prefer different ways to change or recover their password.
> Note that matching on an answer requires a perfect case-and-space sensitive match, and I can't relax that requirement (also for security): I don't store the answer to your question in clear text; that way, if (heaven forbid) the database were to be compromised, your secret answers are safe. They're not encrypted, they're salted and hashed - i.e., it's by definition a one-way process that can't be reversed. When you type your answer, I perform the salt/hash operation on what you type and compare it to what's in the database.
> 
> 
Agree …perfect  case-and-space matching is required.  The implementation approach you mention is correct.
> For password strength - I do have a minimum length (6 or 8, I would have to check), and it does (at least on the web) display an indication of strength. Beyond that, I'm pretty reluctant to overconstrain what you can and can't use for passwords (other than I need to prohibit characters like "<"; see issue #307 <https://github.com/ericberman/MyFlightbookWeb/issues/307>).
> 
> 
Well, that’s up to you, but I don’t see much downside in encouraging (“forcing”?) users to use better passwords.  Just a little coding on your part.   Naturally, you wouldn’t invalidate existing passwords.

**Comment by ericberman** [comment]
> How do you do a “reset”? How is the hint specified? Didn’t see that anywhere. Probably should be under the Password portion of the Profile.
When you go to sign in, there’s a “Forgot password” link.  “hint” was the wrong word; you answer your security question as part of the process.  Hints are inherently insecure because (especially if poorly selected) can dramatically narrow the possible password space for a hacker; they’re also inherently redundant with the security Q&A.


> Email+first+last name is not secure - can easily be guessed (e.g., I bet your CFI could guess that).
> Of course agreed, but by proving I can login under the email, that’s not a problem.

Logging in under an email says nothing about your ability to receive email at that address.  In fact, it’s perfectly OK if your email changes and you no longer have access to the old email to sign in with the old email.  (Although it certainly gets harder if you forgot your password).  *receiving* email at the address is what makes for a sort of 2-factor authentication.

>I didn’t see how to start the process without entering the current password.

See attached.  Kinda by definition, if you’re in Profile->Account, you’ve already signed in so don’t need a reset; it’s when you’re *trying* to sign in that you need a workaround.  The system requires you to type your password again as an extra layer of security (e.g., your kid didn’t just wander by your computer and decide to mischievously change your password.  (Actually not my choice – the system requires the password to change the password, and since I don’t have a clear text password stored anywhere, I need you, the user, to type it in.)

**Comment by ericberman** [comment]
![password](https://user-images.githubusercontent.com/16455286/71757831-ddfe2000-2e4d-11ea-8505-863f556e80f8.png)

**Comment by KayRJay** [comment]
Inline

> On Jan 3, 2020, at 6:24 PM, Eric Berman <notifications@github.com> wrote:
> 
> > How do you do a “reset”? How is the hint specified? Didn’t see that anywhere. Probably should be under the Password portion of the Profile. 
> When you go to sign in, there’s a “Forgot password” link. “hint” was the wrong word; you answer your security question as part of the process.

Aha, that’s why I didn’t see it.  However, this is only available if I click Forgot Password.   Seems the process of changing the password, if logged in, should be under Profile > Account > Password.

> Hints are inherently insecure because (especially if poorly selected) can dramatically narrow the possible password space for a hacker; 

Hints, if user-defined, are only as insecure as the user’s choice of the hint.   Same with the actual password chosen, especially if you don’t enforce any password strength rules.

> they’re also inherently redundant with the security Q&A. 

Like I said, people have different ways they like to be reminded.
> 
> > Email+first+last name is not secure - can easily be guessed (e.g., I bet your CFI could guess that). 
> > Of course agreed, but by proving I can login under the email, that’s not a problem. 
> 
> Logging in under an email says nothing about your ability to receive email at that address.

However since (a) I’d be logged in when requesting the password recovery, and (b) you would be sending the correction link, code/token or actual password TO the email, it’s certain that only a person who can log into that email address can see it and use it.

> In fact, it’s perfectly OK if your email changes and you no longer have access to the old email to sign in with the old email. (Although it certainly gets harder if you forgot your password). *receiving* email at the address is what makes for a sort of 2-factor authentication. 

Yes, it is important to be able to receive the info.  And, some systems provide a way to change the email if you no longer have access.
> 
> >I didn’t see how to start the process without entering the current password. 
> 
> See attached. Kinda by definition, if you’re in Profile->Account, you’ve already signed in so don’t need a reset;

Not so.  I might want to change my password because it is old (and you do tell me how old it is).

> it’s when you’re *trying* to sign in that you need a workaround.

Or not …. may want to change it as a matter of policy.

> The system requires you to type your password again as an extra layer of security (e.g., your kid didn’t just wander by your computer and decide to mischievously change your password. (Actually not my choice – the system requires the password to change the password, and since I don’t have a clear text password stored anywhere, I need you, the user, to type it in.) 

I think this whole area needs to be re-thought, to be like other websites.   My browser (Safari) remembers my password.  So I may not “know” it to change it.  Sure, I can find out from the Safari Preferences, but that’s a pain.

f you have the “eye” icon to show me the password, it’s not really important to be able to enter the old password.

**Comment by ericberman** [comment]
Let me step back here and try to summarize what I think are the use cases, since there are a lot of issues getting conflated here.  (Perhaps some of these should be factored out into separate issues).

Use case 1: I'm trying to sign-in and don't remember my password.  I don't think we have any disagreements here.  This is by definition at the point where you are signing in.  There's a "I forgot my password" link - as there is on every website - and clicking it initiates a reset process.  Two factor auth would be great, but I'm not willing to pay for a service and it's not strictly necessary.  The current approach requires that you be able to receive email at the requested email address (a poor-man's 2-factor auth), to which a link is sent that initiates the reset process.  No password is sent in email.  This process is consistent with many other sites, and is reasonably secure.  The only two failure modes, really, are if you no longer can receive email at that address, or if you don't remember your secret question answer.  Both of these can be addressed with Use case 1A.
 * Use case 1A: Password reset fails.  Contact me and I have an admin button that can reset a password and email it to you.  Because this sends a password in the clear in email, it's not preferred, but is acceptable as a backup.

Use case 2: I want to change my password.  I think I'm completely consistent with other sites here.  E.g., I just checked on Chase.com and Amazon, and they both match what I have, to the T; see below.  They each have three boxes: (empty) box for current password, a box to type a password, and a box to re-type my password.  There's no link on this section of either of these websites to reset your password (or to add an extra hint) because - by definition - to get here you had to sign.  In your comment above you said "Seems the process of changing the password, if logged in, should be under Profile > Account > Password".  I agree with this comment, and that's how this works today, so I'm confused what should change here (you might be referring to use case #2A below?)
![image](https://user-images.githubusercontent.com/16455286/71769984-4dbaec00-2edc-11ea-8917-d6317d5ab01c.png)

 * Use case 2A(1) - I want to change my password and I'm signed in but I've forgotten my current password.  This is not really different from Use Case #1.  You can simply sign out and then click "I forgot my password."  While some sites may explicitly handle 2A distinctly from 1, enough do not that I wouldn't consider it standard practice.  
 * Use case 2A(2) - same as 2A(1) but - as you say above "My browser (Safari) remembers my password.  So I may not “know” it to change it."  This is actually easier than 2A(1): Safari remembers it, so let it fill in the "Current password" field for you.

Use case 3 - I want to change my email address.  You comment "some systems provide a way to change the email if you no longer have access."  I do as well.  Profile->Account->Name/Email.  Note again that there is a distinction between the use of an email address as an identifier, and the use of an email address for communication, so allow me to enumerate a few sub-scenarios here:
 * 3A - I'm changing my preferred email from one active address to another.  Easy: sign in to MyFlightbook using me@oldaddress.com, go to Profile->Account->Name/Email, change to me@newaddress.com.  Done.
 * 3B - I've changed jobs and no longer have access to email me@oldaddress.com, but I do remember my password.  Still easy: it's the exact same process as above.  Here "me@oldaddress.com" is just an identifier; the fact that I can't receive communication at that address any more is not relevant.
 * 3C - I've changed jobs, no longer have access to email me@oldaddress.com, and I don't remember my password.  Here I'm indeed stuck (as is the case, by the way, with lots of other websites).  This now becomes scenario 1A above to get a new password, and with that new password, I can now follow scenario 3B to change the email and scenario 1 to change the password.

Above largely matches all sorts of websites (particularly those that use email as a username, as I do).  I'm not sure where I'm following uncommon practices, or what scenarios I'm not serving - i.e., what problem am I trying to solve by reworking the flow around this stuff?

There are 5 other suggestions I see above:
 * Password illegal characters.  Issue #307 covers illegal characters, so should be tracked there.
 * Password strength: I already give feedback on strength on strength - in real time - as you type.  
![password](https://user-images.githubusercontent.com/16455286/71769803-64f8da00-2eda-11ea-8360-787bab8216ea.png).  Philosophically, my preference here is to encourage, but not mandate, strength.  (Indeed, I've seen a lot of arguments that 4 random words are more secure than requiring a mix of upper/lower case, punctuation, etc.).  So my inclination here is to encourage strong but allow flexibility.
 * 3 questions vs. 1.  Coming up with a good question is actually pretty hard; coming up with 3 is much harder - much higher chance that at least one will be weak.  Yes, some sites (United Airlines) do this (and I personally can't stand it).  But there's another challenge to 3 questions: more friction to account creation.  I want that process to be easy, so there's a balance here.
 * Password hint.  This is indeed distinct - but overlapping - with the Q&A.  I actually don't see many sites doing this, though there are a few.  The overlap with Q&A is primarily that, like a Q&A, coming up with a good hint that isn't insecure is hard, and requiring it adds friction to the sign-up process.  So between that and the fact that so many browsers or password managers remember passwords for you, I don't think the bang-for-the-buck in implementing it is there.
 * Finally the "eye" to show a password.  I think this is indeed an interesting idea.  There are a few issues with it (see [this](https://kyusuf.com/post/password-visibility-toggles/) for example) to ensure security, but I'm not opposed to it.  Main issue for me to figure out is how to avoid conflicting interactions with built-in "eye" support (e.g., Edge) or auto-fill.  I.e., I agree with the author's assertion that the value of the eye is *NOT* to remind you of your password - it's a security hole to ever be able to expose this! - but rather it is to enable you to double-check that what you typed matches what you think you typed.

**Comment by ericberman** [comment]
A couple of notes-to-self on password eye:
 * only show the "eye" after a keystroke that changes the field's text.  This ensures you can't just see an auto-filled password.
 * disable on Edge?

**Comment by ericberman** [comment]
So I just spent an hour or so coding up the reveal-password-eye thing, and it works great, but I'm not going to release it.  I changed my mind about whether it's a good idea: sites like Firefox can autofill the password for you, and then the eye lets you view the password.  This worries the crap out of me - if someone gets access to your computer, they can go to the sign-in page and grab your password.  Even Edge's built-in expose-password eye suffers from this - crazy.

The purpose of the eye is supposed to be when you are typing to verify that you didn't fat-finger the password.  I'm OK with it from that perspective, but in that case you're starting from an empty field.  Autofill happens in the browser after the page is loaded and thus looks like user typing (it triggers the same events).  LOTS of people use autofill, so this would expose them.  So I'm not comfortable releasing that.

Password strength - I am now requiring minimum 8 characters (had been 6), but I am NOT requiring upper/lower case or symbols.  More research I do suggests that actually doesn't help (see issue #307 for some links, including a great XKCD comic).  Seems that length - by far - is the most valuable thing you can do in a password.

I did, however, improve the aesthetics of the password strength indicator (in the yellow above; now a text-less color-coded bar) and some of the attributes - it targets 10 character minimum. 

I'm not seeing any problem to fix with the password reset process, password change process, or email change process, so I am not making any changes there.
