### ISSUE TITLE
Fix progress toward ratings for Private Pilot and Instrument Rating

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#442]

**Comment by ericberman** [comment]
What's broken about it?

**Comment by KayRJay** [comment]
I somehow committed the issue before finishing the description ... sorry.

Currently, under Training > Ratings Progress, the user can select the type of rating sought and a specific regulatory type.   These seem inconsistent or incomplete (though I am clearly not an expert in all this, and more than likely you have it entirely correct!).  
- Should there not be a rating type for CFIs (or perhaps more than one type of CFI)?
- The regulatory types for Instrument rating types are a subset of those for Private Pilot, and don't include Canada or other locales, and they might be missing for other rating types.  
- Is it correct to have EASA LPL ratings as a top-level choice, and also a choice under Private Pilot?

I'm just not sure if the regulatory type subsets are correct for all rating types.  Might be worth a review.

**Comment by ericberman** [comment]
Reasonable question whether each of these ratings should correspond 1:1 with others, but they just...don't.

For CFI's: there isn't a meaningful level of flight experience required here.  See https://www.law.cornell.edu/cfr/text/14/61.183; the only logbook experience requirement is 15 hour PIC requirement in category/class/type; the rest is all "receive an endorsement" and "hold a certificate" stuff, so there's really no notion of "how am I doing towards being ready to take my CFI checkride."

For Instrument Ratings - indeed, I've only done US.  As people request different jurisdictions, I add them.  But there are also fewer paths to an instrument rating than there are for private pilots (e.g., no notion of part 61 vs. part 141), and the instrument rating is held at the category level, not category class (e.g., for PPL, an Airplane Single Engine Land rating is distinct from an Airplane Multi Engine Land rating, but in instrument you just get an instrument rating for "Airplane").  And many other jurisdictions are so similar (or identical) to US that it hasn't been necessary to do distinct progress reports.

And yes, an EASA LAPL rating is distinct from an EASA private pilot rating.  It's more analogous to the US Sport or Recreational rating.

So I think the only thing here is whether there are other jurisdictions for which I should add ratings progress.  Undoubtedly yes, but since each one can be a bit of work to construct, and since I'm hitting diminishing returns, I'll continue to wait for a specific request before building it.
