### ISSUE TITLE
Provide usage data about MyFlightBook itself

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#445]
MyFlightBook's home page includes the count of recorded flights in the past week:
     2,653 pilots have recorded 9,596 flights over the past 7 days!

This info is only displayed after sign-in.  However, it's a nice tidbit as an "advertising" talking point.  Probably no reason to limit it to signed-in users.

Additionally, for signed-in users who might be curious, you could provide more information:

- Number of registered users/aircraft/airports
- Number of flights recorded
- Number of currently signed-in users
- Number of sign-ins in the last 7 days
- (probably others ...)

Because there is a performance hit, this info could be hidden under a pop-up if you like ... perhaps the MyFlightBook logo?

**Comment by ericberman** [comment]
A "local" flight on MyFlightbook can be at any airport; it just means you didn't leave the pattern.  The genesis of that was 61.1's definition of a "cross-country" flight.  See my [blog post](https://myflightbookblog.blogspot.com/2018/08/logging-cross-country-time.html) for gory background here.  

There is no connection to a "home" airport (and indeed, the very notion of a "home airport" doesn't have meaning for a lot of pilots - think commercial or military pilots; "home airport" is primarily a GA thing.)

**Comment by ericberman** [comment]
BTW, I'm not sure the connection between the suggestion here and the title?

**Comment by KayRJay** [comment]
Again, entered the info (by pressing commit) before ready to submit.   Sending the form via Enter is dangerous.

**Comment by KayRJay** [comment]
To continue on this issue ... some other ideas about MyFlightBook

- The MyFlightBook"version" (if any) and the date/time the system was last updated
- Number of airports visited
  - or add it as "2,653 pilots have recorded 9,596 flights visiting xxxx airports over the past 7 days"
- Others of less interest (or of interest only to you)
  - Database size
  - Number of flights with images or telemetry

Also, re the performance hit, the pop-up could list the above "queries" and execute them only when any of them is clicked.

**Comment by ericberman** [comment]
I'm actually a little sensitive about sharing # of users in a live manner (for competitive reasons), but otherwise I already track some of these and am happy to share.

I've just brought out stats on the home page for # of flights, aircraft, and models (the most important ones), as well as number of active users as measured by session start/session end (a poor proxy, and it completely excludes mobile usage which is a huge deal).  

But I backed out the change because the database started timing out left and right; I'm not sure why - these queries aren't THAT expensive.

# of airports is a painstaking computation, I'm not going to do that.  Flights is more important.

Database size & Number of flights with images or telemetry is indeed interesting to me, but I don't think it is to others.  The value of seeing # of flights/aircraft/models is it's a selling point, it validates that I'm not a fly-by-night logbook.

Still investigating why my change broke so badly; it works fine on my local machine...then I can take it back live.

**Comment by KayRJay** [comment]
I somewhat understand the competitive concern regarding the number of registered users.  But is the user count really more sensitive than the other numbers you're showing?  Are you concerned that your user count is low compared to other (free) sites?   Seems not likely, given the number of recorded flights during the life of MyFlightBook. 

CrewLounge PILOTLOG says it is "used by tens of thousands of ... pilots".  It would be interesting to know how many users there are on other sites, though.   The competition might be good for everyone!

If you're not concerned about the competitive value of the other data, then why not provide all the information on the home page before a user signs-in?  Displaying the info after sign-in doesn't really hide it much because it is easy to create an account.   I agree that this information is a nice selling point and should probably be visible even (or perhaps especially?) to people who've not yet created an account.  

Putting this info below the image of a flight makes it a little hard to see/find/run across.  It probably should be closer to the initial text "Recent flights taken by members of the MyFlightBook community."  Many pages in MyFlightBook have lists or other info that vertically fills the screen.  I am rarely inclined to scroll down to the bottom of a page, and generally don't.   Moving this data to the pre-sign in page also increases the visibility of the footer.

(This also means I don't see the ad(s) you host.  Are you missing a revenue opportunity because of that placement?  Couldn't the ad be displayed before the user logs in?)

I guess  you didn't want to publish a version number because it's probably not interesting most of the time.   However, it does show continued development.  You could even advertise the open-source nature of MyFlightBook, the number of user-requested features you've implemented, etc.

By the way, I clicked on the dots below the pictures.  They seem to do the same thing as the arrows at the sides in the pictures.   How do you decide which images to post?   Do they include random pictures of aircraft?   I assume the text below the flight is the user's comment when the image was uploaded.   If the user has published a flight associated with an image, it might be nice to also show the date the picture was taken  (and possibly the aircraft type or tail number?) along with the location and pilot's name.

I accidentally checked on a picture, and it blew up to full screen.   The ESC key didn't close the image.  Perhaps you should have a ⊗ in the upper right corner of the image?

**Comment by ericberman** [comment]
The # of registered users is something competitors could monitor.  I far prefer a rough number ('tens of thousands").  I tell people all the time, but in 1:1 ad-hoc situations.  The # of flights and such are all large enough numbers in any absolute sense that I'm comfortable sharing.

It all does display on home page, either before or after you log in.  No issues there.

As for placement - now we get to the issue of everything on the page competes for the user's attention; what's most important.  I like the "2,311 pilots have recorded 7,352 flights over the past 7 days!" line because it's simple, easy to understand, and shows momentum and activity (i.e., it's not a dormant site!) with the product.  The # of flights/aircraft/models, etc., is more static - it could be 3 years out of date.  So I think for that reason alone it's less compelling.  And pictures - that change every time - are also compelling.  And the big feature tiles at the top are a call to action for a new visitor and help explain the site (whereas returning users don't typically spend much time on this page).  So I put it below the pictures, which is, I think, appropriately reflects the priority relative to the other items on the page.

I don't publish a version number not because it's not interesting but rather because it simply doesn't exist.  There's simply no concept of it, which makes it a bit hard to display <g>

Pictures: it's sorta random.  I have a list of about 300 or so recent flights that people have flagged as being publicly visible.  I go through them looking for 10 flights with images, taking the first image.  I pad out with aircraft images if I can't find 10 flight images.  So yeah, it's pseudo-random what you'll get.  Yes, the comments are the comment associated with the image.

Clicking an image opens it in a new tab; that's why escape doesn't do anything.  You do have an ⊗ - it's on the browser tab.  All images everywhere in the system work that way - clicking them opens the full-resolution image in another tab.  That way you can zoom/pan using your browser, you can drag/drop the image to save it to your desktop, share the URL to Facebook, etc.  Been that way since the start.  I could potentially be persuaded (separate github issue!) that they should open up in-line with escape to dismiss, as that does seem to be a common thing on the web.  But would need to verify that you can still do drag/drop, can still do pan, can still easily get the URL, etc.

**Comment by ericberman** [comment]
Oh - and one more thing on the version: that's why I have the FB feed there.  That's where I announce new features, discussions of aviation logbook topics, and you can see other activity there.

**Comment by ericberman** [comment]
Oh - and you asked about the dots.  Yeah, that comes with the "bxslider" tool that I use for the slideshow of images.  Think of it as random access vs. sequential.  You can click the arrows on the left/right of an image to go next/previous, or you can click the n'th dot to go directly to the n'th image.

**Comment by KayRJay** [comment]
> On Jan 5, 2020, at 3:47 PM, Eric Berman <notifications@github.com> wrote:
> It all does display on home page, either before or after you log in. No issues there.
> 
I don’t see it on the home page before I sign-in because I bookmarked the sign-in page: https://myflightbook.com/logbook/Secure/login.aspx <https://myflightbook.com/logbook/Secure/login.aspx>
> As for placement -
> 
Reasonable.   Though I do wonder how often people see the ads or when they typically discover the footer in common experience.
> I don't publish a version number not because it's not interesting but rather because it simply doesn't exist. There's simply no concept of it, which makes it a bit hard to display
> 
Well, there is the date you last committed a change.  But I can get that from Githiub if I’m desperately interested.
> Pictures: it's sorta random. I have a list of about 300 or so recent flights that people have flagged as being publicly visible. I go through them looking for 10 flights with images, taking the first image. I pad out with aircraft images if I can't find 10 flight images. So yeah, it's pseudo-random what you'll get. Yes, the comments are the comment associated with the image.
> 
Not worth putting the other public info next to the comment?
> Clicking an image opens it in a new tab; that's why escape doesn't do anything. You do have an ⊗ - it's on the browser tab.
> 
Almost every site I’ve ever seen that displays images this way does it in a a pop-up, so that’s why it didn’t work as expected.  There is a downside to using a new tab … when I use the browser ⊗, it doesn’t return me to the tab with MyFlightBook open, but to some other tab.  Then I have to re-select the proper tab.   This happens because I have a browser pin for the MyFlightBook sign-in page, so closing the tab with the image takes me to the first open tab, not to the page I came from.
> 
> All images everywhere in the system work that way - clicking them opens the full-resolution image in another tab. That way you can zoom/pan using your browser, you can drag/drop the image to save it to your desktop, share the URL to Facebook, etc. Been that way since the start.
> 
I like that it’s full-resolution.  Good benefits.
> I could potentially be persuaded (separate github issue!) that they should open up in-line with escape to dismiss, as that does seem to be a common thing on the web. But would need to verify that you can still do drag/drop, can still do pan, can still easily get the URL, etc.
> 
> 
Right.  Will you create the Github issue?

**Comment by KayRJay** [comment]
> Oh - and one more thing on the version: that's why I have the FB feed there. That's where I announce new features, discussions of aviation logbook topics, and you can see other activity there.

I don't Facebook (much), but I did just Follow on Twitter.  Latest update there was March by the way!

**Comment by ericberman** [comment]
Thanks for letting me know about twitter.  I've had it linked to FB so everything I put on FB would cross-post (I never actually use Twitter directly); that must be broken.
