### ISSUE TITLE
"Achievements" issues -- Navigating to a flight or aircraft and Custom dates

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#446]
Clicking on a date in a medal for "Primary Training" or "Milestones" takes you to the proper flight (for review or editing).  And when there is a list of several flights for a category of "Flying stats", you can easily get to a given flight.

However, the links for Longest flight and Furthest flight don't provide single-click access.

It would also be nice if the Aircraft flown and Models flown had links to the appropriate info.  (Maybe that's already there.)

By the way, the first item, " Logged xx Flights!" has a leading blank space.

**Comment by ericberman** [comment]
I'm not seeing that.  Longest Flight and Furthest Flight do both link to the matching flight.  There is a difference, though, in that the badges link to flight details whereas the stats flights link to the public flight page (two different views for the same flight.)  I'll fix that.   The ones that go to a specific flight should all go to one or the other (I'll link them to the details).  

Aircraft Flown and Models flown don't have links because I don't know what I'd link to.  What do you suggest?

I'm not seeing the leading blank space in Logged xx flights either; everything looks aligned properly in the image below, and I checked that there isn't an extra space in the text string.
![image](https://user-images.githubusercontent.com/16455286/71773775-3c8fd080-2f18-11ea-8924-1b637cd51b09.png)

**Comment by KayRJay** [comment]
Right, both Longest Flight and Furthest Flight should go to the details.   That was my concern.

I have only one aircraft and one model.  There is no link for either.   Aircraft Flown and Models flown should link to a list of all relevant aircraft or models, or to the **one** I have.

For me, I see this (on Safari/Mac):

<img width="609" alt="Screen Shot 2020-01-04 at 9 17 46 PM" src="https://user-images.githubusercontent.com/16978320/71775082-dd41b880-2f37-11ea-92e2-90370d2923c7.png">

You don't see the extra space?

**Comment by ericberman** [comment]
I don't have any target page for aircraft or models that can show a subset that matches; seems like a lot of work just to make everything have a link.

I can reproduce the space on Safari.  Weird!  Looks like Safari isn't doing whitespace folding that HTML is supposed to do.  The "Logged 80 flights" part is in the 2nd part of the item (that can be linked).  I know how to fix that.

**Comment by KayRJay** [comment]
Isn’t the aircraft just a specific tail number or multiple tail numbers?   That should be a direct link to a specific aircraft or list, no?

Forgot to mention that (at least on Safari), I can’t use the custom date picker more than once without changing to a pre-defined date range first.  Nothing happens on the second try.

**Comment by ericberman** [comment]
Aircraft is multiple tail numbers, models is multiple models.  So I don't have any page currently that says "show this particular set of models" or "show this subset of your aircraft."  I'd have to make a new page for that just to make this clickable, and that falls low enough on the priority list that I'm not going to get to it.

I was hiding the date selection after choosing "Custom", since at that point you've specified your dates, but yeah I agree I should fix that.

**Comment by KayRJay** [comment]
I understand re the priority, of course.

But about needing a new page to show multiple aircraft with specific tail numbers ... Couldn't the [My Aircraftpage](https://myflightbook.com/logbook/Member/Aircraft.aspx), which shows "Frequently used aircraft" do the job?  It would just list those flights within the specified date range.   It already can sort by recency of flight.

And, re not having a page for sets of models, doesn't the [Aircraft models](https://myflightbook.com/logbook/Member/Makes.aspx) page support listing of models?

In both cases, It's just a different query, right?  Or, what am I missing?

**Comment by ericberman** [comment]
correct on both points, but these pages don't know how to do what would be required here:
 * Aircraft ALWAYS displays all aircraft in your account (just organized in different ways), so it would need to (a) be able to accept a list of aircraft passed in somehow and then be reworked to bypass the various places in the code where it just says "give me all of the user's aircraft" to instead go to the subset list that was passed in, and it would need some sort of UI to indicate that "hey, this isn't your regular aircraft page because not all aircraft are shown" and maybe give you a way to show all aircraft, etc.
 * Models only knows how to do a search from a query - it also doesn't have the notion of accepting a list of models, showing those, suppressing the regular search stuff in that scenario, and so forth.

None of this is rocket science, but a lot of niggling little details that will be pulling a thread on a sweater...

**Comment by KayRJay** [comment]
Pardon me for being persistent here, but isn’t the list of aircraft or models that is passed in to another page simply a subquery you pass in to those display pages?   So the “somehow” way to pass a list of aircraft is to pass a SQL query that is used in the FROM clause as the source of the data, as in 

SELECT <stuff> FROM
  (SELECT <stuff> FROM Aircraft WHERE <AchievementsCriteria>)
WHERE Owner = CurrentUser  /* or whatever those criteria are */

You already generated the Achievements query (with COUNT(*)) to show me the number of distinct aircraft used within a range of dates.   So, it’s using that same query without COUNT(*) as the subquery.

The “some sort of UI” is just a change to the blue banner:

             Aircraft flow between dd/mm/yyy and did/mm/yyy

A similar approach could be used for aircraft models.

But even if this is “easy” I can see that it’s probably not a high priority ... but you have implemented other “low priority items! ;-)

**Comment by ericberman** [comment]
Nope.  I don't pass SQL queries around - that's very dangerous.  (Also most of this is not done at the database level, though certainly aircraft/models *could* be).

In the case of the models page: I have higher level "ModelQuery" object (NOT SQL!!!) that I can pass in to the Models page.  The ModelQuery includes things like "Manufacturer name" or "Category class", and the models page knows how to take a modelquery and bind it to the UI, and to create a modelquery object from the UI, and to pass a modelquery down to the lower level code that takes a modelquery and does the DB work (that's a very deliberate layer of abstraction).  But the ModelQuery object doesn't contain a specification of "model ID in (14, 23, 58, 29)" (i.e., the ones that were found in the achievements page), nor does it know anything about your flights (it's completely independent of user) or of a date range (searching for models doesn't have a notion of "dates"), etc.  And if I added any of these things, I'd have to add UI for it to the models page so that it could display it or at least preserve it, or otherwise let you know what you're looking at - i.e., why are *these* models displayed and not *those* models displayed.  With regular search, it can do that because it can show you the UI for the query.

In the case of the aircraft page, it doesn't have any notion of searching at all.  It ALWAYS looks at your aircraft - every one of them.  It is always a comprehensive list.  Sure, it organizes them in different ways, but there is at the moment absolutely no notion of "find aircraft matching criteria x or in the set of (a, b, c)".   And again, there's no notion of dates - your aircraft are "date free" - N12345 doesn't have a date range associated with it.  It pulls the list of your aircraft (cached) in numerous places, and so that whole model would need to be changed to accommodate sometimes using your cached list of aircraft and sometimes using a subset, and the UI changed to show the subset (if you're using a subset).  

None of this is rocket science.  It's all eminently solvable; I never claimed that it couldn't be done, just that the level of work is wildly disproportionate to the consistency issue that some things are clickable while others aren't.

**Comment by KayRJay** [comment]
Interesting ...

> On Jan 5, 2020, at 10:52 AM, Eric Berman <notifications@github.com> wrote:
> 
> Nope. I don't pass SQL queries around - that's very dangerous.
> 

Why is this “dangerous”?  You’re not exposed to SQL injection (where a user constructs the search criteria as text).
> (Also most of this is not done at the database level, though certainly aircraft/models could be).
> 
Until I read the next sentence, I didn't understand how you answer the query without doing it via SQL.
> In the case of the models page: I have higher level "ModelQuery" object (NOT SQL!!!) that I can pass in to the Models page. The ModelQuery includes things like "Manufacturer name" or "Category class", and the models page knows how to take a modelquery and bind it to the UI, and to create a modelquery object from the UI, and to pass a modelquery down to the lower level code that takes a modelquery and does the DB work (that's a very deliberate layer of abstraction).
> 
OK. I get that.
> But the ModelQuery object doesn't contain a specification of "model ID in (14, 23, 58, 29)" (i.e., the ones that were found in the achievements page), nor does it know anything about your flights (it's completely independent of user) or of a date range (searching for models doesn't have a notion of "dates"), etc.
> 
That makes sense.
> And if I added any of these things, I'd have to add UI for it to the models page so that it could display it or at least preserve it, or otherwise let you know what you're looking at - i.e., why are these models displayed and not those models displayed. With regular search, it can do that because it can show you the UI for the query.
> 
I thought just updating the blue banner would be enough.  It could be general (without specific dates): “Aircraft flown in a range of dates”.  But I get your point.
> In the case of the aircraft page, it doesn't have any notion of searching at all. It ALWAYS looks at your aircraft - every one of them. It is always a comprehensive list.
> 
So, there must be a query or AircraftQuery object to find just MY aircraft, not ALL aircraft in the database.  Or, based on the following, I guess not.
> Sure, it organizes them in different ways, but there is at the moment absolutely no notion of "find aircraft matching criteria x or in the set of (a, b, c)". And again, there's no notion of dates - your aircraft are "date free" - N12345 doesn't have a date range associated with it. It pulls the list of your aircraft (cached) in numerous places, and so that whole model would need to be changed to accommodate sometimes using your cached list of aircraft and sometimes using a subset, and the UI changed to show the subset (if you're using a subset).
> 
Ah, that’s the issue.  You’ve somehow earlier retrieved MY aircraft and cached them (in multiple places?).  So, there is no query to execute either by a model or directly with SQL.
> None of this is rocket science. It's all eminently solvable; I never claimed that it couldn't be done, just that the level of work is wildly disproportionate to the consistency issue that some things are clickable while others aren’t.
> 
Sure, but I did say “easy” in quotes, and I said I understood it was low priority.   At least I now have an even better understanding of some of the internal design of MyFlightBook.

**Comment by ericberman** [comment]
There are a few reasons why it's dangerous: The web is stateless, so making these things clickable means preserving all of the "state" (i.e., which flights/aircraft/etc. to show) in the URL.  You do NOT want to pass SQL (even encrypted, which can be broken) in that because it's susceptible to injection attacks, replay attacks, etc.  That's one reason I pass a higher level FlightQuery or ModelQuery object around.  It's also "dangerous" because it's fragile: it makes the high level parts of the site dependent on the low level database schema.  The correct and safe way to do this is to pass intentions ("please do X for me") or data ("here is an aircraft") - NOT tied to the database - back and forth.  The upper layers of the code ideally never see a "SELECT" statement (much less an "UPDATE" or - gasp "DELETE".  

So yes, there absolutely is a query that gives all of the aircraft for you.  But these pages don't have access to that query.  They simply can make a function call to the lower system and say "Please give me Ken's aircraft"; that call checks the cache (there's only one cached copy of Ken's aircraft in the system - it's accessed from a bunch of places, but only stored in one), and hits the database only on a cache miss, and returns the aircraft to the higher layer.  The upper layer never knows whether or not the database was hit.

**Comment by KayRJay** [comment]
> On Jan 5, 2020, at 11:48 AM, Eric Berman <notifications@github.com> wrote:
> There are a few reasons why it's dangerous: The web is stateless, so making these things clickable means preserving all of the "state" (i.e., which flights/aircraft/etc. to show) in the URL.
> 
I think what you’re saying is that you would have to a create a URL containing the generated SQL as a parameter to the pages that would display the aircraft or models.  And that’s dangerous because it would be exposed to the user.   Makes sense.
> You do NOT want to pass SQL (even encrypted, which can be broken) in that because it's susceptible to injection attacks, replay attacks, etc. That's one reason I pass a higher level FlightQuery or ModelQuery object around.
> 
Understood.
> It's also "dangerous" because it's fragile: it makes the high level parts of the site dependent on the low level database schema. The correct and safe way to do this is to pass intentions ("please do X for me") or data ("here is an aircraft") - NOT tied to the database - back and forth. The upper layers of the code ideally never see a "SELECT" statement (much less an "UPDATE" or - gasp "DELETE”.
> 
Good explanation.
> So yes, there absolutely is a query that gives all of the aircraft for you. But these pages don't have access to that query. They simply can make a function call to the lower system and say "Please give me Ken's aircraft"; that call checks the cache (there's only one cached copy of Ken's aircraft in the system - it's accessed from a bunch of places, but only stored in one), and hits the database only on a cache miss, and returns the aircraft to the higher layer. The upper layer never knows whether or not the database was hit.
> 
Got it.  Thanks,.
