### ISSUE TITLE
Cross-post to twitter from Facebook is broken..

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#447]

**Comment by KayRJay** [comment]
The latest post on Facebook seems to be almost a year old, and the truth is that you've done a LOT of new features in that time!    And Twitter seems to have newer posts than Facebook!

**Comment by ericberman** [comment]
Huh?  Facebook has posts as recent as Monday!

**Comment by ericberman** [comment]
The Facebook->Twitter push thing seems to be not working properly.

**Comment by ericberman** [comment]
Sigh, may have to manually post on both now.  Bleah.  I have a friend at FB, maybe he can tell me what's happening.

**Comment by KayRJay** [comment]
I’m not a FB user often, but this is what I see when I look at Posts From Anyone …

**Comment by ericberman** [comment]
![image](https://user-images.githubusercontent.com/16455286/71787569-702d3200-2fce-11ea-8aca-2e49086dec31.png)

**Comment by ericberman** [comment]
Are you possibly on the wrong page?

**Comment by KayRJay** [comment]
Clicked on [Posts on the MyFlightBook page](https://www.facebook.com/search/str/myflightbook/keywords_blended_posts?f=AbqlNKx8CSwBM3DIyI1ZJ2AhnrVtD_FgbyL4u0By5aLmyp0RXfkXUaKBk434vL_kDOwiymR6Rf5iQbIE2geBkFNTVDEIemwuv-Jpmmxcndn9e7ERRSOD0CkY0b336knNGSY&epa=FILTERS)

**Comment by ericberman** [comment]
Latest post there is from Dec 31.  Less than a week old.

**Comment by ericberman** [comment]
Note that it's a filtered view too.  Click "All" to see all.

**Comment by KayRJay** [comment]
I did click All (to the left of the word POSTS).  I see your post of last week:

MyFlightbook
February 20, 2019 · 
Haven't posted in a while because I haven't done any particularly noteworthy new features. But I have been addressing a whole bunch of smaller issues over the past few weeks - as always, you are all the best source of suggestions and ideas for how to improve MyFlightbook!
Please keep the ideas/suggestions coming!

The next one I see is 

February 20, 2019 · 
Haven't posted in a while because I haven't done any particularly noteworthy new features. But I have been addressing a whole bunch of smaller issues over the past few weeks - as always, you are all the best source of suggestions and ideas for how to improve MyFlightbook!
Please keep the ideas/suggestions coming

I must be getting stupid in my old age ...

**Comment by ericberman** [comment]
I don't even see those, they're so low on the list.  See screenshot above.  Anyhow, you're on FB at that point, nothing I can do about it...

**Comment by KayRJay** [comment]
Weird.   I don't know what to do, as I've selected ALL and the filters look right ... I have to contact FB I guess ...

**Comment by ericberman** [comment]
Looks like this may have been deliberate "retaliation" for FB disabling Twitter cross-post.  I'll just post in two places...

**Comment by KayRJay** [comment]
Bummer.   Hope I can figure out how to see the proper stream ...
