### ISSUE TITLE
Provide alerts for expiring currencies

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#461]
MyFlightBook can/should proactively alert a user that a currency requirement is expired or will soon do so.   This is important for safety and compliance with regulations.   Advance notice/warning of a currency that is about to expire could prompt a pilot to take remedial action.

It is currently possible, in the user profile, to specify how currencies are computed and displayed.   Further, the user can request that weekly or monthly totals and currencies be emailed from MyFlightbook.  However, aside from these periodic summaries, there is no current way to be alerted if a pilot's currency requirement is about to expire, or already has expired.

It's true, of course, that the weekly or monthly summary of currencies provides the date through which a pilot is current with respect to a given requirement, and also indicates in red any expired currency.  However, this is not adequately proactive, for several reasons:
- The user might not (want to) subscribe to weekly or monthly emails     
- The user might not pay adequate attention to a regularly occurring email
- The user's currency might expire between weekly (or more likely monthly) emails

A user profile setting to request notification of expiring currencies would be independent of the request for weekly/monthly currency information.   Ideally, this preference could specify how much in advance of an expiring currency he would be notified (in days or weeks, say).  Or, you could set a fixed timeframe (like 30 days).   

One way to implement this feature that might impose a limited burden on MyFlightBook would be to add a column "Pending Notification Date" to the table of user names.   It would be updated whenever the user changed the preference for notification, and the value stored would be the earliest notification for any possibly expiring currency.  On a daily basis, MyFlightBook would check this table for users who need to be notified about an expiring currency.    The user would receive an email every day (with an option to opt-out of further notifications or perhaps an option to specify a "next notification date").

It's probably not necessary to have separate advanced notification periods for different types of currencies.   However, a pilot might simply wish to allow a certain currency type to expire (e.g., because he is never going to fly at night again).  In that case, he would suspend notifications about some, but not all, possible currency expirations.   So, custom notification plans might be an option.

By the way, other electronic flight books (e.g., the  non-free editions of mccPilotlog Pro edition and VortexLog) provide for advance alerts of expiring currencies.   For example, VortexLog (much slower and seemingly a lot less functional than MyFlightBook) permits the user to say "Notify me x days before any of my recency of experience, endorsements, or my medical expire".  VortexLog also permits the user to create custom alerts (e.g., send a custom email to the user if If "Night Landings is Less Than 3 within the Preceding 90 Days").  

Also, "mccPILOTLOG monitors all your certificates and currencies, including minimum IFR or Night time, minimum number of autolands or ILS approaches, airfield qualifications, license renewal dates, medical and passport expiration, and many more… The notification period is user selectable. Monitoring and alerts are synched with your mobile device."

**Comment by ericberman** [comment]
Indeed, I've had something like this on my list for a long time, and I completely agree that it's a good feature.  Always been an issue of figuring out what the right way to do it is, and the best I've been able to come up with is essentially what you propose: i.e., each time a user makes a change to their logbook, set a flag and that night you can go through only those pilots whose flights changed that day and update their currency; you can then clear the flag and in a side table produce a set of notification dates.

**Comment by KayRJay** [comment]
Glad to know it's on your radar.

It's probably (almost certainly) not enough to make the currency check when a user changes the logbook.  After all, it's often the passage of time (without any new flights) that causes a currency to expire.   I think you have to check the proposed "Pending Notification Date" once/day (for all users who have enabled alerts, which might be a small subset of all users) and issue notifications daily until/unless the user turns them off.    Off the top of my head, I'm not sure there is any other workable solution.

Clearly, you do have to update the user's currency any time they add or change a flight.  I assume you do that already, but that has nothing to do with alerts.

**Comment by ericberman** [comment]
Nope, I don't update the currency when they add/change/delete a flight.  Currency is ALWAYS computed on demand - and it has to be.  There are a number of currencies that literally change minute by minute (e.g., part 117 - which doesn't have an expiration so much as a limit), and it's computationally expensive, so caching it is a waste of CPU resources - would always be invalid.

What I think I'd do is this: for people who dirty (= make any change) their logbook in a given day, I already set a flag.  (I cache achievements and currently that's the only thing I use the flag for, but it's still a useful general purpose "dirty" flag).   Each night, I'd look for the subset of users that are both (a) subscribed for notifications, and (b) dirty.  For each of them, I'd compute currency and store the results in a separate table of upcoming expirations.  Then I'd look for all expirations within N days, and send email notifications on those, clearing the entry once the notification is sent.  

For simplicity, I think I'll make N a constant, like 7 days.  So any currency that has an actual expiration date (as opposed to a limit, like part 117, or an aircraft hours, which can't be predicted) within N (=7) days would generate an email and clear the currency.  If you log another flight within those 7 days, you'd re-dirty your logbook, and (if you haven't regained currency) cause another email to be sent.

**Comment by KayRJay** [comment]
OK, perhaps I misunderstood.   Or maybe I still misunderstand.

If I DON'T change my logbook in any way, and it is "clean", you wouldn't check currency.   But simply the passage of time can cause currency to lapse.   If I haven't flown (at all) for some number of days (even a week), my night currency would lapse if more than 90 days passed since the last night flight.  Given your suggested approach, I don't see how you'd capture that.  It doesn't seem that dirtying the log is relevant to notifying users about expirations.  Maybe I'm mistaken?

I'm not smart enough to know anything about Part 117 currency requirements, so I can't tell if the approach I mentioned applies or not.

I don't think 7 days is enough.  I might not be able to remedy the lack of currency with only 7 days' notice.  Why not let the user specify this, or pick 30 days?

Sure, it's ok to stop sending notices after one notification, rather than do so every day.  Perhaps the right time to "dirty" the logbook is simply on a login, rather than when a flight is added or changed.

**Comment by ericberman** [comment]
Correct - if you don't change your logbook I wouldn't check currency.  But at the point you say "Notify me", I'd dirty you.  From that point on, you'd in sync because that night, I'd cache your currency, and each subsequent night I'd decide whether or not I need to notify you, and I'd clear the cached currency once sent.  If you never do anything in your logbook again, you'd get the one notification when things expire.  And, of course, if you do anything in your logbook, you'd be re-dirtying your logbook

30 days is a long time.  It's 1/3 of most passenger currencies; it's ALL of a VOR check on your aircraft.  I could let the user pick, it's just a bit more complexity.

Login is a poor approximation for dirty.  If you check the box to remember you, or if you use the mobile apps (as probably more than half of my users do), then login is a very rare event.

**Comment by ericberman** [comment]
Thinking about this a bit more I *might* make it a premium feature (say, $15 donation level?).  Rationale:  
 * I might not be able to avoid computing every night, so it's a good way to throttle additional load (or help pay for more CPU).  Still thinking about caching issues and determining when to send out alerts and how to know that an alert has been sent out.
 * Additional email also incurs incremental cost
 * Provides a gratuity at a level that currently doesn't have one.

Some additional thoughts:
 * Right now each currency item determines when it goes from green (OK) to blue (not yet expired, but getting close).  If I compute every night, I can just use that transition to trigger an alert (but then still need to know that it's been sent out so that I don't send multiple alerts.)  But this would allow for variation between lead time for 90-day currencies like 61.57(a/b), 6 month currencies like 61.57(c), 30-day currencies like VOR checks, and so forth.
 * If cached, then I'd need to modify currencystatusitem to indicate green-to-blue lead time and cache that.  All red (expired) items can be discarded from the cache; items in the blue range would trigger a notification and then be removed, green items would remain pending their expiration.
 * If user is subscribed to any other email (weekly/monthly), then on any night that email goes out we'd consider the alert to have been sent too.

Still noodling on how to do this...

**Comment by KayRJay** [comment]
Perfectly reasonable to offer this in exchange for a donation.    You don't need to make any case as far as I am concerned.  You have made an enormous contribution to the flying community.  You could move to a subscription model and not lose many users.   Go for it!

**Comment by KayRJay** [comment]
Oh, and thanks for considering this idea and responding to all my bothersome notes in GitHub and otherwise!

**Comment by ericberman** [comment]
Couple of other thoughts:
 * need to include deadlines
 * all of these items will need to add a new property to indicate when they turn from green to blue, since that transition

**Comment by ericberman** [comment]
Whew, that actually touched a bit of code.  Probably the trickiest thing to verify was that I'm properly determining what changed from green->blue, green->red, or blue->red, and that I'm not spamming.  So the checkbox is really an "accelerator" - if you have weekly email, it will send it, but I bypass the weekly email if you have an expiring currency.

**Comment by KayRJay** [comment]
Glad this got done!   I'd be interested in a brief explanation of the implementation, if you don't mind.

By the way, this is another feature you could add to the competitive comparison listing you'll probably do sometime!
