### ISSUE TITLE
Use templates to control logbook display format

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#479]
Currently, the Logbook view displays the following information for a flight:

- Flight date
- Route (if present)
- Comments (if present)
- Tail number
- Cat/class/type
- 11 numeric values

This format is fixed, there are no alternatives, and no way for users to control which of these fields are displayed.  Unfortunately, this fixed format often wastes space and may not include the flight information most relevant for the user.  While the recently added templates feature is useful for reducing clutter and simplifying entry of a new flight, templates have no role in controlling what is displayed in the logbook view.

Templates could allow users to control the logbook format in a way that is most useful to them.  Some templates include many properties, more than make sense to include in each line of the logbook view.  So, it’s necessary to allow users to tag which properties of a template should be included.  Because property names are typically long, permitting the user to specify a "short name" would keep the flight display compact.

In addition, to save space, it would be helpful to be able to suppress display of the flight route, tail number and comments.  

Modest user interface changes would support these enhancements.   On the logbook page, the user could specify which template should be used to format the display.   The drop-down would first list the templates in the user's profile (those most likely to be of interest), then the shared or public templates.
<img width="362" alt="Screen Shot 2020-02-01 at 1 01 43 PM" src="https://user-images.githubusercontent.com/16978320/73598251-07fd3d80-44f3-11ea-8399-87f8bb959803.png">
The other UI change is to provide a way for the user (on the create/edit templates page) to select the properties to be displayed when a template is used.  The left-to-right display order of the properties would be controlled by the top-to-bottom ordering of properties dragged to the right-hand box.  

Something like this might work:
<img width="970" alt="Screen Shot 2020-02-01 at 1 49 08 PM" src="https://user-images.githubusercontent.com/16978320/73598777-a68c9d00-44f9-11ea-9925-4219263491c9.png">
 
You could set a limit (10-15?) on the number of properties to be displayed, or allow the page to get as wide as the user wants it to be.

Note that the pre-defined templates should have a selection of properties to display.   When the user shares a template, his displayable properties should go with the template.

In the logbook view, with this enhancement, every field after the date would be under the user's control.   Of course, this discussion applies only to the web interface, as the mobile application has a completely different format for displaying flights.

Why do this?   Well ...

- It saves ("precious") horizontal space
- Users can see the properties that are most important to them
- No other way displays a list of flights with other than the pre-defined properties

Some use cases:
- a pilot only flies one airplane
- VFR pilots never fly in iMC
- users may not use simulators at all- 
- some properties are germane to certain flight types (aerobatic, military, etc.)
- an instructor wants to see the student's name for a flight
- a club manager wants to see the name of the pilot

The flexibility this feature would provide "infinite" flexibility, to meet any number of use cases.

**Comment by KayRJay** [comment]
A couple of other thoughts ...

The five current pre-defined templates (Checkrides and Reviews, Lesson Plans, Missions, Roles, Training) are certainly useful for data entry, and probably serve as a good basis for the format of logbook displays too.

However, a special group of templates could be exist solely for the purpose of controlling the set of properties displayed in the logbook view.   Users could define their own display templates, including just those properties they are most interested in.  MyFlightBook could provide pre-defined display templates that include those properties used in one of popular manual (or competitive electronic) logbooks, such as ASA, Jeppesen, Gleim, Sporty's, etc.

Display templates would not affect the list of properties shown for entering new flights.  These templates would be treated just like other templates in all other respects.   

In the drop-down ("Use a template"), templates could simply listed in alphabetical order.   Alternatively, given their purpose, it might be better to list display templates before those that were designed for data entry, and display the other types of templates (first private, then public) following the display templates, listed in order by type of template.

The user's selected template for the logbook view should of course be sticky.   It needn't be specified in the user's profile, but simply saved in a cookie, and used for each session until it is changed.

**Comment by KayRJay** [comment]
Obviously, the width of the logbook view is affected by the number of parameters displayed.  With any given set of parameters, this might be as large as the current width of the logbook display.  When the Logbook listing is wider than the window, the entire window can be scrolled as it is now for a narrow window.

**Comment by ericberman** [comment]
This one gets a bit hairy and tangled up with overall layout customization.  But customization is not a bad thing!  I wonder how much of this I could do by simply layering different stylesheets.  I'm a bit constrained here by the "Gridview" tool that I'm using for the display here, which handles an obscene amount of code for me...

Anyhow, a few quick comments/observations:
 * You refer to "The five current pre-defined templates (Checkrides and Reviews, Lesson Plans, Missions, Roles, Training) ".  I should note that these 5 things are not templates.  They're nothing more than a taxonomy of grouping labels; they have absolutely zero functional value in the system.  The goal is to (a) suggest templates that might be useful, and (b) make a library of templates easier to grock than a big flat list would be.
 * In the code I use the term "Property Templates"; in the UI, I refer to them as "Flight templates".  Should probably be precise about using that because what you're discussing below is a distinct form of template - a layout template.  As you point out, you're talking about display independent from data entry.  So let's refer to a customization of display as a "display template" (for lack of any other better term) to avoid confusion with the distinct concept of a flight template/property template.  In that context, I currently have only 1 display template.  
 * A display template would have two dimensions of customization.   One - which is the focus of your suggestion above - is content.  I.e., what do you include and what do you exclude.  The second would be more aesthetic: what fonts, sizes, and arrangement is used for each row.
 * I actually do have (very limited) customization of the current display template: you can turn on/off SIC and CFI (this controls data entry as well).  The thesis behind this is that of all of the "standard" columns (i.e., the stuff common across all flying and across all paper logbooks), these two columns more than any other are something a pilot will either use a lot or will never use.  Most pilots will in fact - at some point - use pretty much every other field.  Indeed, you can't get your PPL without logging (and being able to demonstrate to your examiner!) night, cross-country, simulated-IMC, PIC, Dual, and Total Time.  Ground Sim and IMC are probably the only two other candidates that are frequent/never, but even these are not exotic fields.

Anyhow, I have a template architecture for printing precisely because there are prescriptive regulatory requirements, different traditions, or mere aesthetic preferences.  I could conceivably use a similar model for the interactive display.  ("Interactive" is a key distinction here that actually does make the coding a lot more complex.)

**Comment by KayRJay** [comment]
Thanks for the reply.   I look forward to hearing more.

**Comment by KayRJay** [comment]
The template would control which the properties are displayed (and possibly subtotaled).   The template would be "sticky" and remain selected until changed.

**Comment by KayRJay** [comment]
The idea of a "short name" for properties (issue #480) obviates the need for a short name field in the user interface.  Properties are curated, as they are added only by the administrator.  Their short names should be managed in a similar way, so all users would see the same names in the logbook for any given property.

**Comment by KayRJay** [comment]
> But customization is not a bad thing!

Agree wholeheartedly!  The goal, I think, should be to give users significant power to customize the appearance of the logbook, while keeping the user interface clean and simple, and avoiding excessive implementation effort.

> You refer to "The five current pre-defined templates (Checkrides and Reviews, Lesson Plans, Missions, Roles, Training) ". I should note that these 5 things are not templates. 

My bad ... I knew that, but left out the words "types of" ...

> As you point out, you're talking about display independent from data entry. 

I take your point in issue #478 about being two independent types of templates, one for the logbook and one for data entry.

> A display template would have two dimensions of customization .. content and aesthetic: what fonts, sizes, and arrangement is used for each row.

I don't suggest customization re aesthetic issues.   All I care about is the content.   I can change the font size (and maybe the font style?) in the browser or OS.  The only "arrangement" issue  important for me would be the left-to-right order of properties, which I suggest could be specified by the order of properties in the drop-down list.  Anything beyond that is unnecessary complication for the user and work for you.

> all of the "standard" columns (i.e., the stuff common across all flying and across all paper logbooks) more than any other are something a pilot will either use a lot or will never use.

Let me clarify the essential point of my proposal.  I am not trying to replicate a printed logbook with this proposal.  It is handy to be able to produce (for example) totals that might correspond to the N flights on each page of a manual logbook, but this is only one of many uses of this proposed feature.  Let's even forget for a moment the idea of totals and subtotals for any group of properties (and discuss that further in issue #481).  

The core idea here is simply to use a template to control which properties are displayed.  This way, each flight shows only those properties a user wants to see.  A template is a great way to group properties that are "interesting" to a user.  These are the properties he wants to enter for a new flight, or to see in the logbook (at a particular time).  

A user may not want to see the "standard columns" (properties) when viewing the log.  Even the tail number and category/class/type might not be useful for a user interested in reviewing his flights.   Sure, a user must use night, cross-country, PIC, Dual, and Total Time (but not necessarily SIC, CFI, Ground Sim or IMC) in his logbook and to become certified.   However, he may want to look at his logged flights for reasons other than getting his certificate.  I'm sure there are additional reasonable use cases beyond those I mentioned above.

> Anyhow, I have a template architecture for printing precisely because there are prescriptive regulatory requirements, different traditions, or mere aesthetic preferences. 

Sure, it makes sense to have a template architecture for printing for all those reasons.    Those reasons don't apply to a logbook view, where "what the user wants to see" is the key factor to decide what should be displayed.

>I could conceivably use a similar model for the interactive display. ("Interactive" is a key distinction here that actually does make the coding a lot more complex.)

I gather per your comment re "not super hard" in issue #478 that the complexity isn't so bad if all you're doing is controlling the list and order of included properties, but not other aspects, of the display.  You of course are the best one to know what makes this sort of model difficult for the interactive (logbook) display.   As a used techie, I have a rough conceptual idea of what it takes, but I'll refrain from speculating.

**Comment by ericberman** [comment]
Added support (not yet deployed) to customize the core time fields (PIC, Cross-country, Night, SIC, IMC, etc.) when entering a flight.

May optionally add more options for display of tabular data, though that can be very difficult (particularly for print layouts) as the print layouts are often prescribed (EASA and others have very "thou shalt have column A for this and column B for that..." requirements) and/or because these layouts are finely hand-tuned and fragile to stuff showing/disappearing.  For now, this remains limited to SIC and Instructor columns because those are the columns most pilots either never use or frequently use, but they're not "occasionally" used (the way that night, ground sim, or cross-country might be).
