### ISSUE TITLE
Create, for each property, a short name

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#480]
It would be helpful to define a "short name" for each property.  This short name could be used in various places (like the headings in the logbook view), where the sometimes very long names wouldn't fit.

**Comment by ericberman** [comment]
I like the idea, but I'm not sure this is necessary, since the system already uses ellipses for this, using CSS "text-overflow: ellipsis".

E.g., in the image below, the actual text for the ILS Approaches column is in fact "Approaches - ILS".  The browser automatically measures the text and inserts ellipses:
![image](https://user-images.githubusercontent.com/16455286/73623493-f484cc00-45f1-11ea-8bc7-510116d38878.png)

While I could optimize a few names by using well chosen abbreviations, the ellipsis is a better general solution because it will adjust the ellipsis automatically based on font, font-size, and width available.
