### ISSUE TITLE
Prevent data pollution by limiting creation and sharing of common entities

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#490]
It's very easy for users to pollute the shared data visible to all users.  For example, I can now create a model of an aircraft, including a bogus manufacturer.  Same for airports, clubs, and perhaps other entities?

Such entities might be automatically shared, or kept private to the user.   MyFlightBook should protect the database from pollution, and permit the creator of such entities to keep them private, offer them for sharing (possibly subject to curation?), and to delete them.

For example, the MySQL table "airports" could record additional information unique to MyFlightBook  about the airport (as opposed to public information such as in [AC-U-KWIK](https://acukwik.com/Airport-Info/HCR)):

- the creator (username) of the airport
- the date/time it was created
- whether it is offered for share
- whether it is now sharable/public or private to the creator
- the number of flights that have visited the airport
- the most recent date/time of a visit

Likewise for clubs.   The creator might be the only one authorized to add aircraft, or allow members to join (or edit or delete the club).  Similar for other shareable entities?

If a creator of an entity deletes it, you might need to record a tombstone (as you apparently do for aircraft), in case there are flights that reference the deleted entity.

By the way, this technique also helps with the playgrounds suggestion (#488).   A playground user might be able to create entities (and even offer them for sharing), but they never would be made public.  And when the playground user is reset, any entities he created would be deleted.

**Comment by ericberman** [comment]
Can't and won't do this.  The whole system is predicated on sharing this stuff; it breaks if I don't do that.  I'd have to rework huge portions of the system to support this, and doing so would break a fundamental premise of the site: that airports, aircraft, models, etc. are all crowd-sourced.  If you can make these things private, then people won't share.  

There are multiple benefits to this 
 * when you join the system and go to add your first aircraft, you almost always find that its model is already in the system, and the aircraft probably is too.
 * You get higher quality data because it gets reviewed by many eyes and fixed.  Someone sees, for example, that you entered a C-172 S as a vanilla C-172 and edits it; you get the benefit of that.
 * Someone adds pictures to an aircraft you flew years ago, you get that.
 * Someone updates the maintenance for an aircraft you fly - you get that.
 * Someone adds a missing airport, or updates a code that changed.  You get that.

This sharing wasn't a feature I coded; it falls out of the design of the system, and I designed it that way very deliberately.

Note that clubs are controlled.  The aircraft within them are shared amongst all pilots in the system, but only club pilots can schedule it within the context of a club.  So there's no issue there.  And clubs are not shared - only an owner of a club can delete it, and only an admin/owner can invite people to join the club or approve requests to do so.

Note also that I do record the user that created an airport, but if I end up reviewing it, I often absorb it into the system as a "native" airport (which cannot be overwritten by users).

Thankfully, pollution has not been a problem.  It does require a bit of data curation for things like models and resolving conflicting edits to aircraft, but the bandwidth required of me for that is fairly low and the benefits of this are enormous.

**Comment by KayRJay** [comment]
Good to know and makes sense.
