### ISSUE TITLE
Search enhancements: UI and performance improvements

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#521]
With all the properties that can be used in a search, it can become cumbersome to execute repeated searches with different criteria.

There should be a way to "uncheck" all the criteria in a section of the search page.   A link "Clear all" next to the "Click to show/hide" link would do the trick.

It would also be nice to have a "Clear all" link/button to reset all search criteria to the default (or not selected).   The current "Reset" button at the bottom of the page does that, but it also executes a search, after clearing all search parameters.   That's not an intuitive response to the word "reset".  

Perhaps that button would be better labelled "Clear all", and not do the search.  If a user wants to search with no criteria, the "Find matching flights" button is right there.  With a "Clear" button, the user can easily redefine the query he wants to do, without wasting CPU cycles to execute a search for all flights (that the user probably doesn't want), and without the need to again press the Search menu option.

Lastly, in any page showing a subset of flights (after SEARCH, CURRENCY, TOTALS, ANALYSIS) there is a "disclaimer" showing the search criteria for the current result set.   Unfortunately, when multiple criteria are used, the user has to click on the red X to remove each one, and as he does so, MyFlightBook executes another (probably not useful) query.

It seems there should be a "Clear all" or "Cancel Query" button, perhaps in one of these forms:

<img width="984" alt="Screen Shot 2020-03-03 at 3 23 14 PM" src="https://user-images.githubusercontent.com/16978320/75825815-5fe1cb00-5d63-11ea-9fb1-5d78060d025d.png">
<img width="1016" alt="Screen Shot 2020-03-03 at 3 22 01 PM" src="https://user-images.githubusercontent.com/16978320/75825825-640de880-5d63-11ea-8674-8cfd7b529ffd.png">

By the way, what is the difference between these groups?

- Flight has the following characteristics: (Click to Hide):
- Flight has these properties: (Click to Hide):

Both sets of "things" seem to be part of what can be added as "Additional properties for your flight ..."

**Comment by ericberman** [comment]
Very reasonable suggestion.

To your question: yes, I suppose properties are characteristics of your flight.  The difference is "flight has the following characteristics" includes core fields that EVERY flight has (even if 0) - i.e., every flight has a "night" attribute, but it may be zero, but not every flight has, say, a "Carrier Landings" count.  I.e., these are the fields that correspond to what you'd find in a paper logbook, along with things that are not explicit data you entered - e.g., flight is signed, flight has telemetry, flight has images.  "Flight has these properties" are the additional fields (properties) that you have chosen to add to this flight but not that flight; these data points are much more ad-hoc.

**Comment by KayRJay** [comment]
Ok, thanks for the explanation.  It is subtle, but makes sense.   It's a bit confusing because the list of 600+ (or more) properties you can add to a flight includes "characteristics" that all flights have as well as these "special" ones.  No biggie though ...

**Comment by ericberman** [comment]
Yeah, it's one of the seams in the UI that is hard to eliminate - the "built-in" fields vs. the optional stuff.

**Comment by ericberman** [comment]
OK, I did the "Clear all" in the list of individual applied filters. 

I decided against adding a "Clear all" to the search form, for two reasons:
 * Doesn't avoid a postback - all of the logic for populating the form lives on the server, so it needs to do the postback regardless.  I don't want to do this in javascript either because, while it would indeed eliminate the postback, it's a bunch of code that parallels what the server needs to do anyhow and then would be a maintenance nightmare if I make changes in one place and forget to do it in the other.
 * The distinction between "Clear form" and "Reset" is super subtle (per the suggestion above, the only difference is whether or not the search is executed), so I think it's confusing to have both.  If I have to do the postback anyhow (per the first point above), then the actual query is essentially free.  So that leaves the main question of semantics down to the more common scenario: are you doing this because you want to go back to viewing all of your flights, or are you doing this because you want to modify your query?  One of them has an extra click: if it's the former, then clearing the form has an extra click to execute the search; if it's the latter, then the extra click is to expand the search box to enter new data.  I can't eliminate that without two buttons, which I've otherwise ruled out as being confusing.  But ultimately, I imagine both scenarios do occur, so sometimes you won't have a click and sometimes you will, depending on the scenario.

(Personally, if I'm doing a new search after a prior search, I'm inevitably refining the prior search, not starting over from scratch anyhow...)

**Comment by KayRJay** [comment]
There is still a subject to be addressed here.  Instead of clearing one group of criteria at a time, a user should be able to remove all search criteria (even if it does another query) on those pages that show a "disclaimer" showing the search criteria for the current result set. The includes  SEARCH, CURRENCY, TOTALS, ANALYSIS. 

It seems there should be a "Clear all" or "Cancel Query" button, perhaps in one of these forms:

<img width="984" alt="Screen Shot 2020-03-03 at 3 23 14 PM" src="https://user-images.githubusercontent.com/16978320/75940997-c215fb00-5e4b-11ea-9d49-52d86ce6fd2c.png">
<img width="1016" alt="Screen Shot 2020-03-03 at 3 22 01 PM" src="https://user-images.githubusercontent.com/16978320/75941013-c8a47280-5e4b-11ea-9901-8b9929e5077f.png">

**Comment by ericberman** [comment]
That's what the check-in above does.  It only shows when there are 2 or more criteria (since it's completely redundant if there's only one criteria):
![image](https://user-images.githubusercontent.com/16455286/75944144-c7734580-5e4b-11ea-8473-bef5eb7d374e.png)

Note that this has NOT yet been deployed to the live site.

**Comment by KayRJay** [comment]
Excellent.   Didn't perceive that from the previous comments.
