### ISSUE TITLE
Raw data report in Analysis wastes space and CPU time and user time

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#522]
The new features of the Analysis tab are very nice ... nice job, and thanks.

The analysis raw data report table totals  17 properties (and 34 running totals when grouping by time).  This is quite a long (left/right scrollable) list, and is perhaps not the most useful format.  Many of the columns have values with just a single digit or a very few.  How about putting the column headings on a slant?

More importantly, it would be helpful to give the user control over which flight properties and characteristics are totaled.

I was surprised to find, that the Analyss tool shows many totals for things I never have done, and no totals for things I have done many times.  I've never done any night flights, instrument work or simulator sessions.  Likewise, though my CFI wanted to know how many stalls and steep turns I've done during my training, that isn't in the Analysis either.

It's true, of course, that I can obtain totals for flights with any given property.  Doing so is  cumbersome to do for each property not currently totaled for Analysis.  It requires multiple searches, one for each property.  I'd have to ignore the resulting flight light, just to get a count.

Perhaps this is another place where Templates might be used to control the formatting and content of totals, as was suggested in issue #479?  This same suggestion also applies to the Totals tab (issue #518).

**Comment by ericberman** [comment]
I like the angled header idea.

The default list is for all of the "core" fields, supplemented by any summable properties you've logged.  The properties are, by definition, things you've used.  The core fields may be all 0's, but they're core because they are so common across so many modes of flying.  

I put this into a collapsible panel precisely because it is big and awkward.  I have to implement it somewhere to enable download to excel, so I made it available to view too.

By the way: I too was a bit confused why stalls and steep turns weren't showing up in the count or totals for you and then I realized why: these aren't counts; they're all true/false.  I.e., "I did steep turns on this flight", not "I did 2 steep turns".  The key thing is that you need to document that you've done training for things like takeoff stalls, but nobody cares how many times you practiced it.

**Comment by KayRJay** [comment]
Almost everywhere else in MFB, I think you suppress the things I haven't logged, whether "Core" or "Special".   That's why I was surprised to see things I didn't ever do.

The excel download is nice, and it could of course include all of the "eligible" fields, even those I did not ever log or that are "Core" and not in my chosen template.

Yes, I wanted a count of the number of flights where I did a specific maneuver.

**Comment by ericberman** [comment]
The main logbook summary (the list of flights) doesn't suppress these things; I'm pretty much matching that.  It's a "group by" view of the main logbook.

**Comment by KayRJay** [comment]
Right.   But in totals elsewhere (e.g., TOTALS) you do not suppress things I don't do.   The Analysis tool is much more like TOTALS than the Logbook, wouldn't you agree?

**Comment by ericberman** [comment]
Bleah, rotating doesn't work:
![image](https://user-images.githubusercontent.com/16455286/75914085-fcaa7400-5e08-11ea-85d0-6815e3bc9cec.png)
The problem is that the browser computes the width of the cell based on the unrotated text, but then rotates the text afterwards.  I don't know of any way to work around that besides forcing all columns to be pretty wide.  I think unrotated actually works better.

I can suppress columns that are all 0.

**Comment by KayRJay** [comment]
Yeah, "blech".   Thanks for at least suppressing zeros.

Are you thinking about using templates for this purpose?

**Comment by ericberman** [comment]
No, I don't see what that solves.  Templates are really about tailoring data entry for a specific flight scenario; this is a report that spans lots of flights; as discussed elsewhere, templates don't really work as a concept for (potentially) heterogeneous sets of flights.  It would conceivably need a new concept.  

But I think the automatic "report on everything reportable and strip anything with null data" is a great solution.

**Comment by KayRJay** [comment]
Well, maybe.   

You’re certainly consistent in your views.  If it were up to me, I’d give the user more options in general, and let him decide what features work for his needs.

But then again, it ISN’T up to me!

Ken
