### ISSUE TITLE
New features list

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#524]
Since MyFlightBook continues to evolve with lots of new features frequently being added,  it would be nice to create greater awareness of these features, leading to more use by more users.

While the blog is a great place to describe new features of MyFlightbook (and how to use them), it could be more prominent.  Now, the link to the blog is at the very bottom of the page among a number of other links.  The scrollable list on the home page is great, but not always visible.  In fact, after I sign in (if I had been signed out), I go straight to the Logbook, and don't often/ever visit the home page.

Do you know how often people visit the Home page?  If it's not often, perhaps it could be limited to the large "tiles" that correspond to the top-level menu with explanations.   Then you could add a new "About MyFlightBook" top-level menu to the right of Profile.

That "About" page could have the scrolling list of "news", the statistics about MyFlightBook, a recent image AND a link to a page of New Features (that link cold also be on the About menu).   The new features would be listed with a very brief description, in reverse chronological order, along with a link to the blog entry (if any) describing them in some detail.

**Comment by ericberman** [comment]
I like the idea, but I think Facebook/Twitter is a better source of timely data.  

The home page isn't super highly used once people start using the site; the scenario you describe for yourself is quite common. 

I could certainly add an "About" item to the top level menu, but there's really nothing there that isn't redundant with things that have become industry standard to also include in the footer.  E.g., I'm typing this right now on GitHub, and things like the blog and "About" are indeed, right there on the footer.

I'm very reluctant to try to be more formal in new feature announcements/descriptions for a variety of reasons:
 * Many are very minor.  
 * The blog tends to dive into logbook issues at a high level and only occassionally dives into specific features - and usually to provide context for the design decisions that I've made.  Facebook and Twitter are where I generally announce new features.
 * Once a feature is added, it's not really relevant to people when it was added; they just like to have it (I hope!)
 * Amazon, Facebook, Microsoft, etc. - they announce significant new services for sure, but they don't generally try to push every tweak in front of their users.  I agree with that philosophy.
 * It's a ton of work to ensure that I'm publicly documenting everything and keeping things fresh.  Only so many hours in the day.  I simply can't commit to this, so a dedicated page would get stale quickly.
 * I'd rather people follow me on FB/Twitter anyhow because there are many ancillary benefits to that (specifically: it's a two-way communication channel).

So I'm fine telling people to watch the home page or follow me on Facebook/Twitter if they want to follow what's been happening.

**Comment by KayRJay** [comment]
It would be interesting to know how many followers you have relative to the number of users of MyFlightBook.  I wouldn't be surprised if many people miss out and don't learn about all the wonderful features MyFlightBook has.

I appreciate your perspective and understand that work would be involved (though this would be limited if the feature was described in a line or two, rather than in a blog).   

Ordering by date is only a simple way to organize the features (rather than create a document with feature groups).   The date isn't interesting per se, only so that users can see what's new since their last visit.  

There isn't really a need to keep the feature list fresh ... just add new features as they come along.  Blogs get more stale than lists of this kind, and usually serve the purposes you describe. 

It was just a thought.

**Comment by KayRJay** [comment]
The other problem ... that the home page isn't regularly visited ... means that people don't see your scrolling list of "news", the latest statistics about MyFlightBook or a selection of new images.  Even if you don't implement the feature list, making those things more visible from the page where users typically go, is a useful thing, it seems to me.    Let the Home page contain those "tiles", but move those other elements to a place where they would be more prominent.  I'm not a coder, but it doesn't seem doing this would require a lot of work at all.

By the way, how do you close an image when it is expanded to the full window?  ESC doesn't work (in Safari).  Furthermore, because the next/previous arrow are IN the image, it is too easy to expand the image.  There's room to put those arrows (which sometimes are hard to see, depending on the image) to the sides.

**Comment by ericberman** [comment]
Image opens in a new tab, so you can just close the tab.  Ctrl+W/Command-W.

As for exposing this: it's a question of priorities.  How important is seeing what's new when I come to the site vs. getting done what you want to get done.  This is very clearly in the realm of "discoverable if you're curious, but not in the way if you're not", IMO.  I DESPISE all of the apps and websites that make me click "got it" every time they have a new feature (or, worse, that force me to be exposed to half a dozen.)  Yes, it's a philosophical choice.  But the more you promote this and that, the more everything else gets lost in the noise.
