### ISSUE TITLE
Instructor name property and value is not sticky, CFI searches only possible via text

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#540]
As a student pilot, I want to record the name of my CFI with each flight.  Though I add "Instructor name" as an "additional property" as I enter a new flight, the instructor name field is not present for the next flight I want to add.   I have to add it again as an "additional property".  I don't know why that property, unlike others, disappears.

When I add a new flight, if I have entered a value for Dual Time, the Instructor name should be populated with the name of the CFI on my most recent previous flight.   ("Most recent" because I may add flights not in chronological order.)

Always populating the name from that previous flight would be ok too, regardless of whether there was Dual Time.  Once I solo, and have my license, it's likely that consecutive flights will have neither Dual Time nor an Instructor (unless I'm taking renewal training, etc.)

Other than searching in Text, I can't search for flights with a given CFI.  I can't search for flights that are NOT with a particular CFI.  (There should be a NOT CONTAINS option for Text searches.)   

Flights with Dual Time but no CFI should be raised as an "issue" when checking flights, so I could then find and fix them.

**Comment by KayRJay** [comment]
Note that I do have checked "Training > Student VFR Private Pilot - Pre solo".

**Comment by KayRJay** [comment]
I didn't have Instructor name in my template. Please ignore the part of this issue that questions why the property isn't available.

There are still issues re pre-populating the field, searches not containing text, and checking for an instructor name when dual time > 0.

**Comment by ericberman** [comment]
I do not pre-populate fields on new flights by default, on purpose: it's too easy to accidentally pre-populate to an inappropriate value.  People have lots of different instructors.  The only field I ever pre-populate on a new flight is the starting hobbs (using the ending hobbs from the prior flight); I think adding more pre-population than that will cause more negative issues than positive.  There is no downside to failure to record a value, there is significant downside to accidentally recording an incorrect value.  This is a VERY deliberate design decision; the last thing I want is to get people in trouble because they logged stuff without realizing it.

This field auto-completes (like any other text field) so you can just type a few letters of their name to add it.

As for "not contains", that's not a bad idea.  I don't have a solution for that at the moment.  I'll open a separate issue for that, since this issue has a whole bunch of other associated stuff.

**Comment by ericberman** [comment]
Issue #544

**Comment by ericberman** [comment]
BTW, while I don't pre-populate, this field should auto-complete to previously used values...

**Comment by KayRJay** [comment]
Yes, you wrote:
> This field auto-completes (like any other text field) so you can just type a few letters of their name to add it.

You also said, a few hours ago:

> As for "not contains", that's not a bad idea. I don't have a solution for that at the moment. I'll open a separate issue for that, since this issue has a whole bunch of other associated stuff.

But apparently you did have a solution, documented and implemented in issue #471 over a month ago.  (You must have forgotten?!)   As suggested in issue #545, this feature should be documented outside Github.
