### ISSUE TITLE
ALL and NONE as qualifiers for airport searches

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#543]
All, Any, None work for other properties and characteristics, but not for airports.  It is reasonable to search for flights that did not visit any of the specified airports, as well as those that visit all of the specified airports.

**Comment by ericberman** [comment]
No need.  If you don't want to find flights that flew to xxx, then add -xxx to the search query.

issue #471

**Comment by ericberman** [comment]
E.g., can search for flights that didn't visit my home airport of (K)PAE.  I search for "-PAE" and that correctly subtracts these flights from search

**Comment by KayRJay** [comment]
Didn’t work for me.   ‘-U14” finds flights that DID visit U14.

Besides, the current search is ANY.   There’s no way to find flights that visit ALL of the listed airports, is there?

Why not make the UI consistent, and offer ALL, ANY, NONE for airports, as you do for other “properties”?   Why should airports use the “-“ notion but others not?

**Comment by ericberman** [comment]
The general text field is the one that supports and/or/not: if you search for -U14 in the general text field, it excludes visits to U14, since the route of flight rolls up into the general text field.  I don't currently support the boolean stuff in the airports-only field.  No particular reason; just work, I could add that, though it's pretty low priority since general text.

**Comment by ericberman** [comment]
Just took a look at adding And/or/not to airports - it's actually hard to do because this field is parsed differently.  I parse this into distinct airports before doing the search, and then build the text query off of that.  The only symbols I preserve are the "@" prefix (for navaids), and the "!" prefix/postfix.  And the mobile apps do the same.  This helps with normalizing and structuring the search criteria.

You can use the General Text field to do a more text-based solution, since general text includes route of flight.

**Comment by KayRJay** [comment]
OK, thanks.
