### ISSUE TITLE
In Search, unify  "characteristics" and "properties", permit adding searchable attributes

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#549]
Per issue #521, there is a subtle difference between "characteristics" and "properties" (let me call them "attributes") of a flight, but they are separated on the Search page:

> Flight has the following characteristics
> Flight has these properties  

And, these "attributes" are spread among several portions of the "New flight" screen: Times, "additional **properties**", and other fields.

You have defined the "characteristics" as "core fields" that are common to ALL flights (even if zero):

<img width="486" alt="Screen Shot 2020-03-21 at 8 13 07 PM" src="https://user-images.githubusercontent.com/16978320/77240846-691ac680-6bb0-11ea-9523-4868d4f1f911.png">

Then there are "properties" that you call "more ad hoc":

<img width="783" alt="Screen Shot 2020-03-21 at 8 10 58 PM" src="https://user-images.githubusercontent.com/16978320/77240831-37a1fb00-6bb0-11ea-94c7-7bfd824f6c29.png">

You have far more experience than I, but I'm not sure it true that ALL flights have those attributes you call "core".   Why is "Cross country time" a characteristic, but "Cross country time over 50 nm" is a "property"? The two groups ... "characteristics" and "properties" ... may really be a distinction without a difference.

You also say that the "characteristics" correspond to a typical printed logbook.  

My Gleim logbook contains the following "attributes" in addition to the obvious date, make/model, ID, airport from & to.  

- Landings (day & night), Inst approaches (No, type & location),  Aircraft category & class
- instrument (actual, simulated/hood, "FTD or simulator"), night (with 2 unlabeled columns)
- XC (all, over 50 NM), PIC, Solo, Gnd training rec'd, Flt training rec'd, Flt training given
- Total flight time, Remarks.

There are quite a few "core" attributes not in my logbook and some that are in my logbook that are not in your "core" list.   I didn't look at other printed logbooks.

But 14 CFR 61.51 defines the  "logbook entries" a person must make to "document and record" the training time and aeronautical experience required for a certificate, rating, or flight review or currency requirement.   The information required falls into several categories: 
- General: Date, Total flight or lesson time, Location (departure and arrival or location of simulator), Type and ID of aircraft, simulator FTD or ATD, name of a safety pilot.
- Type of pilot experience or training: Solo, PiC, SIC, Flight and ground training received, Training received (in a simulator, FTD or ATD)
- Conditions of flight: Day or night, Actual instrument, Simulated instrument conditions, Use of night vision gog

These are truly the "core" attributes, as required by the FAA.  Everything else is ad hoc.

Also, the ten attributes at the top of the New Flight screen 

     Approaches, Total Landings, Cross-Country, Night, Simulated Instrument, IMC, 
     Ground Sim, Dual, PIC and Total Time

don't quite exactly match the FAA requirements, and they are not all "Times" as labelled.

While this is somewhat a discussion of semantics, at least they are (fairly) clear.   It could be argued that it makes sense to combine "categories" and "properties" (and all other "fields" like aircraft ID or to/from airports and "general info" and "times") into one group of "attributes" organized like the 14 CFR 61.51 list on the New flight screen.   I don't expect you to do that, as it's really not necessary. 

However, I do have a request to simplify and enhance the Search page.  There, replace the two sections
> Flight has the following characteristics
> Flight has these properties

with:

>Flight has these attributes:

Below that text would be search fields for a fixed list of attributes that correspond to the 14 CFR 61.51 list of required information.   You would then have a drop-down menu to add "Additional attributes to search ...".   Users could then select any attribute they would like to search on.  This would include many attributes I cannot currently use in a search (e.g., instructor name!).

The drop-down of "Additional attributes to search" might be limited to those attributes the user has ever used, not just recently.   The selected attributes would be sticky in the user's profile, perhaps stored in the dictionary of JSON objects as described in #546.

**Comment by KayRJay** [comment]
And, I believe (without thinking hard or too much about it), ALL, ANY, NONE could apply to all of the "attributes" being queried on.

**Comment by ericberman** [comment]
Short answer: you're actually entirely right that the difference between the core fields and "properties" is a reflection of the database architecture, not the way people think about them.

This seam shows itself in numerous places, not just search.  See https://myflightbookblog.blogspot.com/2018/03/whats-with-these-flight-properties.html, but the gist of it is that the "core" properties are the intersection of the Venn diagram in that blog post, and correspond to the (finite) columns of the flights table.  The additional properties are effectively an unbounded (non-finite) addition of columns for a table.  EVERY flight has a cross-country time (which may be 0), but NOT every flight has a "Cross-country over 50nm" property.  (In DB speak, I can get cross-country time with a simple SELECT statement on the flights table, but to get "Cross-country over 50nm", I not only have to do a left join but I also have to handle a null value, which means not "false" but rather "unknown")  But indeed, that's really an implementation detail that has evolved over time in the UI rather than being designed that way.

Merging them in Search, as you suggest, is pretty reasonable.  In both cases, they really mean "has a non-default value": searching for flights with "night" means searching for flights where night > 0, and searching for flights with an Instructor Name means searching for flights where the left join yields a non-null AND non-empty value; to the user, these are semantically indistinguishable.

The only truly justifiable difference here is that the "core" fields are always available to enter for every flight (i'm happy to walk through the mapping to the Gleim/Jeppesen/other paper logbooks - it really does map, although it's not 1:1 and for good reason!), and always available to query (and each has some sort of semantic meaning to the system), whereas any given user and any given flight will ever only use a subset of the nearly 700 possible properties.  So it is reasonable to do a "core+" UI, with everyone seeing the same set of initial fields + the set of properties relevant to their flying.

I don't think I can remove the seam altogether, though.

**Comment by KayRJay** [comment]
Thanks for the reasonable response. 

Really, this all boils down to “can we make Search more functional?”

Ken

**Comment by ericberman** [comment]
No new functionality that I see above; you're talking about having a more seamless UI, right?

**Comment by KayRJay** [comment]
Fundamentally, my comments are about rationalizing some decisions that have evolved over time, rather than being designed with user requirements foremost in mind.  As you say, the way the system works is a reflection of the database architecture, not the way people think about things. 

I believe that you are very interested in facilitating compliance with FAA regulations.  It seems formalizing the list of flight "attributes" around the 14 CFR 61.51 list of required information is a good thing conceptually.

I am focused on both functionality and usability. Usability, of course, is a reflection of the UI.  As you say, the way the system works reflects the database architecture, and not the user's mindset.  Changing the UI so that the system works more like the way people think of things would make MyFlightBook more usable.  "Seamless" is a good word, I guess ... the seam between the user and the system is sometimes more visible than it should be.

There is also a specific suggestion above to enhance functionality.   I suggest you unify "core fields" and "properties" for the purpose of searching.  Then, a user could create and edit a (remembered) list of searchable attributes (unlike the current Search screen).   Doing this provides new flexibility/power for users, and  improves both usability and capability.

**Comment by ericberman** [comment]
Will be live when I next update the site.

**Comment by KayRJay** [comment]
Cool!
