### ISSUE TITLE
Bulk create pending flights from a zip of telemetry?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#558]

**Comment by KayRJay** [comment]
Nice feature.   I'm (pretty) sure it's not live yet, but I already (!!) have a couple of suggestions:

**Add Import Telemetry to Logbook menu**

It would be nice to make this feature more visible and convenient by adding it to the top level Logbook menu.  There's IMPORT there now.  You could have IMPORT FLIGHTS and IMPORT TELEMETRY.   

**Clarify the upload process**


Adding telemetry is done on [this page](https://myflightbook.com/logbook/Member/ImportTelemetry.aspx).   I've done that before, using several .CSV files.   Assuming that's the place to load a .ZIP file, perhaps the text should be revised.  (Also, it's not the "files" that are matched to an existing flight, but the telemetry data contained in them.)

Instead of

> Upload multiple telemetry files at once. MyFlightbook will try to match them to existing flights by date and location.

the text could read

>Upload multiple telemetry files at once (contained in .ZIP files or individual .CSV files). MyFlightbook will try to match the telemetry data to existing flights by date and location.

By the way, what happens if there is existing telemetry for a flight?  I'm too lazy to try it ...

No doubt you've already added text to the ["Learn More" page](https://myflightbook.com/logbook/Public/FlightDataKey.aspx) that describes uploading telemetry describing the new features (new formats, zip files).    

Two other small suggestions about that page ... change the title from "Uploading data for your flight" to something like "How to upload telemetry". 

Also, the link on that page to the Bulk Load Telemetry page is rather hidden, in small text and probably in the wrong place: 
<img width="550" alt="Screen Shot 2020-03-28 at 3 55 25 PM" src="https://user-images.githubusercontent.com/16978320/77834756-931e3c80-710c-11ea-9540-dee577fc2b0b.png">
The box around the text might make it a little more prominent than otherwise.  However, it seems more logical to put it right after the initial sentence on that page, rather than under "Known columns".

**Comment by ericberman** [comment]
This is actually live, and I put it into the playpen because I think - while it's kinda cool - it's a very minor feature, and can be somewhat fragile and wonky to work with.  Ditto matching telemetry to existing flights (which is why that one is also buried; you can really only find it from the FAQ or the link on the flight data key page).

I didn't bother supporting .ZIP for either of these, since the bulk upload lets you drag/drop multiple files anyhow; as a result, ZIP doesn't really buy you anything.

If you upload something and it matches a flight that already has data, I replace the data.

There's really nothing to add to the Learn More page.  I haven't added any new support for new telemetry formats.  The Learn More page describes what telemetry can look like in order to be understood; that's a discrete topic from how to attach telemetry to flights or create flights from telemetry, so it would be inappropriate to rename it "How to upload telemetry."  So you're quite right that this title is a bit misleading; I'll rename it to "Telemetry Data Description".

Ditto "Import Telemetry" - I'll reword as "Upload Telemetry to Existing Flights".  

And I agree with you that the placement is a bit odd.  Also notice that the IGC link no longer works, and that my verbage is wrong ("attach to a flights")

**Comment by KayRJay** [comment]
Well, I can understand that the creation of pending flights might be fragile/wonky.  But the regular .CSV feature, including bulk load/matching telemetry to existing flights, is "first class", right?

I tried loading a .CSV with a date that didn't match an existing flight.  MFB gave me an error, and didn't create a pending flight.  Should it do both? 

I didn't want to mess with telemetry for an existing flight to test it, so I have to ask: if there's an over-ride, do you give the user a chance to reject it?   Seems dangerous otherwise.

This feature isn't really hidden.    It's an easy trip from "Learn more ..." which I suspect anyone who ever wanted to upload telemetry followed.  

Why did you bother implementing .ZIP support if it doesn't buy you anything?  Seems a low priority then.


New formats?  What about #557 and #552?

As for the rest ... all really small stuff.   Thanks

**Comment by ericberman** [comment]
Creating pending flights isn't fragile/wonky at all - that's well-worn production code.  The two features that are getting conflated here (more below) - bulk attaching of telemetry to existing flights, and bulk creation of new flights from telemetry files - are fragile and wonky.  "Fragile" because bulk operations are inherently tricky due to the lack of interactivity, and "wonky" because this is a real corner case scenario.  

Here's a good litmus test for a wonky feature: if you have to explain to someone (who otherwise understands the usage of the app) the scenario about why they would want it - i.e., if you have to explain the problem to them in the first place - it's probably wonky.  The best way to handle wonky features is to make sure that - at the point that they realize that they need a solution to that problem - they can find it.  BOTH of these scenarios pass that litmus test in spades.

For usage: 

First, only 2% of flights have telemetry.

Of those flights, Probably 90% of this is done by the mobile apps, which generate the CSV.  Actually, just checked: it's approximately 95%.  And these are all uploaded as part of the flight entry.

The bulk of the rest is done on the web, one at a time, either by attaching the data when you create the flight or by attaching it to the flight.

So the scenario of "I have dozens of telemetry files" is indeed pretty rare (whether or not they correspond to already uploaded flights), and thus not even close to "first class".  The scenario of "I have dozens of these and they correspond to flights that I've already put into MyFlightbook" is a subset of this, and thus even rarer.  And the scenario that this issue addresses (creation of flights from telemetry) is rarer still - after all, who has all that flight data but hasn't been logging it in some manner?

Doing this manually, one at a time, is straightforward: go to the flight, click to attach the data, boom, you're done.

Doing this in a bulk process is indeed fragile: lots of things can go wrong, and by definition, bulk processes do not lend themselves to interactive error reporting and correction.  What if it doesn't parse?  what if I can't match it to a flight?  What if it could match to two or more flights?  

For all of these reasons, these are buried (or in the case of this issue, #558), specifically in the playpen.

There's one other reason to bury these: I pay for storage and have finite disk capacity on the main server, so while I'm fine with people using the telemetry feature, I have no incentive to encourage willy-nilly data - I pay for storage, and telemetry (for performance) is kept on the server's file system, which is finite.  If you're using the mobile app and recording telemetry - fantastic (and you're using my app).  So for this specific feature, I am currently actually tossing the data after I figure out the flight from it.  I may change that, but for now, I'm using the telemetry to create the flight and then not saving it.

(By the way, no, I don't warn before overwriting when you bulk-attach telemetry to existing flights, but odds of that being a problem are very low because - by definition - the telemetry had to parse successfully AND has to match date/time of the flight AND has to depart from within 5nm of the route on the existing flight.  Anything that meets that criteria can't be too destructive...).  

This feature and the attach-telemetry-to-flights are distinct features.  The attach-to-flights feature does NOT modify the content of any flight, it only attaches telemetry when available.  This feature does create flights, which means creating new flights (which i put into Pending flights).  They do different things.

I didn't bother implementing ZIP support in either case.  I can do it easily enough - I have all of the libraries  on the server to read zip.  But it is indeed additional work.  I can add it if enough people give me feedback that it's important.  But it really doesn't add much.

#557 and #552 aren't new formats.  They're CSV - but CSV doesn't have a schema so data can be represented in any number of different ways; these issues addressed adding more stuff to the data dictionary (and in the case of #557, rewriting Garmin's CSV because they have 3 lines of header nonsense instead of 1, which violates all of the norms of CSV).

**Comment by KayRJay** [comment]
It might have taken you longer to write your reply to me than implement the feature and make the minor text changes I suggest.  So, thanks.

I get why you don't want to encourage use of this feature.  So it's reasonable to not add the option to import telemetry to the Logbook menu.  

I do appreciate the explanation, and can't really disagree.  Here's my perspective.  I've only captured the telemetry during flight a few times.  I still feel I have a lot to do and don't need that distraction.   I didn't even think about uploading telemetry (one at a time or in bulk), until I saw your mention of FlightAware.  I was able then to go back and get my telemetry for some past flights, and upload it.  It's nice to be able to do that.  Maybe I'm a wonk.  But this feature works for me and is handy.

I guess there must have been some "itch" you needed to "scratch" ... to implement the ability to create pending flights from telemetry data.   When you do create a pending flight, since nothing else is recorded other than the date, it makes sense to discard the telemetry.   But I don't get the overall big picture purpose, especially since you say this feature is not that important or useful.

I'm confused, though.  Can you please explain when a pending flight is created?  I doctored a .CSV file, and didn't get a pending flight.  I was also confused by the title of this issue.  I saw the word "zip" and thought of ".ZIP".

I misunderstood about the .CSV formats.  I now infer (understand?) that your exhaustive list of known columns is how you interpret the data in the .CSV, which could be generated by several "vendors" or "generators" of the .CSV files. (Garmin and FlightAware among them, I guess).   So, I thought it was appropriate to list the "vendors".  Maybe not.

A somewhat related question:   I record a single day's lesson as one flight (sometimes with multiple airports).  FlightAware often sees the day as comprised of several point to point flights.  Do you know a good way to combine multiple flight tracks (in .CSVs) into one for the entire day?  I know I'll mess it up if I manually edit the .CSVs.

Thanks again.

**Comment by ericberman** [comment]
> When you do create a pending flight, since nothing else is recorded other than the date, it makes sense to discard the telemetry. 

Not true about "other than the date".  I'm doing autodetection - I pick up lots of stuff: times, route of flight, landings, etc.  Otherwise, the feature would be pretty pointless.  why create a bunch of flights with only date?

I did it because it's one of those things that every so often would be helpful to someone, and now (compared to a few years ago), I have all the pieces (autodetection, pending flights, etc.) that means it is simple to stitch together vs. a lot of new work.

My initial thought (and hence the title of this issue) was to use zip vs. individual telemetry files.  But I realized pretty quickly that zip didn't add any real value, so I didn't do it.

> I'm confused, though. Can you please explain when a pending flight is created?

A pending flight is created when you:
 * Explicitly save a pending flight (drop-arrow next to "Add Flight")
 * Bulk import flights and a flight has errors (the flights with errors become pending flights, "pending" you resolving the error)
 * Use this feature (from the playpen!) to create flights from telemetry.

Doctoring a CSV doesn't give you a pending flight.  A CSV is telemetry for a flight.  You can attach it to an existing flight, or you can use it to initialize a flight, but prior to this feature's functionality, there was no way to create a pending flight from it.  To create a pending flight, go to the playpen and do the "Bulk create flights from telemetry"

> I misunderstood about the .CSV formats. I now infer (understand?) that your exhaustive list of known columns is how you interpret the data in the .CSV, which could be generated by several "vendors" or "generators" of the .CSV files. (Garmin and FlightAware among them, I guess). So, I thought it was appropriate to list the "vendors". Maybe not.

CSV can be generated by anybody with access to a spreadsheet.  it is literally unbounded who can create what.  CSV simply means "Comma separated values"; it is nothing more than a text file that represents a table, with each row being a line of the text file and the "columns" being separated by commas (hence "Comma Separated Values" or "CSV") or semicolons (depending on your locale).  So it makes no sense to list vendors - it would be a literally unbounded list.

You can merge multiple flight tracks also in the playpen - there's a merge telemetry feature.

**Comment by ericberman** [comment]
Oh - note that merge telemetry does NOT produce CSV output; it can't.  It produces GPX output.  

Why can't it produce merged CSV?  Remember that CSV has NO SCHEMA.  So CSV1 might have columns A, B, and C, while CSV2 might have columns B, D, and E.  The only overlapping column is "B".  Sure, you could have blank values for A, D, and E where appropriate, but blank values may be meaningless or even an error condition when present.  (E.g., if you have a latitude column, you need to have a latitude for EVERY row).

GPX *does* have a schema.  So I parse to GPX and discard anything that isn't part of the GPX schema.
