### ISSUE TITLE
Include weekly data in the weekly flying status emails

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#588]
The current emails with "weekly flying status" actually include only information about currency and totals.  There's nothing "weekly" about it other than it is sent once a week.  I've not been flying lately (COVID, you know), so I get the same email every week (unless a currency has expired).

It would be a nice addition to add a section to this email containing a brief summary of recent flying.  Sure this information can be obtained by using a search and doing an ANALYSIS.   Having it done for me each week saves me the trouble.

A summary of "Recent Activity" could be fairly comprehensive without being too complete.  It could cover activity for the past week AND the current month (or trailing 30 days or something, whatever you like).   It could include the "core" items as defined by the FAA (and as discussed in issue #549) or a subset of such items.

Thinking about it, you could also include summary information about MyFlightBook as on the Home Page (and cover the same time periods as for the user's own data).  This might include 

- the number of flights
- number of pilots who added flights
- total flight time of those flights
- number of aircraft and models of aircraft added
- number of new airports
- number of airports visited across all pilots adding flights

 or any other statistics you think are interesting.

**Comment by ericberman** [comment]
Maybe could just list the flights for the past week/month?
If you're not flying due to covid, putting in the totals for the past week/month is also not going to change from week to week.  Indeed all that's going to happen is that your currency will indeed fade.  

I can't include the chart - that's all javascript, relies on a browser.  

But I think adding some more information isn't a bad idea.  Just gotta figure out what.  The monthly mail includes the stats year-to-date (or previous year, on Jan 1); perhaps I could include that on each mail?

**Comment by KayRJay** [comment]
A list of recent flights is too much detail, and is very easily gotten from MFB itself.   The intention, I think, of the weekly and monthly emails is to summarize activity, not display it. 

The current monthly email includes four groups of information
- currency
- current month
- year to date totals
- flight stats and achievements

The weekly summary includes 
- currency (in a very slightly different format)
- grand (all-time) totals

I'm not sure why the weekly emails include all-time summaries and the monthly do not, and vice-versa re YTD totals.  There's little reason for these emails to have different information or formats.   A suitable format applies for both the weekly and monthly summaries.   You wouldn't even need to send a monthly summary if the weekly summary included both the prior month and current month to date.  (In that case, the user could select either weekly or monthly ... no need for both.)

The display could be more compact and include only the information a user wants.   Here's a suggestion:
- always include certain info (days flown, # flights, # landings, say)
- include attributes from a user-specified or default template
- suppress zero-value totals (as no doubt you do now)
- permit on/off options of what to include:
    - totals by category / class
    - totals by aircraft
    - totals by model
    - totals by role (student, PIC, instructor, solo ...)
    - currencies
    - achievements

These selections, naturally, would be associated with the user's Preferences.

The display could include all the relevant info, in a compact tabular form.  For me, I'd use the Student VFR Private Pilot - Pre solo template, and turn on only "totals by aircraft", leaving the others off. It would look like this, weekly:

<img width="430" alt="Screen Shot 2020-04-26 at 6 09 18 PM" src="https://user-images.githubusercontent.com/16978320/80323547-5025b680-87e9-11ea-859a-2ce8023ae6f1.png">

**Comment by ericberman** [comment]
The weekly and monthly details differ in what they include because they serve (slightly) different purposes.  Weekly is just that - every week, just keeping in touch and keeping you up-to-date with current information - "here's where you are, RIGHT NOW, w.r.t. currency and totals".  Monthly is in addition to weekly and is a point where it makes sense to summarize stuff to date, hence the "prior month" and "ytd" totals/achievements.  Monthly is intended to be more of a summary and report, where weekly is more of a "hey, just letting you know where you are".  (Currency, of course, is not subject to any time period and is - by definition - identical between the two reports)  Sorta the difference between (in a corporate environment) looking at the financials each day vs. the end-of-quarter numbers you report to the street.

I suppose I could change these so that they are identical reports and the only difference is the frequency with which they are sent out (7 days vs. 1st of each month), but I chose not to do that originally for the simple reason that nobody seems to need a weekly report, but many people do need to know monthly stats.  (Also, if these were identical reports, then I'd need to make weekly/monthly mutually exclusive to prevent spamming people with two identical reports on the same day.)

So as I think about it, it probably makes sense to **remove** currency from the monthly email, making it more of a "report" and distinguishing it more from (and thus making it more complementary to) the weekly report.

I'm pretty loathe to add too much customization to the email.  KISS.  You can get all sorts of information by clicking through to the website.  I can't figure out the scenario where the totals you want to see in email are different from the totals you want to see on the website.  This is an engagement/marketing tool - present useful information at a glance.

**Comment by ericberman** [comment]
Just tried looking at weekly vs. monthly where monthly didn't have currency.  I think it needs currency, especially if you do monthly and not weekly.  But they really are intended to be complementary emails, with weekly being more of a "current status snapshot" and monthly being more of a report.

**Comment by KayRJay** [comment]
I think the distinction  you're making is very slight indeed.    The format above (showing past 7 days, prior month, current month to date, and year to date), really covers the timeframes users might be interested in for these reports.   I can understand your original thinking here, but the difference between monthly and weekly reports is pretty subtle other than their frequency.   

The distinction between the content and purpose of weekly vs monthly reports is certainly not obvious to users.  There's no description of the types of email notifications on the Preferences page.  All a user does is choose the frequency of getting email notifications :

<img width="508" alt="image" src="https://user-images.githubusercontent.com/16978320/80408684-d80cce80-8884-11ea-819b-6229c4202127.png">

> I suppose I could change these so that they are identical reports and the only difference is the frequency with which they are sent out (7 days vs. 1st of each month), but I chose not to do that originally for the simple reason that nobody seems to need a weekly report, but many people do need to know monthly stats.

If people don't need or want the Monday reports, they can opt to only get the monthly ones.  But, if you provided some customization, some people might find weekly reports more valuable.

>(Also, if these were identical reports, then I'd need to make weekly/monthly mutually exclusive to prevent spamming people with two identical reports on the same day.)

Well, since the first of the month is a [Monday only sometimes](https://www.timeanddate.com/calendar/weekday-monday-1), it's pretty easy to decide send only one report on first of the month when it is a Monday (just the monthly one, but again, they be identical!).  

On those occasions when the first of the month IS a Monday, it would be reasonable to report the prior two months rather than the prior month and the new month to date.  (So, come June 1, you'd report April and May totals, not June to date.)

As to whether currencies (or achievements, for that matter) are included in the report, wouldn't it be best just to allow the user to specify which he wants, if either or both? 

> I'm pretty loathe to add too much customization to the email. KISS. You can get all sorts of information by clicking through to the website. I can't figure out the scenario where the totals you want to see in email are different from the totals you want to see on the website.

I understand the KISS principle.  And, perhaps it is overkill to support templates for this feature.  On the other and, you've already implemented templates, which support different user types, different scenarios, different stages of a pilot's career.   This is just another, somewhat natural, use of templates.

Isn't the reason for templates exactly because users have different needs?   Perhaps the opposite of KISS is TEHO (to each his own).

Sometimes users will want to see different things (e.g., report by aircraft or by role, for example).  Sure, for any given interest, a user could go to the website and issue a query.   But I'm suggesting customization to make it easier for a user to get what he wants with minimal or no effort.

Now, if you were to say that "it's just too much work" or "it doesn't provide significant benefit to users",  that's an entirely different argument to make, and I can't judge that.   This is a reasonable case to make, and certainly could apply to  the notion of presenting summary information about MyFlightBook overall, as suggested above.

>This is an engagement/marketing tool - present useful information at a glance.

That is certainly a reasonable reason fro have these emails (in addition to their utility to users).  But, the more customizable and usable, the deeper the engagement.   This is actually true throughout MyFlightBook.  The less you support customization, the looser the tie to your user.  The more the product (or this or any other feature) meets the needs of a specific user, the less likely the user is to migrate to another product.
 
A final comment: by changing the format to include several recent periods, you'd provide a glimpse into recent trends.  A user could see whether his activity is increasing or decreasing month-to-month, for example.   Also, the format I suggest is much more compact and easier to read/scan than the present format, which requires at least one line for only one or two numbers.  Again, having the report provide **useful** information that is easy to digest increases user satisfaction and engagement/stickiness. 

I make these suggestions to improve the functionality of MyFlightBook, make it easier to user and make it even more competitive vs. alternatives, and  increase user satisfaction and engagement.  I'm happy to be a source of ideas, even if you don't have time or don't consider them important or for any other reason don't want to implement them.

**Comment by ericberman** [comment]
So I guess I'm hearing two distinct feature requests here:
(a) have only email and give it greater customization, and (b) set the frequency with which it's sent.  But the monthly mail and the weekly email would be identical except for delivery date.

**Comment by KayRJay** [comment]
Yes, and 

(c)  improve the format, so it is more compact and at the same time includes more information.

Thanks for listening!

**Comment by ericberman** [comment]
So playing with this a little bit; I like the idea of a table with different time periods.  Interesting issue (solved) of how to collate when a total doesn't exist in a narrow time period but does in the all-time one.  

There's a minor problem of what to do with the subdescription text (e.g., "14 landings (11 day, 3 night)" - when doing multiple totals, that makes the columns really wide.  I think I'll strip those in email.

But I realized why the monthly email and the weekly must be at least a little different: "this month" and "year to date" are ridiculous on the mail that's sent out just after midnight on the first of the month or on Jan 1 (respectively) because in both cases they're always completely empty.  So it makes all the sense in the world to strip those from monthly mail.

**Comment by KayRJay** [comment]
Thanks for working on this.  I do appreciate that you took (some of) my arguments to heart.  And I appreciate that there are ALWAYS some subtleties that I wasn't considering (e.g., the formatting of columns with lots of text).

I'm not an expert in what's needed to code the formatting, but the following idea might help.  Include, for landings, three numbers under each time period, but have the label indicate what they mean, like this:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/16978320/80432988-ebcf2980-88b2-11ea-9759-035dcf64f169.png">
No need then for the five different columns to have a lot of (repeated) text.  

> "this month" and "year to date" are ridiculous on the mail that's sent out just after midnight on the first of the month or on Jan 1 (respectively) because in both cases they're always completely empty. So it makes all the sense in the world to strip those from monthly mail.

Actually, it's not necessary to have two different message types and different formats for the monthly vs. weekly notifications.   You can use the same format for **all** notifications, but slightly change the period of time for which you report totals in notifications sent on the first of the month.   

After all, there is likely history prior to Jan 1 or the first of any month.   On the first of month other than January, the user wants to know about the totals for the previous month as well as YTD.  On the first of the year, the user wants to know about the previous month and the previous year.   January 1 is a great time to know the prior year's total.  If you leave it out, there's never a monthly report that captures an entire year.

- On January 1, you would report totals for November, December and the Prior Year.  
- On the first of every month other than January, you report the two previous months, and Year-to-Date.  

My example above shows what you'd do for June 1, which happens to the only time in 2020 that the first of the month is on a Monday.  The June 8 report would replace April with May, and May with Month to Date. 

It is helpful to have the totals for the entire prior month as well as the current month to date in the report.  That way a user can tell if he's tracking recent activity in the middle of a month.   Less valuable would be to include the prior year as well as YTD,  but possibly interesting for the same reason.

By the way, with a single message format, you can change the email message subject line and header within the message body. Instead of 
```
Subject: Your weekly flying status
Header: Your weekly stats from MyFlightbook
```
and
```
Subject: Your flying totals for March
Header: Your monthly flying report from MyFlightbook
```
you could have these:
```
Subject: MyFlightBook Flight Activity and Status as of April 1, 2020
Header: Your flying activity and status as of April 1, 2020
```

**Comment by ericberman** [comment]
Right, that's actually exactly what I do today anyhow.  The main difference between the monthly/weekly emails is already the "1st of the month or 1st of the year" behavior; in the current scenario, I show multiple totals section, in the proposed new model, I'd show/hide different columns of a unified totals.  But it's the same basic principle.

For Jan 1 I'd only report December (the prior month) and prior year.  Not sure why I'd show November - no other report shows "2 months prior to this one).

**Comment by KayRJay** [comment]
The reason to show two prior months is so you have a month-to-month comparison.   On a day other than the first, you would have the prior month and the month-to-date.  Allows the user to see how closely his current month activity matches the prior month.

Not the most important thing, but it is nice to see the trend ...

**Comment by ericberman** [comment]
Here are some screenshots of what this looks like.  Note that because I am now displaying multiple totals for each label, it is now the total value that is hyperlinked, not the label.

For weekly mail, it is this:
![image](https://user-images.githubusercontent.com/16455286/80517435-ed900000-8939-11ea-91fc-3310f7cecf69.png)

For monthly mail Feb thru Dec, it looks like this:
![image](https://user-images.githubusercontent.com/16455286/80517503-0a2c3800-893a-11ea-96d8-cc5dfb0664c3.png)
Note that (a) "last 7 days" is gone because this is asynchronous from the weekly mail (where 7 days makes sense) - e.g., if you simply requested monthly frequency, then monthly is the granularity you probably want, and (b) month-to-date is gone (since by definition this is always 0, as this mail is sent out shortly after midnight on the 1st of each month)

For the Jan 1 email, it looks like this ("Mar 2020" would be "Dec 2019"; it says March because right now is April and that's the prior month right now)
![image](https://user-images.githubusercontent.com/16455286/80517712-537c8780-893a-11ea-90f8-b936d1793d3c.png)
Similar to the monthly email, except that it has further dropped year-to-date, which is also (by definition) 0 in the early morning hours of Jan 1.

The "Recent Achievements" section is always included, and is always year-to-date except on Jan 1 when it is prior year.

So the format of the email is now basically the same across all of the mailings.

I don't think I'm going to add site-wide statistics; I want to keep the email personalized.  I also do not think I'm going to add a whole lot of customization here - I don't think the value-provided-to-work-ratio is there; Currency and Totals are (by far) the two things that are most important "news" to keep track of on a regular basis, whether you are or are not flying.

What I *might* do, however, is pull this striped totals thing into the website somewhere as a report...

**Comment by KayRJay** [comment]
Nicely done.  I do understand the decisions re site-wide statistics and customization.   

See new issues #589 and #590 for some related ideas.
