### ISSUE TITLE
Create a pending flight when bulk uploading telemetry

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#607]
I lent my plane to my CFI, and he took 6 flights over a few days.  I downloaded the telemetry from Flightaware.  I did not individually enter the flights, so there were non-matches when I tried the buklk upload.  

It would be nice to create pending flights when telemetry doesn't match, so I could more easily create flights for them based on the telemetry data.

**Comment by ericberman** [comment]
You mean like this?  https://myflightbook.com/logbook/playpen/BulkImportFromTelemetry.aspx

**Comment by KayRJay** [comment]
Yeah … maybe it’s time to move that from the playpen!   Seems like a nice feature.

**Comment by KayRJay** [comment]
Question: why does a pending flight created from an uploaded telemetry file have only the departure airport, and not a complete route?

**Comment by ericberman** [comment]
It all depends on the telemetry and what I detect.  If I don't detect a landing at a different airport, I don't append it.  

Are you asking about the flightaware data?  If so, in taking a cursory glance at it:
 * First of all, it contains no speed data, so I'm deriving it, and it's very low resolution.  See my earlier complaints about KML.  It can contain - or not contain - whatever data it wants, in more or less any order, and can contain multiple segments with no indication of which one I should pay attention to.
 * Nevertheless, I see a derived speed that goes up to a flying speed - so that's a takeoff at KHCR.  At 9:48:14 PM there is a sample with a derived speed (probably an error) of 31kts, so that could possibly be registering a landing, but the nearest airport to that coordinate is...KHCR.  (That part of Utah doesn't have a ton of airports).  And then there's the final coordinate, which is...at KHCR.  And when I append an airport to the route, I avoid duplicates (that way if you're doing touch-and-go's, you don't get KHCR KHCR KHCR KHCR...)

**Comment by KayRJay** [comment]
I guess that all makes sense.  But at this stage of my (very long!) training, a majority of my flights are indeed KHCR-KCHR.   It's good that you don't include all the touch and go's but it does seem odd to have only a takeoff and not a landing.  I certainly hope never to have that situation in real life: I want the same number of landings as takeoffs!

**Comment by ericberman** [comment]
I've never bothered including takeoffs in autofill other than night takeoffs.  There are so many, and most pilots never bother recording takeoffs (except night, and even those I allow night currency with just landings and give a warning if I find no night takeoffs).

**Comment by KayRJay** [comment]
Really?  I would think every route began with a takeoff.  Why wouldn't that be something users record?

**Comment by ericberman** [comment]
I think the fact that pretty much every flight begins with a takeoff is why - it's kinda obvious you did a takeoff on most flights.  And generally getting airborne is no big deal; getting back down is what's hard.  Look at most paper logbooks, they don't bother having columns for them.  There's a gajillion things you can log, nobody logs them all.  Technically, for 61.57(a), you do need to perform both takeoffs AND landings, but the takeoff is often just assumed.

**Comment by ericberman** [comment]
I'm going to close this issue for now; if/when there's demand for bulk telemetry import, it's certainly easy to expose, but for now I think the playpen is fine for it.

**Comment by KayRJay** [comment]
Sure, it’s certainly not critical, but would help me.  I can use it from the playpen.

Re takeoff and landing airports:with only one airport listed, of course you can’t tell if it us a TO or landing airport.  Makes queries for “landings at airport xxx” inaccurate, but I guess that’s not too big a problem.

**Comment by ericberman** [comment]
You absolutely can tell.  One airport = "it was both TO and Landing airport".
KABC = You took off and landed at KABC
KABC-KABC - same thing
KABC-KDEF - you took off from KABC and arrived at KDEF
and so forth.  The first element in the is the takeoff airport, the last item (which could also be the first, if only one item) is the landing airport.  Completely unambiguous

**Comment by KayRJay** [comment]
Ok, then.  Thanks
