### ISSUE TITLE
Minor suggestions for telemetry Raw Data display on Flight Details Page

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#617]
The "Computed speed" is displayed to a level of precision that is beyond reasonable.   it doesn't seem more than one decimal digit is necessary (or useful).

I'm guessing that speed is displayed in knots.  It would be nice if the user could select other formats (mph, kph, knots, mach).

Also, it might be nice to give the user the choice to display lat/long in degreed and minutes too.  I note that AC-U-KWIK uses degrees and minutes.

I don't know if it's ever useful to report altitude in meters (I believe Russia recently converted to using feet).  Would FL be a reasonable display format?   How about reporting altitude in feet as 1,234 (with the comma)?

Might it be useful too, to be able to change the date/time from Zulu to Local (inferred from the lat/long and the date re daylight time)?  And include Z or the time zone in the displayed time.

There's no legend for the column headings, so I don't know what "Time/Kind" is, or if it would be useful to display it in a different "Time" or "Kind"?

Putting that all together, perhaps changing 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/16978320/83983423-8e83ba80-a8eb-11ea-92c5-5f959445c407.png">

to something like this would be helpful (where the drop-downs would be how the user selected the appropriate display option).

<img width="704" alt="image" src="https://user-images.githubusercontent.com/16978320/83983635-436aa700-a8ed-11ea-9936-f779542bcd64.png">

**Comment by ericberman** [comment]
This data table shows full precision - it is showing whatever was in the original table.  (That's why it's called "Raw" data).  For many of these fields, I have no idea what the data is other than data type (integer, timestamp, etc.).  Most of what follows is due to the point of this being about inspecting the raw data.

I also don't know - and usually can't assume - anything about the units of the data (other, obviously, than latitude/longitude).  Fuel flow could be gallons per hour, lbs per hour, liters per minute, or whatever.  Yes, my computed speed is in kts, but a declared speed that isn't in GPX or KML (which have specific schema) can be in m/s, kts, mph, km/h, or ???, and for the most part I have no way to tell.  That's actually why if you click on download and want to convert to GPX/KML (which require m/s), I need you to tell me the original units (unless the original file was GPX/KML); otherwise, I have no idea how to do the conversion.

I do display in degree/minute if the original format is deg/min.  (again, "Raw" data.)  E.g., here's data from my old GPS from a flight in 2010; note that it doesn't have separate Lat/Lon columns, it has a "Position" column:
![image](https://user-images.githubusercontent.com/16455286/83984373-beca5980-a8e9-11ea-9841-489e32fb7437.png)

People absolutely do use meters for altitude; mostly outside of the US.  (GPX and KML use meters internally as well).  But CSV it's a separate ballgame.

I can't convert from lat/lon to local time.  That's an expensive real-time service, because you need a massive data set, kept up to date, that knows where all of the timezone boundaries are and when they do daylight time and when they switch (and when they change the rules about when they switch...)

I do have a dictionary of the columns that I do know about (but I'll display); click here:
![image](https://user-images.githubusercontent.com/16455286/83984483-4748fa00-a8ea-11ea-8210-54c045e2b3f1.png)

**Comment by ericberman** [comment]
Just looked at the code I use for the raw data table.  It's basically the pushpin column (the "zoom in" links above), followed by the raw data.  This code is completely divorced from anything that knows anything about schemas - it is literally seeing a table of columns and values and displaying them with 0 semantic knowledge, so it's even including columns that aren't in my data dictionary.

I'm going to won't fix this - raw data is raw data; it displays raw.  And displaying "cleaned up raw data" ranges in difficulty from "hard" to "impossible".

**Comment by KayRJay** [comment]
Ok, and I don't question the reasons for leaving it as it is.  I'm just presenting a user perspective, rather than the implementor's view ...

Certainly don't want you to do the impossible (which my boss used to say only took a little longer), but the "hard" or "difficult", well ... that's doable!
