### ISSUE TITLE
Suggestion: weekly and other summaries group labels are unclear and should include number of flights

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#684]
The weekly and monthly summaries include lots of “totals”, most of which are aggregate (sum of) times.  One category, “Other totals” includes both “total times” and “total number” or “total count”.   The labels of the various sections of the weekly summary are not consistent or particularly clear:

- Totals by Category/Class
- Times by aircraft features
- Standard Logbook Times
- Other Totals
- Overall Total Flight Time

Something like this would be an improvement:

- Totals Times by Category/Class
- Total Times by Aircraft Features
- Totals of Standard Logbook Times
- Summary of Flights and Landings [by Property (or description)]
- Total Overall Flight Time

Note a bit more consistency in capitalization.  The word “Summary” covers both types of “totals” (times and count).

Two very basic pieces of information seem to be missing ... the number (count) of flights in the relevant period (across all “properties”) and the number (count) of landings.  These probably ought to be the first two entries under “Summary of Flights and Landings”.

These comments also apply to Logbook > Totals.

**Comment by ericberman** [comment]
All makes sense.  I'll make a code check-in momentarily.

A few slight differences from your suggestion:
 * After looking at it, the word "Totals" is redundant in most cases.  So I just say "Times by Category/Class", etc.   In that vein, "Other totals" is now "Other Times and Counts"
 * Adding # of matching flights is a nice idea.  On the website, of course, it's already shown just below (and to the left) of the totals, but this way you have it on the mobile apps and in email.  Since it's the same code that does Rollup By Time, it also shows flights in those time periods.  I put this into the "Overall" section.
 * I didn't do anything regarding landings, since those are already displayed as sub-level breakdowns in both in the overall totals and in the category/class or model breakdowns.  I don't think it makes sense to break them out as top-level totals because it ends up more than doubling the number of these kinds of totals - you need it for landings, full-stop day landings, full-stop night landings, and approaches; for that reason, I'm confident that pairing them with the group remains the right call.  I assume this is addressing your proposed "Summary of flights and landings?"

**Comment by ericberman** [comment]
Here's what I mean about landings/approaches.  Note how they're tied to category/class (or model, if you choose that option), and how there can be up to 4 numbers per.
![landingsapproaches](https://user-images.githubusercontent.com/16455286/96186630-9504ed00-0ef0-11eb-86f4-08d0b14cc83d.png)

**Comment by KayRJay** [comment]
Thanks for responding so quickly.   Just a few parting comments ....

The word "Totals" is not "redundant" (meaning duplicative, as it would not be duplicating anything).  It may not be necessary, but I think it is helpful.   The word "Times" by itself to me doesn't necessarily imply summation.  Rather, it indicates essentially a list of specific times (from individual flights).   Of course these are summaries, so I wouldn't expect to see a list of several flight times.   

In fact, neither "Times" nor "Counts' is actually necessary.   "Total times" and "Total counts" make sense, but just using "Totals" would be perhaps better.  It is obvious when a number is a sum of times or a sum of counts.  As in ...

- Totals by Category/Class
- Totals by Aircraft Features
- Totals of Standard Logbook Times
- Other Totals
- Overall Totals

This whole topic is only a small semantic issue, and doesn't really matter.

I understand your comments re landings.

Thanks for adding number of flights.
