### ISSUE TITLE
Currency symbol is not visible

### ISSUE THREAD

**Issue by FredSau** [ericberman/MyFlightbookWeb#688]
Hello,
I've just change my home computer.
Old one (windows) was configured in French (Belgium), and I've saw de € symbol
New one (still windows) but in English. And I don(t see any valid currency symbol.
Probably not a big problem, but if you have a solution ...
KR.
Fred.
![2020-11-08 16_21_05-Greenshot](https://user-images.githubusercontent.com/28922490/98469230-915a4280-21de-11eb-93ff-b30b067829c6.png)
![2020-11-08 16_22_41-Greenshot](https://user-images.githubusercontent.com/28922490/98469254-afc03e00-21de-11eb-821a-9ec6723cee16.png)

**Comment by ericberman** [comment]
I think the issue is that your English locale is "English" without a region.  I.e., "en" rather than, say, "en-us" (English / United States) or "en-gb" (English / United Kingdom).  I get the exact same behavior if I choose vanilla "en", but if I include a region, I get a $ (USA) or £ (UK).  

This is by design.  I ask the system to format monetary values using the current region conventions, but the system it doesn't know the region, so it therefore doesn't know things like which currency symbol to use, whether to use a comma or a space for thousands separators, comma or period for decimal separators, day/month/year vs. month/day/year, etc.

I'd suggest you add a region.  "en-ie" (English/Ireland) might be a good choice, since Ireland is on the Euro.  https://myflightbookblog.blogspot.com/2019/05/international-functionality-part-2.html has instructions for how to change this in chrome and firefox (other browsers work in similar manners).

**Comment by FredSau** [comment]
Hello Eric,

Yes it's a solution, but for me it's just a workaround.
Why, because Chrome (it's the browser I use) doesn't have a "language"
which permit English and Euro (as you've written we don't have an
"English-Ireland").
But, it's like that. I've set Chrome in English UK. I have a £ and not a €
but ok because I prefer to have an English interface.

Thanks for your help
KR

Fred

Le dim. 8 nov. 2020 à 18:33, Eric Berman <notifications@github.com> a
écrit :
