### ISSUE TITLE
Support to permanent hide check flight warnings for individual flights

### ISSUE THREAD

**Issue by fkrauthan** [ericberman/MyFlightbookWeb#751]
I was wondering if there is any possibility to implement a feature where some of the warnings for individual flights could be marked as "reviews and ok" so they don't show up every time I use that feature.

In my case I do have a couple of flights where the warning in itself makes sense but because of the nature of that particular log entries are not applicable.

**Comment by ericberman** [comment]
That's why these are warnings and not errors. :)  

I think going to the level of individual warnings for individual flights would be an extraordinary amount of work (I'd need to define a unique ID for each possible warning so that I could suppress exactly that warning while allowing others through), and then I'd need to track all the suppressed warnings.  But perhaps much simpler is to say "I've reviewed this flight" and suppress ALL warnings for that flight.  Any edit to the flight would reset that flag.

**Comment by fkrauthan** [comment]
Yeah that was kind of my thought having a flag that resets on any change to a flight. I just see this list growing over time and it will take longer and longer to review (unless I remember when I did it the last time and adjust the date range filter). So a simple suppress all warnings for this flight (that auto clears when I edit the flight) would be perfect.

**Comment by ericberman** [comment]
Just turning my attention to this and I remembered: it already remembers the date of the last flight check, so you can with a simple click on the gray arrow only check flights since then (i.e., only newly added flights).  Doesn't that effectively address this?
![image](https://user-images.githubusercontent.com/16455286/113594561-b9629c00-95ec-11eb-80c3-e64fa26524f6.png)

**Comment by fkrauthan** [comment]
Oh I didn't realize that. It definitely would work as a workaround. I still think having the capability to mark individual flights as verified till a edit is made would be a great addition.

**Comment by ericberman** [comment]
OK, I think I have a total hack that will work for this: I'm going to try appending like 8 spaces to the route.  If I see the 8 spaces, I'll skip that flight in check flights.  Saving the flight will always trim whitespace.  Alternatively, append some other invisible character (tab, perhaps? &emsp14;?  https://en.wikipedia.org/wiki/Whitespace_character has some possibilities...)

It's a total hack, but there's a method to the madness:
 * I don't want to add a new column to the flights table.  This is going to be insanely sparse data, and with over 10M flights, that's an awful lot of "false" to store for the occasional "true"
 * I don't really want to put it into a separate table or into your preferences bag because then keeping it in sync with the flights table (i.e., removing it from over there when you make an edit to a flight over here) is fragile.  Can do that at the database level more reliably, but then it's an extra join and/or an extra database operation every time you save a flight.  Absolutely not worth burdening that path.
 * Spaces, obviously, won't display, and HTML collapses multiple spaces into one.
 * The route field is excluded from validity checks on signed flights, so I can tag it on there without invalidating a signature.

I do need to make sure this hack wouldn't impact the mobile apps (which aren't html based).  But otherwise, this might be a convenient way to flag a given flight as having been reviewed without having to muck with schemas or extra table joins.

**Comment by fkrauthan** [comment]
Sounds like a possibility. Even though I personally probably would just add that additional column. I understand that in most cases it will be false but that extra byte shouldn't really cause that much trouble. You can even make it nullable so only if it is set to `true` it is marked as manual reviewed that might save you a bit of space (not 100% sure how the DB is handling `null` vs `false` but just another thought. This way you don't run risk that down the road people forget about this and break it or build clients that don't expect that behaviour in some cases.

But speaking of data storage (somewhat related) have you ever considered moving to a NoSQL database. I feel like a configurable log book is a perfect example where the strict table schema is not fully working. I know its a really big task to migrate but might be something worth considering down the road?

**Comment by ericberman** [comment]
Ummm...what problem would NoSQL solve?  What's the matter with a strict table schema?  Strict table schemas make for pretty powerful queries...  And columns add a bit of memory every where that you load flights, it's a bit more data to pass back and forth, etc.

Do note that the flight table proper actually doesn't nearly as many columns as you might expect - pretty much just the core stuff that really do vary from flight to flight.  With tens of millions of rows, I both want it relatively lean and if a value is identical for 99+% of the flights, it probably doesn't belong in the table.  That's why I have properties - over 700 of them, without having the flights table store them directly.  That's a simple table join.

**Comment by fkrauthan** [comment]
Exactly your concern that in 10M records only a fraction would need that flag. In NoSQL for example this flag would only take space if it's actually used. And yes in case of NoSQL each property could be stored on the flight itself saving the join. Again not saying that the current approach is wrong or does not work. But Document based databases are developed exactly with the use-case in mind that you might have the same Type (e.g. a Flight Log Entry) but they have slightly different schemas depending on there need.

**Comment by ericberman** [comment]
Ahh, but I have a common schema, it's just sparsely populated.  Does that make a difference?
I think MySQL is pretty efficient about null/default values, but it takes a bunch of space as well in dumps for data restore which I do every other day.

**Comment by fkrauthan** [comment]
Like with anything there are no fixed rules but in my experience when I worked with NoSQL I usually did it the following way:

I have a base schema that I always populate (e.g. minimum fields to display) and then depending on the use-case I store additional fields. In my entities within the code all fields can be there (but I for example just disable saving null values or in NodeJS just don't set them). Therefore my database contains a fixed set of base fields but I only store extra attributes and flags if they are really required for that particular entry.

You can even go as far as pre calculating all the values (number of takeoffs/landings day/night etc) and on a preference change re-calculate that as storing data in a NoSQL db usually is dead cheap and reading is super fast. And databases like MongoDB have pretty good aggregate features that can take full blown JS functions (if needed) to calculate totals etc (which can be handy for currency checks and totals).

But yes it definitely isn't an easy replace and would require a big rewrite of the backend and probably an even bigger data migration (so might not be worth it to save a little bit of data and potentially have a slightly higher performance). Was just a thought.

But since you use MySQL if you create a new table with a join could you not just use a TRIGGER to ether clear the flag or delete that record?

**Comment by ericberman** [comment]
I also avoid updating the table because...at 10M+ rows, the simple act of modifying the table can lock things for a while.  I do it if I need to, but it's been a long time that I've been able to avoid it.  (So that schema has been pretty stable).

I actually had also thought about using a property to indicate "Ignored".  No database change at all there - I'd mark the property as "no print", and attach it or remove it.  Involves (slightly) more database writes, though, but more importantly can invalidate a signed flight (since properties are included in that validation).

Another way I had considered was putting a bag of flight ID's to ignore into your profile preferences.  That would work just fine (and your profile preferences are unstructured - literally a JSON dictionary of data).  But then you have to make sure you catch all of the places where a flight can be deleted or modified and make sure to refresh the ignored flight ID's and...that's a super tangled mess.

**Comment by ericberman** [comment]
Yeah, I guess I don't think of this feature as rising to the level of requiring a new table.

**Comment by fkrauthan** [comment]
Hmm yeah that totally makes sense. Can you exclude properties (or easily add a feature to exclude certain properties) from invalidating signed flights? Since a no print property would actually be from a user perspective the best as when you pull up the flight you would be able to manual remove that flag (if for some reason you need to) and you have a clear indicator that this flight is currently excluded from flight status validation.

**Comment by ericberman** [comment]
I can do that, but it's just more code.  That's what I love about this hack - it's simple, it's isolated (touches very little code), and I just tested that it works on the mobile apps.  I'm using the six-per-em space (\u2006).  It's whitespace (so Trim() handles it), it's one-sixth of an em wide (so even if it displays, it's negligible), and who the heck uses it deliberately?

**Comment by fkrauthan** [comment]
Nice. And the route display (and calculations) etc does a trim before splitting it and displaying the waypoints or is that an area of concern?

**Comment by ericberman** [comment]
yep, but good idea for me to test that too.  But yes - it breaks on regex alphanumeric boundaries, so I'd be surprised if that breaks.

**Comment by ericberman** [comment]
Yep, just tested, works fine on iOS and Android.  It's just whitespace...

But found another issue: if you only check flights since date d, it still checks all flights but only shows issues for flights after date d.  As a result, it says it checked X flights (X = all of your flights), even if it's only showing you the issues for flights after d.  I am changing it to only bother checking the flights after that date, though this could potentially lead to a false positive or two (since some of the checks I do around things like duty periods span multiple flights).  I think I'll live with that - if you only said to check those flights, you only intended those flights...

**Comment by ericberman** [comment]
Code checked in, will go out this week (maybe tomorrow?)

**Comment by fkrauthan** [comment]
Nice thank you so much getting on it so quickly.
