### ISSUE TITLE
Feature request: calculate MSL altitude from GPS altitude

### ISSUE THREAD

**Issue by Murleen** [ericberman/MyFlightbookWeb#790]
I use the Android myFlightbook app to log flights, but the altitude logged is against the WGS84 ellipsoid, which in my local area is ~151ft below MSL. It would be good if the website could include ALTMSL as a generated column when GPS altitude is present, for example using the EGM2008 data set.

**Comment by ericberman** [comment]
Hi, Murleen.  How would I do that?  I just get a number from the GPS that is the altitude (typically in meters), but I have no information about how it was computed or against what data set it is.  I am not sure I have the means to convert from one to the other even if I knew.  Suggestions?

**Comment by Murleen** [comment]
The Android location API specifies that altitude values are in meters over the WGS84 ellipsoid: https://developer.android.com/reference/android/location/Location#getAltitude() (I don't know how iOS is specified)

I'm not an expert, but I think to convert to an MSL altitude, a geoid dataset is used. EGM2008 appears to be the general standard global geoid dataset, and is basically an array of correction values indexed by lat/lon - the reference data is at https://earth-info.nga.mil/, or there seem to be TIFF bitmaps of this data at https://www.agisoft.com/downloads/geoids/. To do the conversion I think it's a case of using the specified lat/lon values to get an interpolated datapoint from the geoid bitmap, then applying that to the GPS altitude. The datasets seem pretty big, so this might be better done server-side rather than in the apps (although I don't know how much accuracy is needed, it might be possible to decimate the dataset somewhat).

**Comment by ericberman** [comment]
Looks like iOS is MSL - see https://developer.apple.com/forums/thread/125281.  And, of course, I support a wide variety of other sources (GPX, KML, NMEA, CSV exports from your aircraft's systems - so it could be pressure altitude, could be barometric altitude, could be flight-level altitude...,, etc.)  So this is all not only without reference to a specific datum, but it is also unitless (could be feet, meters, inches, smoots - I can't tell).  I.e., I treat all of this as "numbers."

Which does, by the way, beg the question: what problem is being solved here?  I'm not entirely sure the consequence of altitude being off from MSL by 151ft.  That's a pretty small amount...  I'd love to understand the scenario where that difference matters..

There are only two real options:
a) Implement something android specific, because then I know I'm dealing with WGS84 in meters.  I could use the earth-info.nga.mil data, I suppose, to do a rough correction (though it's a huge data set and would explode the size of the app - like by 10x or more!)
b) Offer a conversion feature on the website where you specify input units and reference and can convert to specified units and reference.  (I already do offer some unit conversions).

**Comment by ericberman** [comment]
Other potential sources:
 - https://geographiclib.sourceforge.io/html/NET/index.html.  But it appears you need to add a 20MB data file to the server for this to work .
 -  https://github.com/vandry/geoidheight.  Need to translate from C++ to C#, also needs data file.

At this point, though, my strong inclination is to just point you to the geodid-height calculator above and let you do the conversion.  I really am unclear what problem this would solve, especially since you should always be flying on barometric altitude, not GPS.

**Comment by ericberman** [comment]
For CSV, only works if you know original units and convert to/from meters.  E.g., the iOS and Android apps record altitude converted to feet, need to convert to meters and then back to feet.
KML and GPX, on the other hand, have a different problem: we know it's meters, but there's no place to store the converted altitude (without losing the measured one).
Found a library and played with it (NetGeographic, https://geographiclib.sourceforge.io/html/NET/classNETGeographicLib_1_1Geoid.html), but it's not a signed binary and i can't run unsigned.

I think I've done enough investigation on this.  I'd suggest using theunavco link above to do the conversion yourself.

**Comment by ericberman** [comment]
another option to look at https://www.nuget.org/packages/GeoidHeightsDotNet/
