### ISSUE TITLE
Time spinner doesn't save value when pressing ok

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#796]
https://user-images.githubusercontent.com/1769078/127221917-336f790d-321d-4221-92f4-d8409b1a5ea5.mp4

When editing times using the spinner on Android, pressing ok during field editing doesn't save the value

**Comment by ericberman** [comment]
Is this attached to an android bug?  I'm not seeing it at https://github.com/ericberman/MyFlightbookAndroid/issues/, so I'll add one there.

It looks like this only happens if you (a) use the keyboard (i.e., if you swipe up/down to spin the time it's fine) and (b) dismiss the keyboard without hitting return/enter/OK/check.

From: zartom ***@***.***>
Sent: Tuesday, July 27, 2021 1:21 PM
To: ericberman/MyFlightbookWeb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ericberman/MyFlightbookWeb] Time spinner doesn't save value when pressing ok (#796)


https://user-images.githubusercontent.com/1769078/127221917-336f790d-321d-4221-92f4-d8409b1a5ea5.mp4<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1769078%2F127221917-336f790d-321d-4221-92f4-d8409b1a5ea5.mp4&data=04%7C01%7C%7Cdeb5b27f73004d13f7c608d9513c083e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637630140544613953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XvDWry7hcjyZVi1Soe6oIm84N3Pr9vcfeixNr5vfrRA%3D&reserved=0>

When editing times using the spinner on Android, pressing ok during field editing doesn't save the value

-

**Comment by zartom** [comment]
Sorry actually didn't realize I was on the web version GitHub. All four new issues... Can you move them there somehow?
You're right that it happens when typing only.
But you're incorrect about the dismissing. It is fine when using the blue checkmark button, but in the video I was pressing ok, not hiding the keyboard. Clicking on another field after typing the new time also works fine.

**Comment by ericberman** [comment]
I meant if you click on the pop-up keyboard's OK button, everything works.  If you type and then hide the keyboard and then press OK, that's when this happens.  anyhow, we should take this over to the Android issue, since it's not a web issue.
