### ISSUE TITLE
Suggestions: time preferences per aircraft

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#797]
On the app settings we have choice between HH:MM or HH.X formats, UTC or Local time, and how to calculate total time (block, flight, engine...)

However, these are mainly decided by the type of aircraft and not just by the user for all aircrafts. For example, a pilot could be flying a Cessna and an airliner. In this case, all three preferences above might be different for those two aircraft types

**Comment by ericberman** [comment]
I'm curious the basis for the assertion that this preference is decided by type of aircraft?  From my experience, it's far more of a where-are-you-from thing (E.g., Americans tend to use decimal, Europeans use hh:mm).

But lots of these times are also not tied to an aircraft.  E.g., your totals are displayed in hh:mm or decimal depending on your preference - and these are by definition aggregated across aircraft.  Plus, any table layout (print or screen) that mixes decimal and hh:mm is going to be a confusing nightmare.

My inclination is to not fix this...

**Comment by zartom** [comment]
In GA aircraft the Hobbs meter is XX.X.
On Boeing aircraft the OOOI (out off on in) page on the ACARS is HH:MM

in light GA aircrafts you're rarely go across timezones. On Boeings you do often. Also the ACARS flight log is in UTC

Also I only meant while editing a single flight's properties. Not when displaying lists and totals. That's fine and by personal preference

**Comment by ericberman** [comment]
Hobbs is (currently) decimal always.  Lots and lots of people use HH:MM in GA aircraft.

Not sure the significance of crossing timezones (which is not in fact uncommon).  Timezones can affect a point-in-time (e.g., block out, block on, etc.) and point-in-time is ALWAYS displayed in HH:MM notation (how can it not?).  But durations are unaffected by timezones: an 5 hour flight from Seattle to Boston (3 time zones) in a B737 or a 5 hour flight from Seattle to LA (1 time zone) in a fast piston are both...5 hour flights.  The timezone (or lack thereof) is irrelevant; whether to show it as 5:00 or as 5.0 is strictly a display preference thing.  Remember, in this context, "5:00" does *NOT* mean "5 o'clock" (which is impacted by timezones), it means "5 hours and no minutes."

For UTC: everything this is a point-in-time in the system is always, always, always UTC.  It is never in a local timezone.  otherwise you can't do the math.  Note that I may convert to/from a local timezone for display or ease of data entry, but it is always UTC.  So in the Seattle->Boston example, suppose I leave Seattle at 5pm local time on July 27 and arrive Boston at 1am the next day (local).  I can do this in UTC, where I have to do the math and remember that this is 00:00Z to 05:00Z on July 28, or I can use local time and enter 5pm on the 27th (letting the system convert it to 00:00Z on the 28th) when I depart and 1am on the 28th when I land.  

Note that if I'm using the mobile app (where it knows local time because of cell reception), if I use local time, then I'll enter "5pm on the 27th" for block-out while I'm in Seattle.  I now arrive in Boston and my phone has converted to Eastern time, so the block-out time now reads 8pm on the 27th.  That's because 5pm PDT on the 27th == 8pm on the 27th EDT == 00:00Z on the 28th.

But it's ALL still ALL UTC.

**Comment by zartom** [comment]
I think I wasn’t explaining myself right
I am talking about data and time inputs. Hobbs and ACARS are just two ways to show flight time in the aircraft but they display it differently 
Case in point: I’m inputting the block in and out as properties and that calculates my total time, cross country and such. But when I log a flight in a prop with out these block properties, I have to always calculate the flight time manually from the engine start and engine stop fields

**Comment by ericberman** [comment]
ahh, so the idea is that your jet time would autocompute total based on block but your cessna 150 time would key off of engine time or hobbs time?

Another way to do it would simply to have a cascading priority order.  That's actually what the web does when you click "Autofill".

**Comment by zartom** [comment]
That works

**Comment by ericberman** [comment]
I'll leave this issue here, but I think I may simply do a hack, whereby if you put #AFHOBBS# or "#AFTACH#, "#AFENG#, #AFFLT#, or "#AFBLK#" into the private notes for an aircraft, then the *MOBILE* apps will override their explicit auto-fill setting for that aircraft.  As said above, the website doesn't have such a setting (it uses a priority order when you press "Autofill"), so this doesn't really apply on the web.  But the mobile apps do autofill in real time as you modify source times, so you could set your default based on, say, your day job as a jet jockey, and then for your bug squasher on the weekends you can override it.

**Comment by ericberman** [comment]
I just added (not yet live on the app store) an explicit "autofill" command that lets you fill in missing values.  This will, like the website, use a priority order for determining total: hobbs (if both start and end are present), then block, then engine time, then flight time.  Assuming that the Boeing doesn't have hobbs meters, then you aren't filling in hobbs and using autofill will use block time.  And when you go for a $100 hamburger on the weekend in your club's C-172, it will use hobbs.

So I think this addresses the scenario you were trying to handle.

I need to code up the same for Android.  Will take live in the next week or two.

**Comment by zartom** [comment]
That's awesome thanks
I won't be flying this month so i'll check it next month
