### ISSUE TITLE
Bug: downloading telemetary as CSV and reuploading ends with "String was not recognized as a valid DateTime." error

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#835]
I think the reason is that the downloaded file does not include the last "UTC DATETIME" header

**Comment by ericberman** [comment]
Nope, that's not the issue.
The issue is that the UTC DateTime column is expressed d/m/y hh:mm (e.g., "17/09/2021 15:15").  A naked date can be in your regional format, but a full date+time is expected to be in yyyy-mm-dd hh:mm.

What format was your *original* file in?

**Comment by ericberman** [comment]
Indeed, just verified: when CONVERTING a file, the system uses your current locale (as expressed by your browser).  The piece of code, though, that emits each data element doesn't know anything about the semantics of each item, it just asks the system to render it as text.

I'm somewhat loathe to try to force all dates into yyyy-mm-dd format, I don't know what doing so might break elsewhere, although that is a pretty universal (and unambiguous) format - nobody uses yyyy-dd-mm, to my knowledge.

Or, I could make the parsing more flexible to accept a regionally-specified date before the time.  That too has its own challenges.  Right now, I'm asking the system to read it, and ironically even though the system renders as I described, it doesn't seem to parse it the same.

**Comment by ericberman** [comment]
But your simple workaround is to tell Excel (or whatever spreadsheet your using for the CSV) to reformat the datetimes into yyyy-mm-dd hh:mm.  Works like a charm if you do that.

**Comment by ericberman** [comment]
Ahh...also realized, all flight data is always done in the invariant culture.  That's part of the problem as well: I have to ignore current culture when importing because most apps worldwide use the "invariant" culture (periods for decimal separators, etc.) 

That's why the system can't read what it wrote - it writes using your current culture so that you can load it correctly.  E.g., in France, you would express a 90 minute flight in decimal as "1,5" hours.  If I were to write "1.5" in the converted spreadsheet, then when you load it into Excel on a French system it wouldn't recognize it correctly.  That's why I write using your local conventions - I'm writing for *your* consumption.

But lots of CSV comes in from around the world, and apps that generate this (e.g., Garmin logs out of the panel) always use Invariant (basically US) conventions, like periods for decimals.  So the code on import always uses invariant.  As a result, if you try to import that hypothetical French spreadsheet with "1,5", I won't handle that correctly either.

This isn't a bug; it's by design.  You're making a (reasonable) feature request for NEW functionality to support round-trip editing of flight data.  Unfortunately, that is almost certainly a "won't-fix" because of these internationalization issues.

By the way, there are other issues with round-tripping that are out of my hands, separate from the date-format issue.  One that comes to mind is quantization that happens in Excel.  When Excel sees a date+time, it truncates the seconds.  So if you have, say, a sample at "2021-09-17 14:22:21" followed by one 2 seconds later at ""2021-09-17 14:22:23", Excel will display them both as ""2021-09-17 14:22", and when you save as CSV, it will only save the "14:22", and the seconds are lost forever.  As a result you get clumps of samples at minute intervals, rather than a smooth continuous dataset.  You need to explicitly tell Excel to use hh:mm:ss to avoid this, but it's super easy to forget to do this (I have done it a bunch of times myself)

I think the correct way to address this, then, is threefold:
 * Don't convert to CSV.  Download the original format (I do no transformation on your data if you do that) and edit/re-upload that.
 * Or, make sure your data is formatted using US conventions (periods for decimals, yyyy-mm-dd for any date and yyyy-mm-dd hh:mm:ss for any date time!) 
 * Best: I should implement issue #834 , since (I presume) that's actually the problem you were trying to solve.
