### ISSUE TITLE
Auto calculate canadian medical expiry

### ISSUE THREAD

**Issue by fkrauthan** [ericberman/MyFlightbookWeb#887]
Similar to how the medical expiry is auto calculated for the US it would be great if Canadian rules could be implemented as well.

The rules are as follow:

**Category 1**

- Age <40 years: 1 year
- Age >= 40 <= 60 years with two people: 1 year (probably can't be represented) otherwise 1/2 year
- Age >=60 years: 1/2 year

Auto converts to **Category 3** after expiry and then follows **Category 3** rules.

**Category 3**

- Age <40 years: 5 years
- Age >=40 years: 2 years

All medical expires on the first day of the month that following the date of examination.

**Comment by ericberman** [comment]
What do you mean "with two people?"

Category 1 basically matches EASA 1st class, except: (a) EASA is day for day (exam on Nov 15 means expiration is end-of-day Nov 15 a year later, for the 1 year case), and (b) the distinction of 1 year vs. 6 months between age 40/60 is for ATP operations (6 months) vs. other privileges (1 year)

So I'm assuming Canadian category 1 would  be a delta off of EASA 1st class.

For category 3 - that matches US category 3, so that's already there.

"expire on the first day of the month that following the date of the examination" - just for clarity, if I'm 38 years old and get a category 3 exam on Nov 18 of 2021, then I am good until midnight of Nov 30 of 2026; at 00:01 on Dec 1 2026, I my medical is invalid.  Correct?

**Comment by fkrauthan** [comment]
I think Canadian rule is weird for Cat 1. If you have a plane that requires two pilots then the 2 people rule apply. Otherwise for single pilots its 1/2 year after 40.

And you are correct with your example.

**Comment by ericberman** [comment]
I think this will be easy, but one last request, please: can you point me to the regs?  I like to keep a URL reference to them in the code (or at least a document chapter/verse reference) so that if someone asks a question or whatever, I can go find the authoritative document.  Not questioning you, but "This is what Florian told me" doesn't cut it. :)

**Comment by ericberman** [comment]
I'm specifically looking for something from Transport Canada.  Google isn't being very helpful - and the TC website itself isn't either.  I'm finding a lot of information about covid and medicals, but that's not relevant.

**Comment by fkrauthan** [comment]
I could not find anything online. But each Canadian License booklet has this section in it: https://photos.app.goo.gl/No2ze9y54U3tKH8t8

**Comment by fkrauthan** [comment]
Oh actually find the CARS paragraph too: https://laws-lois.justice.gc.ca/eng/regulations/sor-96-433/page-36.html#h-991054 check the section 404.04

**Comment by ericberman** [comment]
Ding ding ding!!! https://laws-lois.justice.gc.ca/eng/regulations/sor-96-433/page-36.html#h-991075 has what I wanted, including something I can cite: 404.04(6)

**Comment by ericberman** [comment]
Actually - still need a reference - I don't see anything in the above link that says anything about category 1 and category 3 (is there no "category 2"?)

**Comment by ericberman** [comment]
This just talks about PPL, Commercial, and commercial-single-pilot

**Comment by fkrauthan** [comment]
For PPL you need a Category 3 (so that's the PPL times that apply)
And for CPL you need Category 1 I believe there is a Category 2 but that does not apply to pilots (might be air traffic controllers or something like that)

**Comment by fkrauthan** [comment]
This is not an official source but maybe helps: http://roccolombardi.ca/index.php/forms-resources/medical-certification-categories
