### ISSUE TITLE
Years displayed twice on the analysis graph

### ISSUE THREAD

**Issue by CDFriend** [ericberman/MyFlightbookWeb#903]
When I use the analysis view and group my flight times by year, I can see the each year printed twice on the x-axis. 
![2022-01-30 20_40_01-Window](https://user-images.githubusercontent.com/8661121/151740151-e8334502-0bc5-4952-9b38-475ca807c446.png)

**Comment by ericberman** [comment]
Probably not much I can do about that - it's google chart's issue, and it's not technically a "bug"; looks like they're doing the time based on Jan 1 and Jul 1 of each year for purposes of the axis, but I'm just formatting it as year. 

I can investigate to see  if I can specify a tighter granularity, but since each bar covers 2 half-year periods on the scale, the graph is technically accurate.

Note that this can also go in the other direction.  E.g., the image below is from my logbook - here Google is just showing a label every other year.  Also still correct.

![image](https://user-images.githubusercontent.com/16455286/151744282-252d308b-3074-4bb4-a203-2b106072b60e.png)

**Comment by ericberman** [comment]
Indeed, I'm setting "showTextEvery" on the horizontal axis to "1" (and setting the formatting to , but Google's chart algorithm still shows minor axis marks and thus can show labels on those axes.  

If I set the format to show month/day as well, you can see it's doing Jan 1 and July 1:
![image](https://user-images.githubusercontent.com/16455286/151847030-404222c5-69a7-4595-894e-dce906c6069c.png)

**Comment by CDFriend** [comment]
Interesting, seems odd that it'd be grouping by half year increments when we've selected group by year. 

If this is a limitation of google charts, would it be worthwhile to switch to a different charting library like D3? I'm happy to look into this and contribute a PR here.

**Comment by ericberman** [comment]
Not at all opposed to switching to another library (I'm not familiar with D3); I'm not married to google.

the relevant modules are:
 * AppCode\Charting\googlechart.cs
 * Controls\googlechart.ascx and ascx.cs.
