### ISSUE TITLE
Feature suggestion: new achievements and stats

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#928]
Examples:
Averages: Averages flights per year, average flight time, distance, etc.
Quickest 100/1000 hours (from/to date)
Number of countries and states visited
Most Northerly/Southerly/Westerly/Easterly airports visited
Highest/lowest elevation airport visited
Long/short runway (if possible to determine using a public database and/or flight entry properties)

**Comment by ericberman** [comment]
Hi, Tom.  Already have a bunch of this.

Averages: use the Analysis tab.  You can then search for a given time period, and it will show you the average:
![image](https://user-images.githubusercontent.com/16455286/164047294-8bfb32a0-3923-42bb-992b-a9b3f07fc0e4.png)

Countries/states - I already have achievements for a bunch of these, but of course achievements are deliberately opaque (meant to be easter eggs of a sort).  However, if you go to the Visited Airports, page, it's all laid out for you:
![image](https://user-images.githubusercontent.com/16455286/164047579-0d38c45d-2d1c-4e85-af58-1b06e900a2e5.png)

I'd also think you could eyeball that page to see the most northerly/southerly/easterly/westerly airports, no?

I can't do elevation or runway length because I don't have that information.  Lots of user-defined airports, and for most countries outside of the US I gather the data from a variety of sources, and those aren't part of the lowest-common-denominator.  That said, I do know of, say, the lowest and highest (public) airports in the US and there are achievements related to those.

So I think the main remaining thing is the quickest 100/1000 hours.  That's an interesting one, and you can't get it by any simple eyeball.
