### ISSUE TITLE
adding a new Anonymous aircraft adds public notes

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#976]
![image](https://user-images.githubusercontent.com/1769078/188589246-c10c1ada-037b-4b90-a818-0cddf981463e.png)

**Comment by ericberman** [comment]
Not sure I follow what the bug is here.  Those notes are on that aircraft and have been for a while (I just looked on my laptop, which has a database snapshot from July, and #004308 has those weird notes).  Anonymous aircraft are all shared, and public notes on an aircraft are also shared, so if you add an anonymous aircraft to your account that already has public notes attached to it, then you will pick up those public notes.  This functionality is by design.

So I don't think there's a bug here.  Or am I missing the issue?

**Comment by zartom** [comment]
I guess I didn't understand why Anonymous aircraft should have public notes then... since they are very general by design. Maybe it would have more value as "type public notes" rather than "tail number notes"

**Comment by ericberman** [comment]
An anonymous aircraft is really just an aircraft with a stylized tail number.  You'll notice the "#004308".  I use that as a tailnumber, with "#" cueing me that it's anonymous, and 004308 is quite literally the model # for which it is anonymous (i.e., the PA-28-235 is model 4308 in the database).  But it's still treated as an aircraft (not a model!) every other respect.  Note that this doesn't say "tail number notes" - it's "aircraft notes".
