### ISSUE TITLE
Copying from excel when creating a new aircraft model adds both text and photo

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#977]
![image](https://user-images.githubusercontent.com/1769078/188589541-62cb139a-4f14-4833-bc05-f89fada4bd52.png)

**Comment by ericberman** [comment]
Oh, that's funny.  Excel is putting both text and an image on the clipboard.  You can paste pictures that are on the clipboard (I think that was your request?), but I listen for a paste of a picture on the whole page because you can't easily put the focus on the "Drop files here" box.  If you paste into, say, notepad and then cut again, the image is lost from the clipboard and so it's only text on the clipboard.

I am not entirely sure how best to handle this...will have to give it some thought.

**Comment by zartom** [comment]
Actually, I copied the model name text box for rapid additions to the aircraft list

**Comment by ericberman** [comment]
Right. And at least when I was able to reproduce this earlier, I had both text and a picture on the clipboard. I’m grabbing the picture because I’m seeing there. Even though you only copied text, XL put an image as well

**Comment by ericberman** [comment]
So if you copy a cell from Excel and do "Paste Special" into word, you can get a sense of the multiple versions on the clipboard:
![image](https://user-images.githubusercontent.com/16455286/188768950-90b33875-d97a-4488-81c2-956e9aaacb28.png)

I listen for paste events at the document level.  On paste, I'm iterating through these and if I see an image, I grab it; otherwise, I let it through to the default behavior.

Here's what I see from Excel - note that there are 3 text versions, and...an image:
![image](https://user-images.githubusercontent.com/16455286/188769487-7ec76841-c06c-485f-9163-625447de9bba.png)

I suppose that I could check to see if (a) the current focused item is an input and (b) if text is on the clipboard, I could then resign and let the default behavior happen.
